### Before the start

In [ ]:
# # before start
# %pip install tld
# %pip install category_encoders

# ! pip install pytz
# !pip install timezonefinder
# !pip install geopy

# !pip3 install torch
# !pip3 install torchvision
# !pip3 install tqdm

# !pip install torch -q
# !pip install keras

# !pip install skorch
# !pip install bayesian-optimization

# # !pip install cudf
# # !pip install cudf-cu11==22.12 rmm-cu11==22.12 dask-cudf-cu11==22.12 --extra-index-url=https://pypi.ngc.nvidia.com/

In [ ]:
# load data and import libraries
import pandas as pd
import numpy as np
import pytz
# from geopy.geocoders import Nominatim
# from timezonefinder import TimezoneFinder
import datetime

import torch
# For layers and models
import torch.nn as nn
# For activation functions (F.sigmoid is deprecated)
import torch.nn.functional as F
from torch import sigmoid

import os
import warnings
warnings.filterwarnings("ignore")
from torch.utils.data import Dataset, DataLoader
# Collection of optimizers
import torch.optim as optim

# use_cuda = torch.cuda.is_available()
# device = torch.device("cuda" if use_cuda else "cpu")
# model = CustomModel().to(device)

### ANN preprocessing

In [ ]:
new_labels = [
    "Sport",
    "Hobby Passive",
    "Work&Study",
    "Daily Routine"
]
match_labels_v3 = [0,3,0,1,2,2,3]

match_labels = {
    "Sport": 0,
    "Food": 3,
    "Hobby Active": 0,
    "Hobby Passive": 1,
    "Studying":2,
    "Work":2,
    "Other":3
}


In [ ]:
df = pd.read_csv('schedule.csv')

df['Label Number'] = df['Label'].apply(lambda x: match_labels[x])
df['Label Name'] = df['Label Number'].apply(lambda x: new_labels[x])

df.drop(columns=['Label', 'Activity', 'End Time', 'If Has Deadline', 'Deadline Time', 'Deadline Date'], inplace=True)

mini = df['Importance'].min()
maxi = df['Importance'].max()
df['Importance'] = df['Importance'].apply(lambda x: int((x-mini) / (maxi-mini) * 3) )

df[:13]

Date Start Time  Duration  Importance  Label Number     Label Name
0   2023-06-16      07:00        60           1             3  Daily Routine
1   2023-06-16      08:15        45           2             0          Sport
2   2023-06-16      09:15        60           0             1  Hobby Passive
3   2023-06-16      10:30        45           3             2     Work&Study
4   2023-06-16      11:30        60           1             3  Daily Routine
5   2023-06-16      13:00        60           2             2     Work&Study
6   2023-06-16      14:15        30           0             0          Sport
7   2023-06-16      15:00        90           1             2     Work&Study
8   2023-06-16      17:00        45           1             3  Daily Routine
9   2023-06-16      18:00        45           2             0          Sport
10  2023-06-16      19:00        60           1             1  Hobby Passive
11  2023-06-16      20:15        30           0             1  Hobby Passive
12  2023-06-16      21:00        60           0             3  Daily Routine

In [ ]:
from sklearn.preprocessing import OneHotEncoder

def encode_features(df, features_name, encoder):
    new_features = encoder.transform(df[features_name])
    # create dataframe from encoded features with named columns
    new_columns = pd.DataFrame(new_features, columns=encoder.get_feature_names_out())
    new_df = pd.concat([df, new_columns], axis=1)
    # new_df.drop(features_name, axis=1, inplace=True)
    return new_df

encoder = OneHotEncoder(sparse=False, drop='first')
enc_column = ['Label Number']
encoder.fit(df[enc_column])
df = encode_features(df, enc_column, encoder)

df

Date Start Time  Duration  Importance  Label Number     Label Name  \
0    2023-06-16      07:00        60           1             3  Daily Routine   
1    2023-06-16      08:15        45           2             0          Sport   
2    2023-06-16      09:15        60           0             1  Hobby Passive   
3    2023-06-16      10:30        45           3             2     Work&Study   
4    2023-06-16      11:30        60           1             3  Daily Routine   
..          ...        ...       ...         ...           ...            ...   
249  2023-07-07      15:45        90           2             2     Work&Study   
250  2023-07-07      17:30        45           1             3  Daily Routine   
251  2023-07-07      18:30        90           1             0          Sport   
252  2023-07-07      20:15        90           2             3  Daily Routine   
253  2023-07-07      22:00        60           0             3  Daily Routine   

     Label Number_1  Label Number_2  Label Number_3  
0               0.0             0.0             1.0  
1               0.0             0.0             0.0  
2               1.0             0.0             0.0  
3               0.0             1.0             0.0  
4               0.0             0.0             1.0  
..              ...             ...             ...  
249             0.0             1.0             0.0  
250             0.0             0.0             1.0  
251             0.0             0.0             0.0  
252             0.0             0.0             1.0  
253             0.0             0.0             1.0  

[254 rows x 9 columns]

In [ ]:
def make_true_duration(x, prob=1.3):
    true_noise = [[-5,20], [-15,0], [-20,5], [-10,30]]
    addi = np.random.uniform(low=prob*true_noise[x['Label Number']][0], high=prob * true_noise[x['Label Number']][1])
    result= x['Duration'] + int(addi)
    if addi > true_noise[x['Label Number']][1]:
        result= x['Duration'] + true_noise[x['Label Number']][1]
    elif addi < true_noise[x['Label Number']][0]:
        result= x['Duration'] + true_noise[x['Label Number']][0]
    if result < 10:
        return 10
    return result

df['True Duration'] = df.apply(lambda x: make_true_duration(x), axis=1)
df

Date Start Time  Duration  Importance  Label Number     Label Name  \
0    2023-06-16      07:00        60           1             3  Daily Routine   
1    2023-06-16      08:15        45           2             0          Sport   
2    2023-06-16      09:15        60           0             1  Hobby Passive   
3    2023-06-16      10:30        45           3             2     Work&Study   
4    2023-06-16      11:30        60           1             3  Daily Routine   
..          ...        ...       ...         ...           ...            ...   
249  2023-07-07      15:45        90           2             2     Work&Study   
250  2023-07-07      17:30        45           1             3  Daily Routine   
251  2023-07-07      18:30        90           1             0          Sport   
252  2023-07-07      20:15        90           2             3  Daily Routine   
253  2023-07-07      22:00        60           0             3  Daily Routine   

     Label Number_1  Label Number_2  Label Number_3  True Duration  
0               0.0             0.0             1.0             90  
1               0.0             0.0             0.0             64  
2               1.0             0.0             0.0             45  
3               0.0             1.0             0.0             25  
4               0.0             0.0             1.0             77  
..              ...             ...             ...            ...  
249             0.0             1.0             0.0             71  
250             0.0             0.0             1.0             57  
251             0.0             0.0             0.0             97  
252             0.0             0.0             1.0            103  
253             0.0             0.0             1.0             60  

[254 rows x 10 columns]

In [ ]:
min_time = datetime.datetime.strptime("00:00", '%H:%M')
max_time = ((datetime.datetime.strptime("23:59", '%H:%M')-min_time).total_seconds()+1)//60
# df['Start Time'] = df['Start Time'].apply(lambda x: ((datetime.datetime.strptime(x, '%H:%M')-min_time).total_seconds()+1)/max_time)
df['Start Time'] = df['Start Time'].apply(lambda x: (datetime.datetime.strptime(x, '%H:%M')-min_time).total_seconds()//60)

# move start time
cur_day = '1/1/2020'
delta = 0

for index, row in df.iterrows():
    if row['Date'] != cur_day:
        delta = row['Start Time']
        cur_day = row['Date']
    df.at[index, 'Start Time'] -= delta

df['True Start Time'] = df['Start Time']
df.describe()

Start Time    Duration  Importance  Label Number  Label Number_1  \
count  254.000000  254.000000  254.000000    254.000000      254.000000   
mean   426.496063   66.259843    1.251969      1.779528        0.110236   
std    278.493487   19.999689    0.897678      1.231429        0.313802   
min      0.000000   30.000000    0.000000      0.000000        0.000000   
25%    180.000000   45.000000    1.000000      0.000000        0.000000   
50%    420.000000   60.000000    1.000000      2.000000        0.000000   
75%    660.000000   90.000000    2.000000      3.000000        0.000000   
max    900.000000   90.000000    3.000000      3.000000        1.000000   

       Label Number_2  Label Number_3  True Duration  True Start Time  
count      254.000000      254.000000     254.000000       254.000000  
mean         0.220472        0.409449      70.877953       426.496063  
std          0.415384        0.492703      23.796836       278.493487  
min          0.000000        0.000000      15.000000         0.000000  
25%          0.000000        0.000000      52.000000       180.000000  
50%          0.000000        0.000000      70.500000       420.000000  
75%          0.000000        1.000000      90.000000       660.000000  
max          1.000000        1.000000     120.000000       900.000000

In [ ]:
TS_DUR =10
LENGTH = 1200

def parse_date(d):
    res = [int(i) for i in d.split('/')[::-1]]
    return datetime.date(*res)

cur_day = '1/1/2020'
# basic_slots = [0]*(2*60//10)+[1]*(3*60//10)+[0]*(2*60//10)
basic_slots = [0]*(LENGTH//TS_DUR)

available_time_slots = [0]*(LENGTH//TS_DUR)
names = ['TS'+str(i) for i in range(len(available_time_slots))]
df[names] = available_time_slots

for index, row in df.iterrows():
    if row['Date'] == cur_day:
        df.loc[index, names] = available_time_slots.copy()
    else:
        cur_day = row['Date']
        available_time_slots = basic_slots.copy()
        df.loc[index, names] = available_time_slots.copy()
    start = int(row['True Start Time'] / TS_DUR)
    end = int((row['True Start Time'] + row['True Duration']) // TS_DUR) + [1 if (row['True Start Time'] + row['True Duration']) % TS_DUR > 0 else 0][0]
    # print(start, end, row['True Duration'] )
    df.loc[index, 'Summ'] = sum(available_time_slots)

    available_time_slots[start:end+1] = [1]*(end-start+1)
    # print(index, available_time_slots)

df

Date  Start Time  Duration  Importance  Label Number  \
0    2023-06-16         0.0        60           1             3   
1    2023-06-16        75.0        45           2             0   
2    2023-06-16       135.0        60           0             1   
3    2023-06-16       210.0        45           3             2   
4    2023-06-16       270.0        60           1             3   
..          ...         ...       ...         ...           ...   
249  2023-07-07       525.0        90           2             2   
250  2023-07-07       630.0        45           1             3   
251  2023-07-07       690.0        90           1             0   
252  2023-07-07       795.0        90           2             3   
253  2023-07-07       900.0        60           0             3   

        Label Name  Label Number_1  Label Number_2  Label Number_3  \
0    Daily Routine             0.0             0.0             1.0   
1            Sport             0.0             0.0             0.0   
2    Hobby Passive             1.0             0.0             0.0   
3       Work&Study             0.0             1.0             0.0   
4    Daily Routine             0.0             0.0             1.0   
..             ...             ...             ...             ...   
249     Work&Study             0.0             1.0             0.0   
250  Daily Routine             0.0             0.0             1.0   
251          Sport             0.0             0.0             0.0   
252  Daily Routine             0.0             0.0             1.0   
253  Daily Routine             0.0             0.0             1.0   

     True Duration  ...  TS111  TS112  TS113  TS114  TS115  TS116  TS117  \
0               90  ...      0      0      0      0      0      0      0   
1               64  ...      0      0      0      0      0      0      0   
2               45  ...      0      0      0      0      0      0      0   
3               25  ...      0      0      0      0      0      0      0   
4               77  ...      0      0      0      0      0      0      0   
..             ...  ...    ...    ...    ...    ...    ...    ...    ...   
249             71  ...      0      0      0      0      0      0      0   
250             57  ...      0      0      0      0      0      0      0   
251             97  ...      0      0      0      0      0      0      0   
252            103  ...      0      0      0      0      0      0      0   
253             60  ...      0      0      0      0      0      0      0   

     TS118  TS119  Summ  
0        0      0   0.0  
1        0      0  10.0  
2        0      0  15.0  
3        0      0  19.0  
4        0      0  23.0  
..     ...    ...   ...  
249      0      0  53.0  
250      0      0  60.0  
251      0      0  67.0  
252      0      0  77.0  
253      0      0  88.0  

[254 rows x 132 columns]

In [ ]:
# scaling
df['Importance'] = df['Importance'] / 3

df.drop(columns=['Label Name'], inplace=True)

df['Duration'] = df['Duration'] / (6*60)
df['True Duration'] = df['True Duration'] / (6*60)

df

Date  Start Time  Duration  Importance  Label Number  \
0    2023-06-16         0.0  0.166667    0.333333             3   
1    2023-06-16        75.0  0.125000    0.666667             0   
2    2023-06-16       135.0  0.166667    0.000000             1   
3    2023-06-16       210.0  0.125000    1.000000             2   
4    2023-06-16       270.0  0.166667    0.333333             3   
..          ...         ...       ...         ...           ...   
249  2023-07-07       525.0  0.250000    0.666667             2   
250  2023-07-07       630.0  0.125000    0.333333             3   
251  2023-07-07       690.0  0.250000    0.333333             0   
252  2023-07-07       795.0  0.250000    0.666667             3   
253  2023-07-07       900.0  0.166667    0.000000             3   

     Label Number_1  Label Number_2  Label Number_3  True Duration  \
0               0.0             0.0             1.0       0.250000   
1               0.0             0.0             0.0       0.177778   
2               1.0             0.0             0.0       0.125000   
3               0.0             1.0             0.0       0.069444   
4               0.0             0.0             1.0       0.213889   
..              ...             ...             ...            ...   
249             0.0             1.0             0.0       0.197222   
250             0.0             0.0             1.0       0.158333   
251             0.0             0.0             0.0       0.269444   
252             0.0             0.0             1.0       0.286111   
253             0.0             0.0             1.0       0.166667   

     True Start Time  ...  TS111  TS112  TS113  TS114  TS115  TS116  TS117  \
0                0.0  ...      0      0      0      0      0      0      0   
1               75.0  ...      0      0      0      0      0      0      0   
2              135.0  ...      0      0      0      0      0      0      0   
3              210.0  ...      0      0      0      0      0      0      0   
4              270.0  ...      0      0      0      0      0      0      0   
..               ...  ...    ...    ...    ...    ...    ...    ...    ...   
249            525.0  ...      0      0      0      0      0      0      0   
250            630.0  ...      0      0      0      0      0      0      0   
251            690.0  ...      0      0      0      0      0      0      0   
252            795.0  ...      0      0      0      0      0      0      0   
253            900.0  ...      0      0      0      0      0      0      0   

     TS118  TS119  Summ  
0        0      0   0.0  
1        0      0  10.0  
2        0      0  15.0  
3        0      0  19.0  
4        0      0  23.0  
..     ...    ...   ...  
249      0      0  53.0  
250      0      0  60.0  
251      0      0  67.0  
252      0      0  77.0  
253      0      0  88.0  

[254 rows x 131 columns]

In [ ]:
def drop_some_values(x, prob=0.95 ):
    if np.random.uniform() > prob:
        return 0
    return x

df['Duration'] = df['Duration'].apply(lambda x: drop_some_values(x))

df['Start Time'] = df['Start Time'] / max_time
df['True Start Time'] = df['Start Time']
df['Start Time'] = df['Start Time'].apply(lambda x: drop_some_values(x))
df.describe()

Start Time    Duration  Importance  Label Number  Label Number_1  \
count  254.000000  254.000000  254.000000    254.000000      254.000000   
mean     0.281240    0.173228    0.417323      1.779528        0.110236   
std      0.198370    0.068295    0.299226      1.231429        0.313802   
min      0.000000    0.000000    0.000000      0.000000        0.000000   
25%      0.093815    0.125000    0.333333      0.000000        0.000000   
50%      0.260598    0.166667    0.333333      2.000000        0.000000   
75%      0.458652    0.250000    0.666667      3.000000        0.000000   
max      0.625434    0.250000    1.000000      3.000000        1.000000   

       Label Number_2  Label Number_3  True Duration  True Start Time  \
count      254.000000      254.000000     254.000000       254.000000   
mean         0.220472        0.409449       0.196883         0.296384   
std          0.415384        0.492703       0.066102         0.193533   
min          0.000000        0.000000       0.041667         0.000000   
25%          0.000000        0.000000       0.144444         0.125087   
50%          0.000000        0.000000       0.195833         0.291869   
75%          0.000000        1.000000       0.250000         0.458652   
max          1.000000        1.000000       0.333333         0.625434   

              TS0  ...  TS111  TS112  TS113  TS114  TS115  TS116  TS117  \
count  254.000000  ...  254.0  254.0  254.0  254.0  254.0  254.0  254.0   
mean     0.913386  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
std      0.281824  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
min      0.000000  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
25%      1.000000  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
50%      1.000000  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
75%      1.000000  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
max      1.000000  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

       TS118  TS119        Summ  
count  254.0  254.0  254.000000  
mean     0.0    0.0   40.767717  
std      0.0    0.0   26.283292  
min      0.0    0.0    0.000000  
25%      0.0    0.0   19.250000  
50%      0.0    0.0   39.000000  
75%      0.0    0.0   63.000000  
max      0.0    0.0   91.000000  

[8 rows x 130 columns]

In [ ]:
df

Date  Start Time  Duration  Importance  Label Number  \
0    2023-06-16    0.000000  0.166667    0.333333             3   
1    2023-06-16    0.052120  0.125000    0.666667             0   
2    2023-06-16    0.093815  0.166667    0.000000             1   
3    2023-06-16    0.145935  0.125000    1.000000             2   
4    2023-06-16    0.187630  0.166667    0.333333             3   
..          ...         ...       ...         ...           ...   
249  2023-07-07    0.364837  0.000000    0.666667             2   
250  2023-07-07    0.437804  0.125000    0.333333             3   
251  2023-07-07    0.479500  0.250000    0.333333             0   
252  2023-07-07    0.552467  0.250000    0.666667             3   
253  2023-07-07    0.625434  0.166667    0.000000             3   

     Label Number_1  Label Number_2  Label Number_3  True Duration  \
0               0.0             0.0             1.0       0.250000   
1               0.0             0.0             0.0       0.177778   
2               1.0             0.0             0.0       0.125000   
3               0.0             1.0             0.0       0.069444   
4               0.0             0.0             1.0       0.213889   
..              ...             ...             ...            ...   
249             0.0             1.0             0.0       0.197222   
250             0.0             0.0             1.0       0.158333   
251             0.0             0.0             0.0       0.269444   
252             0.0             0.0             1.0       0.286111   
253             0.0             0.0             1.0       0.166667   

     True Start Time  ...  TS111  TS112  TS113  TS114  TS115  TS116  TS117  \
0           0.000000  ...      0      0      0      0      0      0      0   
1           0.052120  ...      0      0      0      0      0      0      0   
2           0.093815  ...      0      0      0      0      0      0      0   
3           0.145935  ...      0      0      0      0      0      0      0   
4           0.187630  ...      0      0      0      0      0      0      0   
..               ...  ...    ...    ...    ...    ...    ...    ...    ...   
249         0.364837  ...      0      0      0      0      0      0      0   
250         0.437804  ...      0      0      0      0      0      0      0   
251         0.479500  ...      0      0      0      0      0      0      0   
252         0.552467  ...      0      0      0      0      0      0      0   
253         0.625434  ...      0      0      0      0      0      0      0   

     TS118  TS119  Summ  
0        0      0   0.0  
1        0      0  10.0  
2        0      0  15.0  
3        0      0  19.0  
4        0      0  23.0  
..     ...    ...   ...  
249      0      0  53.0  
250      0      0  60.0  
251      0      0  67.0  
252      0      0  77.0  
253      0      0  88.0  

[254 rows x 131 columns]

### Test train dataset

In [ ]:
X = df.drop(columns=['Date', 'True Duration', 'True Start Time', 'Label Number', 'Summ'])
y = df[['True Start Time', 'True Duration']]

In [ ]:
len(X.columns)

126

In [ ]:
y.describe()

True Start Time  True Duration
count       254.000000     254.000000
mean          0.296384       0.196883
std           0.193533       0.066102
min           0.000000       0.041667
25%           0.125087       0.144444
50%           0.291869       0.195833
75%           0.458652       0.250000
max           0.625434       0.333333

In [ ]:
X = X.to_numpy()
y = y.to_numpy()


In [ ]:
y

array([[0.        , 0.25      ],
       [0.05211953, 0.17777778],
       [0.09381515, 0.125     ],
       [0.14593468, 0.06944444],
       [0.1876303 , 0.21388889],
       [0.25017373, 0.11666667],
       [0.30229326, 0.09444444],
       [0.33356498, 0.21388889],
       [0.41695622, 0.10833333],
       [0.45865184, 0.13888889],
       [0.50034746, 0.125     ],
       [0.55246699, 0.04166667],
       [0.58373871, 0.22777778],
       [0.        , 0.225     ],
       [0.05211953, 0.17777778],
       [0.09381515, 0.19444444],
       [0.16678249, 0.10555556],
       [0.20847811, 0.11944444],
       [0.26059764, 0.27777778],
       [0.33356498, 0.19444444],
       [0.41695622, 0.16666667],
       [0.45865184, 0.24722222],
       [0.53161918, 0.31388889],
       [0.60458652, 0.20277778],
       [0.        , 0.14166667],
       [0.05211953, 0.30555556],
       [0.12508687, 0.125     ],
       [0.17720639, 0.11944444],
       [0.21890202, 0.25      ],
       [0.29186935, 0.3       ],
       [0.

In [ ]:
len(torch.tensor(y,dtype=torch.float32))

254

In [ ]:
from sklearn.model_selection import train_test_split

class TaskDataset(Dataset):
  def __init__(self,X, y):
    self.x_train=torch.tensor(X,dtype=torch.float32)
    self.y_train=torch.tensor(y,dtype=torch.float32)

  def __len__(self):
    return len(self.y_train)

  def __getitem__(self,idx):
    return self.x_train[idx], self.y_train[idx]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, shuffle=False)
datasets = {
    'train': TaskDataset(X_train, y_train),
    'test': TaskDataset(X_test, y_test)
}

batch_size = 10
dataloaders = {
    'train': DataLoader(datasets['train'], batch_size=batch_size, shuffle=False),
    # 'val': DataLoader(valData, batch_size=batch_size, shuffle=False),
    'test': DataLoader(datasets['test'], batch_size=batch_size, shuffle=False)
}

### Model designing

In [ ]:
# Device configuration
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

device(type='cpu')

In [ ]:
# Definition of the very simple network with 1 hidden layer
class SimpleScheduler(nn.Module):
    def __init__(self, input_n=126):
        # Invoke the parent's constructor
        super(SimpleScheduler, self).__init__()
        # nn implements feedworward layer as nn.Linear(a, b),
        # where a, b - input and output dims of weight matrix.
        # Bias is included by default.
        self.hidden = nn.Linear(input_n, 50)
        self.output = nn.Linear(50, 2)


    def forward(self, x):
        # You can write the result of sigmoid to a local variable,
        # but the common style in torch is to re-write x after computation of each layer
        x = F.relu(self.hidden(x))
        x = self.output(x)
        return x


model1 = SimpleScheduler().to(device)

print(f"SimpleScheduler model architecture:\n {model1}")
print("\n")

SimpleScheduler model architecture:
 SimpleScheduler(
  (hidden): Linear(in_features=126, out_features=50, bias=True)
  (output): Linear(in_features=50, out_features=2, bias=True)
)




In [ ]:
# Set hyperparameters
# Number of iterations over the whole data set
epochs = 50
# Learning rate for Stochastic Gradient Descent
lr = 0.005
# SGD parameter to accelerate the optimization, check https://paperswithcode.com/method/sgd-with-momentum
momentum = 0.5
# Loss function - cross entropy, the multiclass variant of that you used in Lab 3
criterion = nn.HuberLoss()

In [ ]:
from tqdm import tqdm

def train( model, device, train_loader, optimizer, epoch):
    # Do not forget to set train() to update weights of model
    model.train()
    # A wrapper over data loader to show progress bar
    bar = tqdm(train_loader)
    iteration = 0
    overall_loss = 0
    for data, target in bar:
        # Device of data and model must be the same
        data, target = data.to(device), target.to(device)
        # To avoid an accumulation of gradients
        optimizer.zero_grad()
        # Prediction
        output = model(data)
        # Error between prediction and ground truth
        loss = criterion(output, target)
        # Compute gradient
        loss.backward()
        # Update params of model
        optimizer.step()

        iteration += 1
        overall_loss += loss.item()
        bar.set_postfix({"Loss": format(overall_loss/iteration, '.6f')})

def test( model, device, test_loader):
    # Do not forget to set eval() to keep model's params the same
    model.eval()
    test_loss = 0
    correct = 0
    mse_loss = nn.MSELoss()
    mse_loss_val = 0
    ind = 0
    with torch.no_grad():
        for data, target in test_loader:
            # print(f"target shape is {target.shape}")
            data, target = data.to(device), target.to(device)
            output = model(data)
            # print(f"output shape is {output.shape}")
            # Sum up batch loss
            test_loss += F.cross_entropy(output, target, reduction='sum').item()
            mse_loss_val += mse_loss(output, target).item()
            # mse_loss += sum()
            # pred = output.argmax(dim=1, keepdim=True)  # get the index of the max log-probability
            # print(output.shape)
            # targ = target.argmax(dim=1, keepdim=True)  # get the index of the max log-probability
            print(target, "\n", output)

            # correct += pred.eq(targ.view_as(pred)).sum().item()

    # test_loss /= len(test_loader.dataset)
    print(f"Test set: Average loss: {test_loss} mse loss: {mse_loss_val}")

In [ ]:
# Train the model
optimizer = optim.Adam(model1.parameters(), lr=lr)

for epoch in range(1, epochs + 1):
    train(model1, device, dataloaders['train'], optimizer, epoch)
    test(model1, device, dataloaders['test'])

# Optionally, you can save the params of model to file
#torch.save(model.state_dict(), "mnist_model.pt")


100%|██████████| 21/21 [00:00<00:00, 215.47it/s, Loss=0.003354]


tensor([[0.3648, 0.2528],
        [0.4378, 0.1389],
        [0.4795, 0.2806],
        [0.5525, 0.3056],
        [0.6254, 0.2194],
        [0.0000, 0.1778],
        [0.0521, 0.1806],
        [0.0938, 0.1500],
        [0.1459, 0.0694],
        [0.1876, 0.2500]]) 
 tensor([[0.3791, 0.1596],
        [0.4953, 0.1324],
        [0.5037, 0.1630],
        [0.6091, 0.1351],
        [0.6914, 0.0640],
        [0.0026, 0.2019],
        [0.0525, 0.1969],
        [0.1308, 0.0937],
        [0.1718, 0.1208],
        [0.2052, 0.1265]])
tensor([[0.2502, 0.1444],
        [0.3023, 0.0833],
        [0.3336, 0.1944],
        [0.4170, 0.1972],
        [0.4587, 0.1278],
        [0.5003, 0.1500],
        [0.5525, 0.0611],
        [0.5837, 0.1556],
        [0.0000, 0.2389],
        [0.0521, 0.2889]]) 
 tensor([[0.2828, 0.1673],
        [0.2977, 0.1113],
        [0.3755, 0.1140],
        [0.4272, 0.1177],
        [0.4661, 0.1406],
        [0.4721, 0.1208],
        [0.5234, 0.0963],
        [0.5896, 0.0921],
     

100%|██████████| 21/21 [00:00<00:00, 285.34it/s, Loss=0.001241]


tensor([[0.3648, 0.2528],
        [0.4378, 0.1389],
        [0.4795, 0.2806],
        [0.5525, 0.3056],
        [0.6254, 0.2194],
        [0.0000, 0.1778],
        [0.0521, 0.1806],
        [0.0938, 0.1500],
        [0.1459, 0.0694],
        [0.1876, 0.2500]]) 
 tensor([[0.3361, 0.1960],
        [0.4363, 0.1762],
        [0.4540, 0.2120],
        [0.5637, 0.2341],
        [0.6037, 0.1845],
        [0.0017, 0.1907],
        [0.0368, 0.2030],
        [0.0891, 0.1256],
        [0.1334, 0.1343],
        [0.1593, 0.1467]])
tensor([[0.2502, 0.1444],
        [0.3023, 0.0833],
        [0.3336, 0.1944],
        [0.4170, 0.1972],
        [0.4587, 0.1278],
        [0.5003, 0.1500],
        [0.5525, 0.0611],
        [0.5837, 0.1556],
        [0.0000, 0.2389],
        [0.0521, 0.2889]]) 
 tensor([[0.2153, 0.1829],
        [0.2285, 0.1551],
        [0.2934, 0.1691],
        [0.3350, 0.1353],
        [0.3905, 0.1863],
        [0.3899, 0.1741],
        [0.4520, 0.1617],
        [0.5145, 0.1842],
     

100%|██████████| 21/21 [00:00<00:00, 217.19it/s, Loss=0.000756]


tensor([[0.3648, 0.2528],
        [0.4378, 0.1389],
        [0.4795, 0.2806],
        [0.5525, 0.3056],
        [0.6254, 0.2194],
        [0.0000, 0.1778],
        [0.0521, 0.1806],
        [0.0938, 0.1500],
        [0.1459, 0.0694],
        [0.1876, 0.2500]]) 
 tensor([[3.5750e-01, 2.0453e-01],
        [4.5463e-01, 1.7773e-01],
        [4.7452e-01, 2.1592e-01],
        [5.9201e-01, 2.4378e-01],
        [6.5047e-01, 1.9480e-01],
        [1.6171e-05, 1.9387e-01],
        [4.1470e-02, 2.0426e-01],
        [9.4745e-02, 1.3103e-01],
        [1.4037e-01, 1.3194e-01],
        [1.8094e-01, 1.4476e-01]])
tensor([[0.2502, 0.1444],
        [0.3023, 0.0833],
        [0.3336, 0.1944],
        [0.4170, 0.1972],
        [0.4587, 0.1278],
        [0.5003, 0.1500],
        [0.5525, 0.0611],
        [0.5837, 0.1556],
        [0.0000, 0.2389],
        [0.0521, 0.2889]]) 
 tensor([[0.2213, 0.1736],
        [0.2643, 0.1070],
        [0.3276, 0.1579],
        [0.3891, 0.1230],
        [0.4368, 0.1730],
   

100%|██████████| 21/21 [00:00<00:00, 248.39it/s, Loss=0.000590]


tensor([[0.3648, 0.2528],
        [0.4378, 0.1389],
        [0.4795, 0.2806],
        [0.5525, 0.3056],
        [0.6254, 0.2194],
        [0.0000, 0.1778],
        [0.0521, 0.1806],
        [0.0938, 0.1500],
        [0.1459, 0.0694],
        [0.1876, 0.2500]]) 
 tensor([[ 0.3460,  0.2076],
        [ 0.4296,  0.1769],
        [ 0.4549,  0.2245],
        [ 0.5607,  0.2516],
        [ 0.6170,  0.1814],
        [-0.0038,  0.1935],
        [ 0.0363,  0.2118],
        [ 0.0901,  0.1410],
        [ 0.1426,  0.1212],
        [ 0.1820,  0.1441]])
tensor([[0.2502, 0.1444],
        [0.3023, 0.0833],
        [0.3336, 0.1944],
        [0.4170, 0.1972],
        [0.4587, 0.1278],
        [0.5003, 0.1500],
        [0.5525, 0.0611],
        [0.5837, 0.1556],
        [0.0000, 0.2389],
        [0.0521, 0.2889]]) 
 tensor([[ 0.2232,  0.1596],
        [ 0.2732,  0.0962],
        [ 0.3241,  0.1608],
        [ 0.3942,  0.1230],
        [ 0.4259,  0.1735],
        [ 0.4501,  0.1467],
        [ 0.4910,  0.1201

100%|██████████| 21/21 [00:00<00:00, 271.80it/s, Loss=0.000500]


tensor([[0.3648, 0.2528],
        [0.4378, 0.1389],
        [0.4795, 0.2806],
        [0.5525, 0.3056],
        [0.6254, 0.2194],
        [0.0000, 0.1778],
        [0.0521, 0.1806],
        [0.0938, 0.1500],
        [0.1459, 0.0694],
        [0.1876, 0.2500]]) 
 tensor([[ 0.3601,  0.2027],
        [ 0.4363,  0.1611],
        [ 0.4603,  0.2157],
        [ 0.5707,  0.2518],
        [ 0.6402,  0.1726],
        [-0.0019,  0.1919],
        [ 0.0408,  0.2084],
        [ 0.0975,  0.1316],
        [ 0.1431,  0.1231],
        [ 0.1849,  0.1490]])
tensor([[0.2502, 0.1444],
        [0.3023, 0.0833],
        [0.3336, 0.1944],
        [0.4170, 0.1972],
        [0.4587, 0.1278],
        [0.5003, 0.1500],
        [0.5525, 0.0611],
        [0.5837, 0.1556],
        [0.0000, 0.2389],
        [0.0521, 0.2889]]) 
 tensor([[0.2277, 0.1478],
        [0.2887, 0.0865],
        [0.3327, 0.1717],
        [0.4141, 0.1115],
        [0.4461, 0.1603],
        [0.4811, 0.1330],
        [0.5184, 0.0883],
        [0.

100%|██████████| 21/21 [00:00<00:00, 276.74it/s, Loss=0.000481]


tensor([[0.3648, 0.2528],
        [0.4378, 0.1389],
        [0.4795, 0.2806],
        [0.5525, 0.3056],
        [0.6254, 0.2194],
        [0.0000, 0.1778],
        [0.0521, 0.1806],
        [0.0938, 0.1500],
        [0.1459, 0.0694],
        [0.1876, 0.2500]]) 
 tensor([[ 0.3650,  0.2033],
        [ 0.4387,  0.1657],
        [ 0.4616,  0.2214],
        [ 0.5697,  0.2642],
        [ 0.6467,  0.1714],
        [-0.0026,  0.1908],
        [ 0.0392,  0.2088],
        [ 0.0914,  0.1387],
        [ 0.1453,  0.1134],
        [ 0.1814,  0.1504]])
tensor([[0.2502, 0.1444],
        [0.3023, 0.0833],
        [0.3336, 0.1944],
        [0.4170, 0.1972],
        [0.4587, 0.1278],
        [0.5003, 0.1500],
        [0.5525, 0.0611],
        [0.5837, 0.1556],
        [0.0000, 0.2389],
        [0.0521, 0.2889]]) 
 tensor([[0.2245, 0.1435],
        [0.2904, 0.0752],
        [0.3352, 0.1746],
        [0.4117, 0.1144],
        [0.4429, 0.1691],
        [0.4802, 0.1395],
        [0.5234, 0.0857],
        [0.

100%|██████████| 21/21 [00:00<00:00, 261.80it/s, Loss=0.000452]


tensor([[0.3648, 0.2528],
        [0.4378, 0.1389],
        [0.4795, 0.2806],
        [0.5525, 0.3056],
        [0.6254, 0.2194],
        [0.0000, 0.1778],
        [0.0521, 0.1806],
        [0.0938, 0.1500],
        [0.1459, 0.0694],
        [0.1876, 0.2500]]) 
 tensor([[ 0.3617,  0.2044],
        [ 0.4351,  0.1749],
        [ 0.4525,  0.2244],
        [ 0.5633,  0.2665],
        [ 0.6306,  0.1774],
        [-0.0045,  0.1907],
        [ 0.0399,  0.2099],
        [ 0.0918,  0.1415],
        [ 0.1417,  0.1165],
        [ 0.1827,  0.1559]])
tensor([[0.2502, 0.1444],
        [0.3023, 0.0833],
        [0.3336, 0.1944],
        [0.4170, 0.1972],
        [0.4587, 0.1278],
        [0.5003, 0.1500],
        [0.5525, 0.0611],
        [0.5837, 0.1556],
        [0.0000, 0.2389],
        [0.0521, 0.2889]]) 
 tensor([[ 2.2411e-01,  1.4128e-01],
        [ 2.9463e-01,  4.5508e-02],
        [ 3.3264e-01,  1.7757e-01],
        [ 4.0473e-01,  1.1596e-01],
        [ 4.3579e-01,  1.7743e-01],
        [ 4.7

100%|██████████| 21/21 [00:00<00:00, 270.77it/s, Loss=0.000401]


tensor([[0.3648, 0.2528],
        [0.4378, 0.1389],
        [0.4795, 0.2806],
        [0.5525, 0.3056],
        [0.6254, 0.2194],
        [0.0000, 0.1778],
        [0.0521, 0.1806],
        [0.0938, 0.1500],
        [0.1459, 0.0694],
        [0.1876, 0.2500]]) 
 tensor([[ 0.3534,  0.2099],
        [ 0.4212,  0.1680],
        [ 0.4433,  0.2276],
        [ 0.5523,  0.2673],
        [ 0.6121,  0.1790],
        [-0.0047,  0.1889],
        [ 0.0385,  0.2129],
        [ 0.0897,  0.1419],
        [ 0.1435,  0.1076],
        [ 0.1818,  0.1568]])
tensor([[0.2502, 0.1444],
        [0.3023, 0.0833],
        [0.3336, 0.1944],
        [0.4170, 0.1972],
        [0.4587, 0.1278],
        [0.5003, 0.1500],
        [0.5525, 0.0611],
        [0.5837, 0.1556],
        [0.0000, 0.2389],
        [0.0521, 0.2889]]) 
 tensor([[ 2.2555e-01,  1.2102e-01],
        [ 2.9759e-01,  3.3069e-02],
        [ 3.2793e-01,  1.7895e-01],
        [ 3.9959e-01,  1.2178e-01],
        [ 4.2741e-01,  1.8284e-01],
        [ 4.7

100%|██████████| 21/21 [00:00<00:00, 248.86it/s, Loss=0.000391]


tensor([[0.3648, 0.2528],
        [0.4378, 0.1389],
        [0.4795, 0.2806],
        [0.5525, 0.3056],
        [0.6254, 0.2194],
        [0.0000, 0.1778],
        [0.0521, 0.1806],
        [0.0938, 0.1500],
        [0.1459, 0.0694],
        [0.1876, 0.2500]]) 
 tensor([[ 0.3541,  0.2094],
        [ 0.4212,  0.1740],
        [ 0.4391,  0.2312],
        [ 0.5473,  0.2747],
        [ 0.6073,  0.1834],
        [-0.0047,  0.1889],
        [ 0.0386,  0.2100],
        [ 0.0876,  0.1437],
        [ 0.1415,  0.1082],
        [ 0.1836,  0.1538]])
tensor([[0.2502, 0.1444],
        [0.3023, 0.0833],
        [0.3336, 0.1944],
        [0.4170, 0.1972],
        [0.4587, 0.1278],
        [0.5003, 0.1500],
        [0.5525, 0.0611],
        [0.5837, 0.1556],
        [0.0000, 0.2389],
        [0.0521, 0.2889]]) 
 tensor([[ 2.3058e-01,  1.0571e-01],
        [ 2.9175e-01,  5.8456e-02],
        [ 3.2812e-01,  1.8072e-01],
        [ 3.9712e-01,  1.1596e-01],
        [ 4.2186e-01,  1.8459e-01],
        [ 4.6

100%|██████████| 21/21 [00:00<00:00, 300.46it/s, Loss=0.000364]


tensor([[0.3648, 0.2528],
        [0.4378, 0.1389],
        [0.4795, 0.2806],
        [0.5525, 0.3056],
        [0.6254, 0.2194],
        [0.0000, 0.1778],
        [0.0521, 0.1806],
        [0.0938, 0.1500],
        [0.1459, 0.0694],
        [0.1876, 0.2500]]) 
 tensor([[ 0.3469,  0.2144],
        [ 0.4090,  0.1641],
        [ 0.4306,  0.2384],
        [ 0.5367,  0.2756],
        [ 0.5967,  0.1846],
        [-0.0055,  0.1873],
        [ 0.0387,  0.2090],
        [ 0.0873,  0.1467],
        [ 0.1411,  0.1086],
        [ 0.1817,  0.1652]])
tensor([[0.2502, 0.1444],
        [0.3023, 0.0833],
        [0.3336, 0.1944],
        [0.4170, 0.1972],
        [0.4587, 0.1278],
        [0.5003, 0.1500],
        [0.5525, 0.0611],
        [0.5837, 0.1556],
        [0.0000, 0.2389],
        [0.0521, 0.2889]]) 
 tensor([[ 0.2304,  0.1032],
        [ 0.3024,  0.0261],
        [ 0.3272,  0.1817],
        [ 0.3997,  0.1343],
        [ 0.4223,  0.2019],
        [ 0.4697,  0.1595],
        [ 0.5221,  0.0821

100%|██████████| 21/21 [00:00<00:00, 258.80it/s, Loss=0.000382]


tensor([[0.3648, 0.2528],
        [0.4378, 0.1389],
        [0.4795, 0.2806],
        [0.5525, 0.3056],
        [0.6254, 0.2194],
        [0.0000, 0.1778],
        [0.0521, 0.1806],
        [0.0938, 0.1500],
        [0.1459, 0.0694],
        [0.1876, 0.2500]]) 
 tensor([[ 0.3476,  0.2113],
        [ 0.4107,  0.1819],
        [ 0.4260,  0.2372],
        [ 0.5334,  0.2843],
        [ 0.5883,  0.1884],
        [-0.0058,  0.1872],
        [ 0.0387,  0.2111],
        [ 0.0845,  0.1472],
        [ 0.1368,  0.1045],
        [ 0.1790,  0.1630]])
tensor([[0.2502, 0.1444],
        [0.3023, 0.0833],
        [0.3336, 0.1944],
        [0.4170, 0.1972],
        [0.4587, 0.1278],
        [0.5003, 0.1500],
        [0.5525, 0.0611],
        [0.5837, 0.1556],
        [0.0000, 0.2389],
        [0.0521, 0.2889]]) 
 tensor([[ 0.2180,  0.1446],
        [ 0.2866,  0.0571],
        [ 0.3209,  0.1838],
        [ 0.3919,  0.1256],
        [ 0.4091,  0.1887],
        [ 0.4594,  0.1586],
        [ 0.5117,  0.0740

100%|██████████| 21/21 [00:00<00:00, 267.65it/s, Loss=0.000374]


tensor([[0.3648, 0.2528],
        [0.4378, 0.1389],
        [0.4795, 0.2806],
        [0.5525, 0.3056],
        [0.6254, 0.2194],
        [0.0000, 0.1778],
        [0.0521, 0.1806],
        [0.0938, 0.1500],
        [0.1459, 0.0694],
        [0.1876, 0.2500]]) 
 tensor([[ 0.3362,  0.2136],
        [ 0.3974,  0.1693],
        [ 0.4172,  0.2409],
        [ 0.5198,  0.2892],
        [ 0.5737,  0.2009],
        [-0.0062,  0.1851],
        [ 0.0379,  0.2066],
        [ 0.0849,  0.1454],
        [ 0.1367,  0.1043],
        [ 0.1776,  0.1693]])
tensor([[0.2502, 0.1444],
        [0.3023, 0.0833],
        [0.3336, 0.1944],
        [0.4170, 0.1972],
        [0.4587, 0.1278],
        [0.5003, 0.1500],
        [0.5525, 0.0611],
        [0.5837, 0.1556],
        [0.0000, 0.2389],
        [0.0521, 0.2889]]) 
 tensor([[ 0.2199,  0.1123],
        [ 0.2773,  0.0849],
        [ 0.3172,  0.2051],
        [ 0.3932,  0.1375],
        [ 0.4144,  0.2084],
        [ 0.4659,  0.1750],
        [ 0.5178,  0.0895

100%|██████████| 21/21 [00:00<00:00, 282.95it/s, Loss=0.000397]


tensor([[0.3648, 0.2528],
        [0.4378, 0.1389],
        [0.4795, 0.2806],
        [0.5525, 0.3056],
        [0.6254, 0.2194],
        [0.0000, 0.1778],
        [0.0521, 0.1806],
        [0.0938, 0.1500],
        [0.1459, 0.0694],
        [0.1876, 0.2500]]) 
 tensor([[ 0.3321,  0.2194],
        [ 0.3971,  0.1941],
        [ 0.4124,  0.2504],
        [ 0.5192,  0.3004],
        [ 0.5686,  0.2012],
        [-0.0059,  0.1864],
        [ 0.0393,  0.2079],
        [ 0.0813,  0.1517],
        [ 0.1319,  0.1063],
        [ 0.1746,  0.1746]])
tensor([[0.2502, 0.1444],
        [0.3023, 0.0833],
        [0.3336, 0.1944],
        [0.4170, 0.1972],
        [0.4587, 0.1278],
        [0.5003, 0.1500],
        [0.5525, 0.0611],
        [0.5837, 0.1556],
        [0.0000, 0.2389],
        [0.0521, 0.2889]]) 
 tensor([[ 2.1399e-01,  1.3087e-01],
        [ 2.7441e-01,  7.9260e-02],
        [ 3.1272e-01,  2.0935e-01],
        [ 3.8830e-01,  1.4858e-01],
        [ 4.0673e-01,  2.1029e-01],
        [ 4.5

100%|██████████| 21/21 [00:00<00:00, 245.90it/s, Loss=0.000434]


tensor([[0.3648, 0.2528],
        [0.4378, 0.1389],
        [0.4795, 0.2806],
        [0.5525, 0.3056],
        [0.6254, 0.2194],
        [0.0000, 0.1778],
        [0.0521, 0.1806],
        [0.0938, 0.1500],
        [0.1459, 0.0694],
        [0.1876, 0.2500]]) 
 tensor([[ 0.3169,  0.2162],
        [ 0.3784,  0.1748],
        [ 0.3981,  0.2478],
        [ 0.4926,  0.2872],
        [ 0.5360,  0.1895],
        [-0.0077,  0.1840],
        [ 0.0374,  0.2060],
        [ 0.0772,  0.1484],
        [ 0.1275,  0.1026],
        [ 0.1702,  0.1731]])
tensor([[0.2502, 0.1444],
        [0.3023, 0.0833],
        [0.3336, 0.1944],
        [0.4170, 0.1972],
        [0.4587, 0.1278],
        [0.5003, 0.1500],
        [0.5525, 0.0611],
        [0.5837, 0.1556],
        [0.0000, 0.2389],
        [0.0521, 0.2889]]) 
 tensor([[ 0.2054,  0.1316],
        [ 0.2662,  0.0944],
        [ 0.3049,  0.2119],
        [ 0.3765,  0.1401],
        [ 0.4004,  0.2145],
        [ 0.4494,  0.1795],
        [ 0.4986,  0.0922

100%|██████████| 21/21 [00:00<00:00, 270.63it/s, Loss=0.000533]


tensor([[0.3648, 0.2528],
        [0.4378, 0.1389],
        [0.4795, 0.2806],
        [0.5525, 0.3056],
        [0.6254, 0.2194],
        [0.0000, 0.1778],
        [0.0521, 0.1806],
        [0.0938, 0.1500],
        [0.1459, 0.0694],
        [0.1876, 0.2500]]) 
 tensor([[ 0.3008,  0.2041],
        [ 0.3596,  0.1576],
        [ 0.3736,  0.2247],
        [ 0.4528,  0.2374],
        [ 0.4935,  0.1399],
        [-0.0106,  0.1808],
        [ 0.0343,  0.1988],
        [ 0.0701,  0.1409],
        [ 0.1181,  0.0954],
        [ 0.1564,  0.1616]])
tensor([[0.2502, 0.1444],
        [0.3023, 0.0833],
        [0.3336, 0.1944],
        [0.4170, 0.1972],
        [0.4587, 0.1278],
        [0.5003, 0.1500],
        [0.5525, 0.0611],
        [0.5837, 0.1556],
        [0.0000, 0.2389],
        [0.0521, 0.2889]]) 
 tensor([[ 0.1837,  0.1384],
        [ 0.2405,  0.0961],
        [ 0.2817,  0.1945],
        [ 0.3512,  0.1126],
        [ 0.3664,  0.1656],
        [ 0.4077,  0.1228],
        [ 0.4534,  0.0398

100%|██████████| 21/21 [00:00<00:00, 252.63it/s, Loss=0.000560]


tensor([[0.3648, 0.2528],
        [0.4378, 0.1389],
        [0.4795, 0.2806],
        [0.5525, 0.3056],
        [0.6254, 0.2194],
        [0.0000, 0.1778],
        [0.0521, 0.1806],
        [0.0938, 0.1500],
        [0.1459, 0.0694],
        [0.1876, 0.2500]]) 
 tensor([[ 0.2874,  0.1995],
        [ 0.3468,  0.1575],
        [ 0.3578,  0.2169],
        [ 0.4369,  0.2355],
        [ 0.4784,  0.1401],
        [-0.0128,  0.1810],
        [ 0.0348,  0.1883],
        [ 0.0689,  0.1279],
        [ 0.1124,  0.0953],
        [ 0.1509,  0.1601]])
tensor([[0.2502, 0.1444],
        [0.3023, 0.0833],
        [0.3336, 0.1944],
        [0.4170, 0.1972],
        [0.4587, 0.1278],
        [0.5003, 0.1500],
        [0.5525, 0.0611],
        [0.5837, 0.1556],
        [0.0000, 0.2389],
        [0.0521, 0.2889]]) 
 tensor([[ 0.1745,  0.1409],
        [ 0.2272,  0.0957],
        [ 0.2678,  0.1849],
        [ 0.3362,  0.1167],
        [ 0.3503,  0.1490],
        [ 0.3921,  0.1204],
        [ 0.4400,  0.0466

100%|██████████| 21/21 [00:00<00:00, 245.96it/s, Loss=0.000766]


tensor([[0.3648, 0.2528],
        [0.4378, 0.1389],
        [0.4795, 0.2806],
        [0.5525, 0.3056],
        [0.6254, 0.2194],
        [0.0000, 0.1778],
        [0.0521, 0.1806],
        [0.0938, 0.1500],
        [0.1459, 0.0694],
        [0.1876, 0.2500]]) 
 tensor([[ 0.3008,  0.2166],
        [ 0.3604,  0.1436],
        [ 0.3732,  0.2165],
        [ 0.4500,  0.2260],
        [ 0.4941,  0.1483],
        [-0.0127,  0.1815],
        [ 0.0421,  0.1874],
        [ 0.0786,  0.1323],
        [ 0.1213,  0.0989],
        [ 0.1601,  0.1614]])
tensor([[0.2502, 0.1444],
        [0.3023, 0.0833],
        [0.3336, 0.1944],
        [0.4170, 0.1972],
        [0.4587, 0.1278],
        [0.5003, 0.1500],
        [0.5525, 0.0611],
        [0.5837, 0.1556],
        [0.0000, 0.2389],
        [0.0521, 0.2889]]) 
 tensor([[ 0.1778,  0.1261],
        [ 0.2462,  0.0847],
        [ 0.2838,  0.1937],
        [ 0.3526,  0.1233],
        [ 0.3795,  0.1654],
        [ 0.4186,  0.1278],
        [ 0.4586,  0.0528

100%|██████████| 21/21 [00:00<00:00, 270.36it/s, Loss=0.001026]


tensor([[0.3648, 0.2528],
        [0.4378, 0.1389],
        [0.4795, 0.2806],
        [0.5525, 0.3056],
        [0.6254, 0.2194],
        [0.0000, 0.1778],
        [0.0521, 0.1806],
        [0.0938, 0.1500],
        [0.1459, 0.0694],
        [0.1876, 0.2500]]) 
 tensor([[ 0.3455,  0.1589],
        [ 0.4250,  0.0807],
        [ 0.4369,  0.1259],
        [ 0.5120,  0.1190],
        [ 0.5716,  0.0341],
        [-0.0094,  0.1714],
        [ 0.0590,  0.1703],
        [ 0.0972,  0.1040],
        [ 0.1346,  0.0795],
        [ 0.1817,  0.1425]])
tensor([[0.2502, 0.1444],
        [0.3023, 0.0833],
        [0.3336, 0.1944],
        [0.4170, 0.1972],
        [0.4587, 0.1278],
        [0.5003, 0.1500],
        [0.5525, 0.0611],
        [0.5837, 0.1556],
        [0.0000, 0.2389],
        [0.0521, 0.2889]]) 
 tensor([[ 0.2098,  0.1125],
        [ 0.2903,  0.0361],
        [ 0.3259,  0.1559],
        [ 0.4058,  0.0709],
        [ 0.4404,  0.0794],
        [ 0.4799,  0.0442],
        [ 0.5296, -0.0081

100%|██████████| 21/21 [00:00<00:00, 271.51it/s, Loss=0.001476]


tensor([[0.3648, 0.2528],
        [0.4378, 0.1389],
        [0.4795, 0.2806],
        [0.5525, 0.3056],
        [0.6254, 0.2194],
        [0.0000, 0.1778],
        [0.0521, 0.1806],
        [0.0938, 0.1500],
        [0.1459, 0.0694],
        [0.1876, 0.2500]]) 
 tensor([[ 0.3696,  0.1995],
        [ 0.4557,  0.1462],
        [ 0.4659,  0.1827],
        [ 0.5356,  0.1802],
        [ 0.6157,  0.1241],
        [-0.0066,  0.1798],
        [ 0.0618,  0.2050],
        [ 0.1023,  0.1390],
        [ 0.1432,  0.0987],
        [ 0.1895,  0.1446]])
tensor([[0.2502, 0.1444],
        [0.3023, 0.0833],
        [0.3336, 0.1944],
        [0.4170, 0.1972],
        [0.4587, 0.1278],
        [0.5003, 0.1500],
        [0.5525, 0.0611],
        [0.5837, 0.1556],
        [0.0000, 0.2389],
        [0.0521, 0.2889]]) 
 tensor([[ 0.2319,  0.1380],
        [ 0.2970,  0.1659],
        [ 0.3509,  0.1838],
        [ 0.4213,  0.1346],
        [ 0.4626,  0.1474],
        [ 0.4993,  0.1174],
        [ 0.5474,  0.0839

100%|██████████| 21/21 [00:00<00:00, 273.24it/s, Loss=0.001367]


tensor([[0.3648, 0.2528],
        [0.4378, 0.1389],
        [0.4795, 0.2806],
        [0.5525, 0.3056],
        [0.6254, 0.2194],
        [0.0000, 0.1778],
        [0.0521, 0.1806],
        [0.0938, 0.1500],
        [0.1459, 0.0694],
        [0.1876, 0.2500]]) 
 tensor([[ 4.2057e-01,  2.1241e-01],
        [ 5.3432e-01,  1.9259e-01],
        [ 5.4869e-01,  2.2233e-01],
        [ 6.4399e-01,  2.3308e-01],
        [ 7.5144e-01,  2.0693e-01],
        [-1.0255e-04,  1.8701e-01],
        [ 6.3617e-02,  2.1141e-01],
        [ 1.1960e-01,  1.4120e-01],
        [ 1.5539e-01,  1.1923e-01],
        [ 2.0892e-01,  1.5668e-01]])
tensor([[0.2502, 0.1444],
        [0.3023, 0.0833],
        [0.3336, 0.1944],
        [0.4170, 0.1972],
        [0.4587, 0.1278],
        [0.5003, 0.1500],
        [0.5525, 0.0611],
        [0.5837, 0.1556],
        [0.0000, 0.2389],
        [0.0521, 0.2889]]) 
 tensor([[ 0.2608,  0.1519],
        [ 0.3493,  0.0441],
        [ 0.3882,  0.2015],
        [ 0.4772,  0.1748],
 

100%|██████████| 21/21 [00:00<00:00, 308.61it/s, Loss=0.000900]


tensor([[0.3648, 0.2528],
        [0.4378, 0.1389],
        [0.4795, 0.2806],
        [0.5525, 0.3056],
        [0.6254, 0.2194],
        [0.0000, 0.1778],
        [0.0521, 0.1806],
        [0.0938, 0.1500],
        [0.1459, 0.0694],
        [0.1876, 0.2500]]) 
 tensor([[ 0.4022,  0.2292],
        [ 0.5030,  0.1956],
        [ 0.5237,  0.2375],
        [ 0.6156,  0.2525],
        [ 0.6983,  0.2112],
        [-0.0025,  0.1828],
        [ 0.0629,  0.2100],
        [ 0.1063,  0.1270],
        [ 0.1567,  0.1119],
        [ 0.1983,  0.1587]])
tensor([[0.2502, 0.1444],
        [0.3023, 0.0833],
        [0.3336, 0.1944],
        [0.4170, 0.1972],
        [0.4587, 0.1278],
        [0.5003, 0.1500],
        [0.5525, 0.0611],
        [0.5837, 0.1556],
        [0.0000, 0.2389],
        [0.0521, 0.2889]]) 
 tensor([[ 0.2649,  0.1229],
        [ 0.3423,  0.0416],
        [ 0.3631,  0.2021],
        [ 0.4375,  0.1568],
        [ 0.4849,  0.1906],
        [ 0.5230,  0.1597],
        [ 0.5792,  0.1418

100%|██████████| 21/21 [00:00<00:00, 246.44it/s, Loss=0.000572]


tensor([[0.3648, 0.2528],
        [0.4378, 0.1389],
        [0.4795, 0.2806],
        [0.5525, 0.3056],
        [0.6254, 0.2194],
        [0.0000, 0.1778],
        [0.0521, 0.1806],
        [0.0938, 0.1500],
        [0.1459, 0.0694],
        [0.1876, 0.2500]]) 
 tensor([[ 0.3626,  0.2227],
        [ 0.4519,  0.1832],
        [ 0.4763,  0.2472],
        [ 0.5638,  0.2505],
        [ 0.6312,  0.1846],
        [-0.0074,  0.1844],
        [ 0.0558,  0.2021],
        [ 0.0862,  0.1251],
        [ 0.1361,  0.1083],
        [ 0.1740,  0.1610]])
tensor([[0.2502, 0.1444],
        [0.3023, 0.0833],
        [0.3336, 0.1944],
        [0.4170, 0.1972],
        [0.4587, 0.1278],
        [0.5003, 0.1500],
        [0.5525, 0.0611],
        [0.5837, 0.1556],
        [0.0000, 0.2389],
        [0.0521, 0.2889]]) 
 tensor([[ 0.2293,  0.1372],
        [ 0.2937,  0.0742],
        [ 0.3175,  0.1958],
        [ 0.3909,  0.1178],
        [ 0.4334,  0.1579],
        [ 0.4674,  0.1167],
        [ 0.5269,  0.0834

100%|██████████| 21/21 [00:00<00:00, 219.23it/s, Loss=0.000378]


tensor([[0.3648, 0.2528],
        [0.4378, 0.1389],
        [0.4795, 0.2806],
        [0.5525, 0.3056],
        [0.6254, 0.2194],
        [0.0000, 0.1778],
        [0.0521, 0.1806],
        [0.0938, 0.1500],
        [0.1459, 0.0694],
        [0.1876, 0.2500]]) 
 tensor([[ 0.3765,  0.2161],
        [ 0.4676,  0.1835],
        [ 0.4920,  0.2577],
        [ 0.5870,  0.2609],
        [ 0.6502,  0.1657],
        [-0.0052,  0.1808],
        [ 0.0558,  0.1993],
        [ 0.0943,  0.1287],
        [ 0.1445,  0.1051],
        [ 0.1796,  0.1622]])
tensor([[0.2502, 0.1444],
        [0.3023, 0.0833],
        [0.3336, 0.1944],
        [0.4170, 0.1972],
        [0.4587, 0.1278],
        [0.5003, 0.1500],
        [0.5525, 0.0611],
        [0.5837, 0.1556],
        [0.0000, 0.2389],
        [0.0521, 0.2889]]) 
 tensor([[ 0.2448,  0.1144],
        [ 0.3102,  0.0548],
        [ 0.3313,  0.1900],
        [ 0.4156,  0.1011],
        [ 0.4576,  0.1492],
        [ 0.4957,  0.1072],
        [ 0.5639,  0.0636

100%|██████████| 21/21 [00:00<00:00, 239.58it/s, Loss=0.000401]


tensor([[0.3648, 0.2528],
        [0.4378, 0.1389],
        [0.4795, 0.2806],
        [0.5525, 0.3056],
        [0.6254, 0.2194],
        [0.0000, 0.1778],
        [0.0521, 0.1806],
        [0.0938, 0.1500],
        [0.1459, 0.0694],
        [0.1876, 0.2500]]) 
 tensor([[ 0.3781,  0.2306],
        [ 0.4649,  0.2028],
        [ 0.4884,  0.2788],
        [ 0.5842,  0.2894],
        [ 0.6484,  0.2022],
        [-0.0044,  0.1831],
        [ 0.0538,  0.2030],
        [ 0.0932,  0.1470],
        [ 0.1481,  0.1186],
        [ 0.1804,  0.1758]])
tensor([[0.2502, 0.1444],
        [0.3023, 0.0833],
        [0.3336, 0.1944],
        [0.4170, 0.1972],
        [0.4587, 0.1278],
        [0.5003, 0.1500],
        [0.5525, 0.0611],
        [0.5837, 0.1556],
        [0.0000, 0.2389],
        [0.0521, 0.2889]]) 
 tensor([[ 0.2501,  0.1369],
        [ 0.3123,  0.0894],
        [ 0.3373,  0.2146],
        [ 0.4174,  0.1347],
        [ 0.4572,  0.1893],
        [ 0.4942,  0.1497],
        [ 0.5647,  0.1030

100%|██████████| 21/21 [00:00<00:00, 234.47it/s, Loss=0.000339]


tensor([[0.3648, 0.2528],
        [0.4378, 0.1389],
        [0.4795, 0.2806],
        [0.5525, 0.3056],
        [0.6254, 0.2194],
        [0.0000, 0.1778],
        [0.0521, 0.1806],
        [0.0938, 0.1500],
        [0.1459, 0.0694],
        [0.1876, 0.2500]]) 
 tensor([[ 0.3747,  0.2384],
        [ 0.4558,  0.2161],
        [ 0.4781,  0.2962],
        [ 0.5726,  0.3004],
        [ 0.6369,  0.2234],
        [-0.0051,  0.1816],
        [ 0.0516,  0.2065],
        [ 0.0914,  0.1458],
        [ 0.1492,  0.1161],
        [ 0.1798,  0.1651]])
tensor([[0.2502, 0.1444],
        [0.3023, 0.0833],
        [0.3336, 0.1944],
        [0.4170, 0.1972],
        [0.4587, 0.1278],
        [0.5003, 0.1500],
        [0.5525, 0.0611],
        [0.5837, 0.1556],
        [0.0000, 0.2389],
        [0.0521, 0.2889]]) 
 tensor([[ 0.2532,  0.1129],
        [ 0.3095,  0.0712],
        [ 0.3335,  0.2211],
        [ 0.4119,  0.1384],
        [ 0.4482,  0.1984],
        [ 0.4842,  0.1576],
        [ 0.5529,  0.1030

100%|██████████| 21/21 [00:00<00:00, 244.94it/s, Loss=0.000303]


tensor([[0.3648, 0.2528],
        [0.4378, 0.1389],
        [0.4795, 0.2806],
        [0.5525, 0.3056],
        [0.6254, 0.2194],
        [0.0000, 0.1778],
        [0.0521, 0.1806],
        [0.0938, 0.1500],
        [0.1459, 0.0694],
        [0.1876, 0.2500]]) 
 tensor([[ 0.3742,  0.2343],
        [ 0.4529,  0.1978],
        [ 0.4756,  0.2815],
        [ 0.5691,  0.2933],
        [ 0.6350,  0.2195],
        [-0.0047,  0.1795],
        [ 0.0530,  0.2026],
        [ 0.0907,  0.1443],
        [ 0.1507,  0.1103],
        [ 0.1778,  0.1692]])
tensor([[0.2502, 0.1444],
        [0.3023, 0.0833],
        [0.3336, 0.1944],
        [0.4170, 0.1972],
        [0.4587, 0.1278],
        [0.5003, 0.1500],
        [0.5525, 0.0611],
        [0.5837, 0.1556],
        [0.0000, 0.2389],
        [0.0521, 0.2889]]) 
 tensor([[ 0.2492,  0.1254],
        [ 0.3014,  0.0921],
        [ 0.3325,  0.2159],
        [ 0.4133,  0.1286],
        [ 0.4478,  0.1884],
        [ 0.4840,  0.1463],
        [ 0.5530,  0.0890

100%|██████████| 21/21 [00:00<00:00, 242.28it/s, Loss=0.000273]


tensor([[0.3648, 0.2528],
        [0.4378, 0.1389],
        [0.4795, 0.2806],
        [0.5525, 0.3056],
        [0.6254, 0.2194],
        [0.0000, 0.1778],
        [0.0521, 0.1806],
        [0.0938, 0.1500],
        [0.1459, 0.0694],
        [0.1876, 0.2500]]) 
 tensor([[ 0.3721,  0.2291],
        [ 0.4538,  0.2013],
        [ 0.4771,  0.2912],
        [ 0.5686,  0.2883],
        [ 0.6363,  0.2048],
        [-0.0040,  0.1782],
        [ 0.0547,  0.1981],
        [ 0.0922,  0.1396],
        [ 0.1485,  0.1084],
        [ 0.1773,  0.1689]])
tensor([[0.2502, 0.1444],
        [0.3023, 0.0833],
        [0.3336, 0.1944],
        [0.4170, 0.1972],
        [0.4587, 0.1278],
        [0.5003, 0.1500],
        [0.5525, 0.0611],
        [0.5837, 0.1556],
        [0.0000, 0.2389],
        [0.0521, 0.2889]]) 
 tensor([[ 0.2508,  0.1037],
        [ 0.3043,  0.0690],
        [ 0.3302,  0.2153],
        [ 0.4147,  0.1230],
        [ 0.4496,  0.1815],
        [ 0.4862,  0.1381],
        [ 0.5559,  0.0722

100%|██████████| 21/21 [00:00<00:00, 239.94it/s, Loss=0.000269]


tensor([[0.3648, 0.2528],
        [0.4378, 0.1389],
        [0.4795, 0.2806],
        [0.5525, 0.3056],
        [0.6254, 0.2194],
        [0.0000, 0.1778],
        [0.0521, 0.1806],
        [0.0938, 0.1500],
        [0.1459, 0.0694],
        [0.1876, 0.2500]]) 
 tensor([[ 0.3724,  0.2295],
        [ 0.4537,  0.1985],
        [ 0.4770,  0.2888],
        [ 0.5671,  0.2861],
        [ 0.6347,  0.2065],
        [-0.0039,  0.1773],
        [ 0.0539,  0.1962],
        [ 0.0907,  0.1413],
        [ 0.1473,  0.1073],
        [ 0.1785,  0.1721]])
tensor([[0.2502, 0.1444],
        [0.3023, 0.0833],
        [0.3336, 0.1944],
        [0.4170, 0.1972],
        [0.4587, 0.1278],
        [0.5003, 0.1500],
        [0.5525, 0.0611],
        [0.5837, 0.1556],
        [0.0000, 0.2389],
        [0.0521, 0.2889]]) 
 tensor([[ 0.2517,  0.1067],
        [ 0.3048,  0.0786],
        [ 0.3308,  0.2187],
        [ 0.4149,  0.1255],
        [ 0.4499,  0.1791],
        [ 0.4862,  0.1364],
        [ 0.5555,  0.0689

100%|██████████| 21/21 [00:00<00:00, 242.42it/s, Loss=0.000258]


tensor([[0.3648, 0.2528],
        [0.4378, 0.1389],
        [0.4795, 0.2806],
        [0.5525, 0.3056],
        [0.6254, 0.2194],
        [0.0000, 0.1778],
        [0.0521, 0.1806],
        [0.0938, 0.1500],
        [0.1459, 0.0694],
        [0.1876, 0.2500]]) 
 tensor([[ 0.3716,  0.2300],
        [ 0.4520,  0.1966],
        [ 0.4765,  0.2853],
        [ 0.5663,  0.2842],
        [ 0.6332,  0.2077],
        [-0.0034,  0.1771],
        [ 0.0550,  0.1931],
        [ 0.0908,  0.1425],
        [ 0.1464,  0.1070],
        [ 0.1784,  0.1735]])
tensor([[0.2502, 0.1444],
        [0.3023, 0.0833],
        [0.3336, 0.1944],
        [0.4170, 0.1972],
        [0.4587, 0.1278],
        [0.5003, 0.1500],
        [0.5525, 0.0611],
        [0.5837, 0.1556],
        [0.0000, 0.2389],
        [0.0521, 0.2889]]) 
 tensor([[ 0.2505,  0.1061],
        [ 0.3028,  0.0794],
        [ 0.3301,  0.2216],
        [ 0.4139,  0.1273],
        [ 0.4492,  0.1785],
        [ 0.4853,  0.1372],
        [ 0.5541,  0.0674

100%|██████████| 21/21 [00:00<00:00, 259.93it/s, Loss=0.000252]


tensor([[0.3648, 0.2528],
        [0.4378, 0.1389],
        [0.4795, 0.2806],
        [0.5525, 0.3056],
        [0.6254, 0.2194],
        [0.0000, 0.1778],
        [0.0521, 0.1806],
        [0.0938, 0.1500],
        [0.1459, 0.0694],
        [0.1876, 0.2500]]) 
 tensor([[ 0.3725,  0.2284],
        [ 0.4509,  0.1843],
        [ 0.4765,  0.2729],
        [ 0.5668,  0.2827],
        [ 0.6340,  0.2042],
        [-0.0033,  0.1763],
        [ 0.0542,  0.1960],
        [ 0.0928,  0.1393],
        [ 0.1444,  0.1035],
        [ 0.1790,  0.1755]])
tensor([[0.2502, 0.1444],
        [0.3023, 0.0833],
        [0.3336, 0.1944],
        [0.4170, 0.1972],
        [0.4587, 0.1278],
        [0.5003, 0.1500],
        [0.5525, 0.0611],
        [0.5837, 0.1556],
        [0.0000, 0.2389],
        [0.0521, 0.2889]]) 
 tensor([[ 0.2468,  0.1298],
        [ 0.3013,  0.1002],
        [ 0.3308,  0.2234],
        [ 0.4148,  0.1284],
        [ 0.4508,  0.1774],
        [ 0.4863,  0.1380],
        [ 0.5552,  0.0629

100%|██████████| 21/21 [00:00<00:00, 250.82it/s, Loss=0.000245]


tensor([[0.3648, 0.2528],
        [0.4378, 0.1389],
        [0.4795, 0.2806],
        [0.5525, 0.3056],
        [0.6254, 0.2194],
        [0.0000, 0.1778],
        [0.0521, 0.1806],
        [0.0938, 0.1500],
        [0.1459, 0.0694],
        [0.1876, 0.2500]]) 
 tensor([[ 0.3716,  0.2261],
        [ 0.4505,  0.1882],
        [ 0.4759,  0.2789],
        [ 0.5656,  0.2758],
        [ 0.6346,  0.1990],
        [-0.0031,  0.1762],
        [ 0.0562,  0.1914],
        [ 0.0921,  0.1399],
        [ 0.1476,  0.1055],
        [ 0.1781,  0.1778]])
tensor([[0.2502, 0.1444],
        [0.3023, 0.0833],
        [0.3336, 0.1944],
        [0.4170, 0.1972],
        [0.4587, 0.1278],
        [0.5003, 0.1500],
        [0.5525, 0.0611],
        [0.5837, 0.1556],
        [0.0000, 0.2389],
        [0.0521, 0.2889]]) 
 tensor([[ 0.2487,  0.1073],
        [ 0.3036,  0.0702],
        [ 0.3296,  0.2237],
        [ 0.4137,  0.1274],
        [ 0.4498,  0.1748],
        [ 0.4861,  0.1349],
        [ 0.5554,  0.0561

100%|██████████| 21/21 [00:00<00:00, 235.86it/s, Loss=0.000246]


tensor([[0.3648, 0.2528],
        [0.4378, 0.1389],
        [0.4795, 0.2806],
        [0.5525, 0.3056],
        [0.6254, 0.2194],
        [0.0000, 0.1778],
        [0.0521, 0.1806],
        [0.0938, 0.1500],
        [0.1459, 0.0694],
        [0.1876, 0.2500]]) 
 tensor([[ 0.3709,  0.2271],
        [ 0.4491,  0.1932],
        [ 0.4761,  0.2781],
        [ 0.5652,  0.2754],
        [ 0.6308,  0.2027],
        [-0.0029,  0.1752],
        [ 0.0545,  0.1909],
        [ 0.0930,  0.1391],
        [ 0.1447,  0.1043],
        [ 0.1786,  0.1806]])
tensor([[0.2502, 0.1444],
        [0.3023, 0.0833],
        [0.3336, 0.1944],
        [0.4170, 0.1972],
        [0.4587, 0.1278],
        [0.5003, 0.1500],
        [0.5525, 0.0611],
        [0.5837, 0.1556],
        [0.0000, 0.2389],
        [0.0521, 0.2889]]) 
 tensor([[ 0.2495,  0.1087],
        [ 0.3041,  0.0814],
        [ 0.3297,  0.2288],
        [ 0.4126,  0.1333],
        [ 0.4503,  0.1765],
        [ 0.4844,  0.1416],
        [ 0.5523,  0.0577

100%|██████████| 21/21 [00:00<00:00, 242.24it/s, Loss=0.000246]


tensor([[0.3648, 0.2528],
        [0.4378, 0.1389],
        [0.4795, 0.2806],
        [0.5525, 0.3056],
        [0.6254, 0.2194],
        [0.0000, 0.1778],
        [0.0521, 0.1806],
        [0.0938, 0.1500],
        [0.1459, 0.0694],
        [0.1876, 0.2500]]) 
 tensor([[ 0.3696,  0.2307],
        [ 0.4463,  0.1821],
        [ 0.4716,  0.2674],
        [ 0.5618,  0.2860],
        [ 0.6308,  0.2080],
        [-0.0030,  0.1753],
        [ 0.0556,  0.1907],
        [ 0.0927,  0.1408],
        [ 0.1465,  0.1078],
        [ 0.1791,  0.1851]])
tensor([[0.2502, 0.1444],
        [0.3023, 0.0833],
        [0.3336, 0.1944],
        [0.4170, 0.1972],
        [0.4587, 0.1278],
        [0.5003, 0.1500],
        [0.5525, 0.0611],
        [0.5837, 0.1556],
        [0.0000, 0.2389],
        [0.0521, 0.2889]]) 
 tensor([[ 0.2490,  0.1171],
        [ 0.3020,  0.0947],
        [ 0.3299,  0.2370],
        [ 0.4126,  0.1414],
        [ 0.4488,  0.1862],
        [ 0.4847,  0.1501],
        [ 0.5523,  0.0592

100%|██████████| 21/21 [00:00<00:00, 248.03it/s, Loss=0.000245]


tensor([[0.3648, 0.2528],
        [0.4378, 0.1389],
        [0.4795, 0.2806],
        [0.5525, 0.3056],
        [0.6254, 0.2194],
        [0.0000, 0.1778],
        [0.0521, 0.1806],
        [0.0938, 0.1500],
        [0.1459, 0.0694],
        [0.1876, 0.2500]]) 
 tensor([[ 0.3696,  0.2329],
        [ 0.4427,  0.1768],
        [ 0.4704,  0.2646],
        [ 0.5615,  0.2821],
        [ 0.6287,  0.2107],
        [-0.0033,  0.1753],
        [ 0.0571,  0.1898],
        [ 0.0924,  0.1429],
        [ 0.1469,  0.1109],
        [ 0.1783,  0.1881]])
tensor([[0.2502, 0.1444],
        [0.3023, 0.0833],
        [0.3336, 0.1944],
        [0.4170, 0.1972],
        [0.4587, 0.1278],
        [0.5003, 0.1500],
        [0.5525, 0.0611],
        [0.5837, 0.1556],
        [0.0000, 0.2389],
        [0.0521, 0.2889]]) 
 tensor([[ 0.2460,  0.1230],
        [ 0.2982,  0.1001],
        [ 0.3283,  0.2402],
        [ 0.4108,  0.1455],
        [ 0.4488,  0.1874],
        [ 0.4830,  0.1538],
        [ 0.5497,  0.0643

100%|██████████| 21/21 [00:00<00:00, 238.71it/s, Loss=0.000239]


tensor([[0.3648, 0.2528],
        [0.4378, 0.1389],
        [0.4795, 0.2806],
        [0.5525, 0.3056],
        [0.6254, 0.2194],
        [0.0000, 0.1778],
        [0.0521, 0.1806],
        [0.0938, 0.1500],
        [0.1459, 0.0694],
        [0.1876, 0.2500]]) 
 tensor([[ 0.3681,  0.2318],
        [ 0.4388,  0.1840],
        [ 0.4667,  0.2778],
        [ 0.5566,  0.3047],
        [ 0.6210,  0.2281],
        [-0.0035,  0.1749],
        [ 0.0558,  0.1933],
        [ 0.0911,  0.1466],
        [ 0.1475,  0.1105],
        [ 0.1788,  0.1894]])
tensor([[0.2502, 0.1444],
        [0.3023, 0.0833],
        [0.3336, 0.1944],
        [0.4170, 0.1972],
        [0.4587, 0.1278],
        [0.5003, 0.1500],
        [0.5525, 0.0611],
        [0.5837, 0.1556],
        [0.0000, 0.2389],
        [0.0521, 0.2889]]) 
 tensor([[ 0.2475,  0.1192],
        [ 0.2996,  0.0980],
        [ 0.3284,  0.2441],
        [ 0.4092,  0.1575],
        [ 0.4463,  0.2017],
        [ 0.4806,  0.1690],
        [ 0.5456,  0.0728

100%|██████████| 21/21 [00:00<00:00, 289.39it/s, Loss=0.000251]


tensor([[0.3648, 0.2528],
        [0.4378, 0.1389],
        [0.4795, 0.2806],
        [0.5525, 0.3056],
        [0.6254, 0.2194],
        [0.0000, 0.1778],
        [0.0521, 0.1806],
        [0.0938, 0.1500],
        [0.1459, 0.0694],
        [0.1876, 0.2500]]) 
 tensor([[ 0.3682,  0.2381],
        [ 0.4348,  0.1974],
        [ 0.4621,  0.2946],
        [ 0.5518,  0.3183],
        [ 0.6182,  0.2477],
        [-0.0054,  0.1745],
        [ 0.0559,  0.1961],
        [ 0.0898,  0.1506],
        [ 0.1490,  0.1141],
        [ 0.1795,  0.1914]])
tensor([[0.2502, 0.1444],
        [0.3023, 0.0833],
        [0.3336, 0.1944],
        [0.4170, 0.1972],
        [0.4587, 0.1278],
        [0.5003, 0.1500],
        [0.5525, 0.0611],
        [0.5837, 0.1556],
        [0.0000, 0.2389],
        [0.0521, 0.2889]]) 
 tensor([[ 0.2469,  0.1308],
        [ 0.2963,  0.1159],
        [ 0.3297,  0.2439],
        [ 0.4071,  0.1641],
        [ 0.4428,  0.2087],
        [ 0.4782,  0.1757],
        [ 0.5424,  0.0888

100%|██████████| 21/21 [00:00<00:00, 296.28it/s, Loss=0.000266]


tensor([[0.3648, 0.2528],
        [0.4378, 0.1389],
        [0.4795, 0.2806],
        [0.5525, 0.3056],
        [0.6254, 0.2194],
        [0.0000, 0.1778],
        [0.0521, 0.1806],
        [0.0938, 0.1500],
        [0.1459, 0.0694],
        [0.1876, 0.2500]]) 
 tensor([[ 0.3709,  0.2418],
        [ 0.4350,  0.2058],
        [ 0.4632,  0.3046],
        [ 0.5533,  0.3273],
        [ 0.6186,  0.2589],
        [-0.0037,  0.1734],
        [ 0.0565,  0.1986],
        [ 0.0916,  0.1504],
        [ 0.1457,  0.1147],
        [ 0.1800,  0.1925]])
tensor([[0.2502, 0.1444],
        [0.3023, 0.0833],
        [0.3336, 0.1944],
        [0.4170, 0.1972],
        [0.4587, 0.1278],
        [0.5003, 0.1500],
        [0.5525, 0.0611],
        [0.5837, 0.1556],
        [0.0000, 0.2389],
        [0.0521, 0.2889]]) 
 tensor([[ 0.2475,  0.1284],
        [ 0.2965,  0.1183],
        [ 0.3294,  0.2523],
        [ 0.4076,  0.1753],
        [ 0.4455,  0.2120],
        [ 0.4778,  0.1838],
        [ 0.5390,  0.1063

100%|██████████| 21/21 [00:00<00:00, 302.42it/s, Loss=0.000307]


tensor([[0.3648, 0.2528],
        [0.4378, 0.1389],
        [0.4795, 0.2806],
        [0.5525, 0.3056],
        [0.6254, 0.2194],
        [0.0000, 0.1778],
        [0.0521, 0.1806],
        [0.0938, 0.1500],
        [0.1459, 0.0694],
        [0.1876, 0.2500]]) 
 tensor([[ 0.3761,  0.2414],
        [ 0.4418,  0.2028],
        [ 0.4659,  0.2737],
        [ 0.5593,  0.3146],
        [ 0.6315,  0.2584],
        [-0.0022,  0.1724],
        [ 0.0607,  0.1918],
        [ 0.0965,  0.1478],
        [ 0.1521,  0.1166],
        [ 0.1833,  0.1899]])
tensor([[0.2502, 0.1444],
        [0.3023, 0.0833],
        [0.3336, 0.1944],
        [0.4170, 0.1972],
        [0.4587, 0.1278],
        [0.5003, 0.1500],
        [0.5525, 0.0611],
        [0.5837, 0.1556],
        [0.0000, 0.2389],
        [0.0521, 0.2889]]) 
 tensor([[ 0.2500,  0.1345],
        [ 0.3000,  0.1195],
        [ 0.3327,  0.2450],
        [ 0.4141,  0.1609],
        [ 0.4523,  0.1996],
        [ 0.4856,  0.1737],
        [ 0.5455,  0.1130

100%|██████████| 21/21 [00:00<00:00, 288.32it/s, Loss=0.000394]


tensor([[0.3648, 0.2528],
        [0.4378, 0.1389],
        [0.4795, 0.2806],
        [0.5525, 0.3056],
        [0.6254, 0.2194],
        [0.0000, 0.1778],
        [0.0521, 0.1806],
        [0.0938, 0.1500],
        [0.1459, 0.0694],
        [0.1876, 0.2500]]) 
 tensor([[ 0.3830,  0.2198],
        [ 0.4562,  0.1734],
        [ 0.4807,  0.2418],
        [ 0.5772,  0.2789],
        [ 0.6564,  0.2105],
        [-0.0013,  0.1688],
        [ 0.0645,  0.1832],
        [ 0.1051,  0.1368],
        [ 0.1540,  0.1041],
        [ 0.1857,  0.1765]])
tensor([[0.2502, 0.1444],
        [0.3023, 0.0833],
        [0.3336, 0.1944],
        [0.4170, 0.1972],
        [0.4587, 0.1278],
        [0.5003, 0.1500],
        [0.5525, 0.0611],
        [0.5837, 0.1556],
        [0.0000, 0.2389],
        [0.0521, 0.2889]]) 
 tensor([[ 0.2484,  0.1415],
        [ 0.3029,  0.1215],
        [ 0.3379,  0.2213],
        [ 0.4254,  0.1346],
        [ 0.4659,  0.1696],
        [ 0.5027,  0.1408],
        [ 0.5661,  0.0812

100%|██████████| 21/21 [00:00<00:00, 301.29it/s, Loss=0.000418]


tensor([[0.3648, 0.2528],
        [0.4378, 0.1389],
        [0.4795, 0.2806],
        [0.5525, 0.3056],
        [0.6254, 0.2194],
        [0.0000, 0.1778],
        [0.0521, 0.1806],
        [0.0938, 0.1500],
        [0.1459, 0.0694],
        [0.1876, 0.2500]]) 
 tensor([[0.3884, 0.2004],
        [0.4718, 0.1436],
        [0.4967, 0.2099],
        [0.6008, 0.2411],
        [0.6839, 0.1655],
        [0.0012, 0.1681],
        [0.0641, 0.1840],
        [0.1079, 0.1288],
        [0.1595, 0.0960],
        [0.1887, 0.1692]])
tensor([[0.2502, 0.1444],
        [0.3023, 0.0833],
        [0.3336, 0.1944],
        [0.4170, 0.1972],
        [0.4587, 0.1278],
        [0.5003, 0.1500],
        [0.5525, 0.0611],
        [0.5837, 0.1556],
        [0.0000, 0.2389],
        [0.0521, 0.2889]]) 
 tensor([[ 0.2569,  0.0944],
        [ 0.3116,  0.0531],
        [ 0.3435,  0.1965],
        [ 0.4336,  0.1129],
        [ 0.4735,  0.1455],
        [ 0.5164,  0.1089],
        [ 0.5881,  0.0414],
        [ 0.6157,

100%|██████████| 21/21 [00:00<00:00, 302.69it/s, Loss=0.000473]


tensor([[0.3648, 0.2528],
        [0.4378, 0.1389],
        [0.4795, 0.2806],
        [0.5525, 0.3056],
        [0.6254, 0.2194],
        [0.0000, 0.1778],
        [0.0521, 0.1806],
        [0.0938, 0.1500],
        [0.1459, 0.0694],
        [0.1876, 0.2500]]) 
 tensor([[0.3808, 0.2105],
        [0.4569, 0.1566],
        [0.4852, 0.2364],
        [0.5813, 0.2578],
        [0.6523, 0.1812],
        [0.0022, 0.1657],
        [0.0469, 0.1940],
        [0.0843, 0.1314],
        [0.1522, 0.0951],
        [0.1839, 0.1618]])
tensor([[0.2502, 0.1444],
        [0.3023, 0.0833],
        [0.3336, 0.1944],
        [0.4170, 0.1972],
        [0.4587, 0.1278],
        [0.5003, 0.1500],
        [0.5525, 0.0611],
        [0.5837, 0.1556],
        [0.0000, 0.2389],
        [0.0521, 0.2889]]) 
 tensor([[ 0.2391,  0.1218],
        [ 0.2957,  0.0663],
        [ 0.3312,  0.1972],
        [ 0.4182,  0.1192],
        [ 0.4543,  0.1626],
        [ 0.4892,  0.1295],
        [ 0.5455,  0.0729],
        [ 0.5858,

100%|██████████| 21/21 [00:00<00:00, 313.23it/s, Loss=0.000347]


tensor([[0.3648, 0.2528],
        [0.4378, 0.1389],
        [0.4795, 0.2806],
        [0.5525, 0.3056],
        [0.6254, 0.2194],
        [0.0000, 0.1778],
        [0.0521, 0.1806],
        [0.0938, 0.1500],
        [0.1459, 0.0694],
        [0.1876, 0.2500]]) 
 tensor([[3.5713e-01, 2.2231e-01],
        [4.2883e-01, 1.6729e-01],
        [4.5669e-01, 2.3982e-01],
        [5.5512e-01, 2.7630e-01],
        [6.2381e-01, 1.9487e-01],
        [4.4553e-04, 1.7356e-01],
        [4.5773e-02, 1.8540e-01],
        [7.8512e-02, 1.4548e-01],
        [1.3843e-01, 1.0570e-01],
        [1.7763e-01, 1.8630e-01]])
tensor([[0.2502, 0.1444],
        [0.3023, 0.0833],
        [0.3336, 0.1944],
        [0.4170, 0.1972],
        [0.4587, 0.1278],
        [0.5003, 0.1500],
        [0.5525, 0.0611],
        [0.5837, 0.1556],
        [0.0000, 0.2389],
        [0.0521, 0.2889]]) 
 tensor([[ 0.2316,  0.1287],
        [ 0.2916,  0.0787],
        [ 0.3171,  0.2206],
        [ 0.4018,  0.1385],
        [ 0.4318,  0.

100%|██████████| 21/21 [00:00<00:00, 302.17it/s, Loss=0.000258]


tensor([[0.3648, 0.2528],
        [0.4378, 0.1389],
        [0.4795, 0.2806],
        [0.5525, 0.3056],
        [0.6254, 0.2194],
        [0.0000, 0.1778],
        [0.0521, 0.1806],
        [0.0938, 0.1500],
        [0.1459, 0.0694],
        [0.1876, 0.2500]]) 
 tensor([[ 3.4718e-01,  2.1579e-01],
        [ 4.1760e-01,  1.5940e-01],
        [ 4.4553e-01,  2.4970e-01],
        [ 5.3619e-01,  2.7317e-01],
        [ 6.0178e-01,  2.0044e-01],
        [-1.3210e-05,  1.7001e-01],
        [ 4.9454e-02,  1.7553e-01],
        [ 7.6989e-02,  1.4158e-01],
        [ 1.4179e-01,  9.3708e-02],
        [ 1.7309e-01,  1.7777e-01]])
tensor([[0.2502, 0.1444],
        [0.3023, 0.0833],
        [0.3336, 0.1944],
        [0.4170, 0.1972],
        [0.4587, 0.1278],
        [0.5003, 0.1500],
        [0.5525, 0.0611],
        [0.5837, 0.1556],
        [0.0000, 0.2389],
        [0.0521, 0.2889]]) 
 tensor([[ 0.2290,  0.0887],
        [ 0.2839,  0.0381],
        [ 0.3125,  0.2111],
        [ 0.3976,  0.1272],
 

100%|██████████| 21/21 [00:00<00:00, 316.76it/s, Loss=0.000255]


tensor([[0.3648, 0.2528],
        [0.4378, 0.1389],
        [0.4795, 0.2806],
        [0.5525, 0.3056],
        [0.6254, 0.2194],
        [0.0000, 0.1778],
        [0.0521, 0.1806],
        [0.0938, 0.1500],
        [0.1459, 0.0694],
        [0.1876, 0.2500]]) 
 tensor([[ 0.3381,  0.2103],
        [ 0.4079,  0.1537],
        [ 0.4354,  0.2464],
        [ 0.5216,  0.2598],
        [ 0.5865,  0.1919],
        [-0.0021,  0.1705],
        [ 0.0464,  0.1808],
        [ 0.0787,  0.1341],
        [ 0.1346,  0.0916],
        [ 0.1672,  0.1812]])
tensor([[0.2502, 0.1444],
        [0.3023, 0.0833],
        [0.3336, 0.1944],
        [0.4170, 0.1972],
        [0.4587, 0.1278],
        [0.5003, 0.1500],
        [0.5525, 0.0611],
        [0.5837, 0.1556],
        [0.0000, 0.2389],
        [0.0521, 0.2889]]) 
 tensor([[ 0.2185,  0.0992],
        [ 0.2728,  0.0616],
        [ 0.3069,  0.2056],
        [ 0.3913,  0.1170],
        [ 0.4205,  0.1582],
        [ 0.4546,  0.1254],
        [ 0.5184,  0.0403

100%|██████████| 21/21 [00:00<00:00, 322.11it/s, Loss=0.000281]


tensor([[0.3648, 0.2528],
        [0.4378, 0.1389],
        [0.4795, 0.2806],
        [0.5525, 0.3056],
        [0.6254, 0.2194],
        [0.0000, 0.1778],
        [0.0521, 0.1806],
        [0.0938, 0.1500],
        [0.1459, 0.0694],
        [0.1876, 0.2500]]) 
 tensor([[ 0.3289,  0.2055],
        [ 0.3973,  0.1511],
        [ 0.4230,  0.2352],
        [ 0.5090,  0.2559],
        [ 0.5693,  0.1847],
        [-0.0031,  0.1714],
        [ 0.0475,  0.1820],
        [ 0.0749,  0.1369],
        [ 0.1338,  0.0950],
        [ 0.1644,  0.1851]])
tensor([[0.2502, 0.1444],
        [0.3023, 0.0833],
        [0.3336, 0.1944],
        [0.4170, 0.1972],
        [0.4587, 0.1278],
        [0.5003, 0.1500],
        [0.5525, 0.0611],
        [0.5837, 0.1556],
        [0.0000, 0.2389],
        [0.0521, 0.2889]]) 
 tensor([[ 0.2116,  0.0932],
        [ 0.2695,  0.0621],
        [ 0.3028,  0.2107],
        [ 0.3840,  0.1259],
        [ 0.4141,  0.1582],
        [ 0.4468,  0.1268],
        [ 0.5076,  0.0377

100%|██████████| 21/21 [00:00<00:00, 274.72it/s, Loss=0.000334]


tensor([[0.3648, 0.2528],
        [0.4378, 0.1389],
        [0.4795, 0.2806],
        [0.5525, 0.3056],
        [0.6254, 0.2194],
        [0.0000, 0.1778],
        [0.0521, 0.1806],
        [0.0938, 0.1500],
        [0.1459, 0.0694],
        [0.1876, 0.2500]]) 
 tensor([[ 0.3287,  0.2047],
        [ 0.3977,  0.1503],
        [ 0.4222,  0.2317],
        [ 0.5078,  0.2552],
        [ 0.5662,  0.1831],
        [-0.0020,  0.1719],
        [ 0.0493,  0.1804],
        [ 0.0734,  0.1354],
        [ 0.1359,  0.0973],
        [ 0.1658,  0.1855]])
tensor([[0.2502, 0.1444],
        [0.3023, 0.0833],
        [0.3336, 0.1944],
        [0.4170, 0.1972],
        [0.4587, 0.1278],
        [0.5003, 0.1500],
        [0.5525, 0.0611],
        [0.5837, 0.1556],
        [0.0000, 0.2389],
        [0.0521, 0.2889]]) 
 tensor([[ 0.2098,  0.0966],
        [ 0.2746,  0.0690],
        [ 0.3065,  0.2132],
        [ 0.3861,  0.1265],
        [ 0.4194,  0.1599],
        [ 0.4511,  0.1278],
        [ 0.5072,  0.0350

100%|██████████| 21/21 [00:00<00:00, 313.57it/s, Loss=0.000398]


tensor([[0.3648, 0.2528],
        [0.4378, 0.1389],
        [0.4795, 0.2806],
        [0.5525, 0.3056],
        [0.6254, 0.2194],
        [0.0000, 0.1778],
        [0.0521, 0.1806],
        [0.0938, 0.1500],
        [0.1459, 0.0694],
        [0.1876, 0.2500]]) 
 tensor([[3.4450e-01, 2.0783e-01],
        [4.1837e-01, 1.4879e-01],
        [4.4233e-01, 2.2382e-01],
        [5.3153e-01, 2.5502e-01],
        [5.9231e-01, 1.8604e-01],
        [9.7357e-05, 1.7252e-01],
        [5.3978e-02, 1.8102e-01],
        [7.9564e-02, 1.3331e-01],
        [1.4054e-01, 1.0158e-01],
        [1.7239e-01, 1.8907e-01]])
tensor([[0.2502, 0.1444],
        [0.3023, 0.0833],
        [0.3336, 0.1944],
        [0.4170, 0.1972],
        [0.4587, 0.1278],
        [0.5003, 0.1500],
        [0.5525, 0.0611],
        [0.5837, 0.1556],
        [0.0000, 0.2389],
        [0.0521, 0.2889]]) 
 tensor([[ 0.2199,  0.0993],
        [ 0.2942,  0.0665],
        [ 0.3214,  0.2189],
        [ 0.4031,  0.1260],
        [ 0.4438,  0.

100%|██████████| 21/21 [00:00<00:00, 321.10it/s, Loss=0.000427]


tensor([[0.3648, 0.2528],
        [0.4378, 0.1389],
        [0.4795, 0.2806],
        [0.5525, 0.3056],
        [0.6254, 0.2194],
        [0.0000, 0.1778],
        [0.0521, 0.1806],
        [0.0938, 0.1500],
        [0.1459, 0.0694],
        [0.1876, 0.2500]]) 
 tensor([[0.3794, 0.2169],
        [0.4598, 0.1567],
        [0.4857, 0.2342],
        [0.5815, 0.2662],
        [0.6521, 0.1966],
        [0.0047, 0.1725],
        [0.0583, 0.1776],
        [0.0882, 0.1295],
        [0.1477, 0.1011],
        [0.1872, 0.1919]])
tensor([[0.2502, 0.1444],
        [0.3023, 0.0833],
        [0.3336, 0.1944],
        [0.4170, 0.1972],
        [0.4587, 0.1278],
        [0.5003, 0.1500],
        [0.5525, 0.0611],
        [0.5837, 0.1556],
        [0.0000, 0.2389],
        [0.0521, 0.2889]]) 
 tensor([[ 0.2464,  0.1028],
        [ 0.3301,  0.0672],
        [ 0.3503,  0.2271],
        [ 0.4360,  0.1316],
        [ 0.4861,  0.1703],
        [ 0.5194,  0.1402],
        [ 0.5735,  0.0418],
        [ 0.6075,

100%|██████████| 21/21 [00:00<00:00, 304.88it/s, Loss=0.000407]


tensor([[0.3648, 0.2528],
        [0.4378, 0.1389],
        [0.4795, 0.2806],
        [0.5525, 0.3056],
        [0.6254, 0.2194],
        [0.0000, 0.1778],
        [0.0521, 0.1806],
        [0.0938, 0.1500],
        [0.1459, 0.0694],
        [0.1876, 0.2500]]) 
 tensor([[0.4091, 0.2298],
        [0.4891, 0.1761],
        [0.5141, 0.2638],
        [0.6126, 0.2993],
        [0.6947, 0.2250],
        [0.0076, 0.1736],
        [0.0616, 0.1838],
        [0.0960, 0.1361],
        [0.1590, 0.1044],
        [0.1991, 0.1957]])
tensor([[0.2502, 0.1444],
        [0.3023, 0.0833],
        [0.3336, 0.1944],
        [0.4170, 0.1972],
        [0.4587, 0.1278],
        [0.5003, 0.1500],
        [0.5525, 0.0611],
        [0.5837, 0.1556],
        [0.0000, 0.2389],
        [0.0521, 0.2889]]) 
 tensor([[0.2733, 0.1158],
        [0.3532, 0.0817],
        [0.3711, 0.2391],
        [0.4535, 0.1488],
        [0.5064, 0.1940],
        [0.5425, 0.1624],
        [0.6006, 0.0635],
        [0.6296, 0.2049],
     

100%|██████████| 21/21 [00:00<00:00, 263.53it/s, Loss=0.000419]


tensor([[0.3648, 0.2528],
        [0.4378, 0.1389],
        [0.4795, 0.2806],
        [0.5525, 0.3056],
        [0.6254, 0.2194],
        [0.0000, 0.1778],
        [0.0521, 0.1806],
        [0.0938, 0.1500],
        [0.1459, 0.0694],
        [0.1876, 0.2500]]) 
 tensor([[0.3971, 0.2390],
        [0.4737, 0.1850],
        [0.4981, 0.2763],
        [0.5941, 0.3016],
        [0.6811, 0.2209],
        [0.0042, 0.1775],
        [0.0623, 0.1817],
        [0.0981, 0.1423],
        [0.1613, 0.1148],
        [0.1854, 0.2006]])
tensor([[0.2502, 0.1444],
        [0.3023, 0.0833],
        [0.3336, 0.1944],
        [0.4170, 0.1972],
        [0.4587, 0.1278],
        [0.5003, 0.1500],
        [0.5525, 0.0611],
        [0.5837, 0.1556],
        [0.0000, 0.2389],
        [0.0521, 0.2889]]) 
 tensor([[ 2.5943e-01,  1.5123e-01],
        [ 3.2419e-01,  1.2531e-01],
        [ 3.4903e-01,  2.4652e-01],
        [ 4.2929e-01,  1.6555e-01],
        [ 4.8279e-01,  1.9300e-01],
        [ 5.1644e-01,  1.6424e-01