### Before the start

In [1]:
# # before start
# %pip install tld
# %pip install category_encoders

# ! pip install pytz
# !pip install timezonefinder
# !pip install geopy

# !pip3 install torch
# !pip3 install torchvision
# !pip3 install tqdm

# !pip install torch -q
# !pip install keras

# !pip install skorch
# !pip install bayesian-optimization

# # !pip install cudf
# # !pip install cudf-cu11==22.12 rmm-cu11==22.12 dask-cudf-cu11==22.12 --extra-index-url=https://pypi.ngc.nvidia.com/

In [2]:
# load data and import libraries
import pandas as pd
import numpy as np
import pytz
# from geopy.geocoders import Nominatim
# from timezonefinder import TimezoneFinder
import datetime

import torch
# For layers and models
import torch.nn as nn
# For activation functions (F.sigmoid is deprecated)
import torch.nn.functional as F
from torch import sigmoid

import os
import warnings
warnings.filterwarnings("ignore")
from torch.utils.data import Dataset, DataLoader
# Collection of optimizers
import torch.optim as optim

# use_cuda = torch.cuda.is_available()
# device = torch.device("cuda" if use_cuda else "cpu")
# model = CustomModel().to(device)

### ANN preprocessing

In [3]:
new_labels = [
    "Sport",
    "Hobby Passive",
    "Work&Study",
    "Daily Routine"
]
match_labels_v3 = [0,3,0,1,2,2,3]

match_labels = {
    "Sport": 0,
    "Food": 3,
    "Hobby Active": 0,
    "Hobby Passive": 1,
    "Studying":2,
    "Work":2,
    "Other":3
}


In [4]:
df = pd.read_csv('schedule.csv')

df['Label Number'] = df['Label'].apply(lambda x: match_labels[x])
df['Label Name'] = df['Label Number'].apply(lambda x: new_labels[x])

df.drop(columns=['Label', 'Activity', 'End Time', 'If Has Deadline', 'Deadline Time', 'Deadline Date'], inplace=True)

mini = df['Importance'].min()
maxi = df['Importance'].max()
df['Importance'] = df['Importance'].apply(lambda x: int((x-mini) / (maxi-mini) * 3) )

df_out = df[208:]

df[:13]

Date Start Time  Duration  Importance  Label Number     Label Name
0   2023-06-16      07:00        60           1             3  Daily Routine
1   2023-06-16      08:15        45           2             0          Sport
2   2023-06-16      09:15        60           0             1  Hobby Passive
3   2023-06-16      10:30        45           3             2     Work&Study
4   2023-06-16      11:30        60           1             3  Daily Routine
5   2023-06-16      13:00        60           2             2     Work&Study
6   2023-06-16      14:15        30           0             0          Sport
7   2023-06-16      15:00        90           1             2     Work&Study
8   2023-06-16      17:00        45           1             3  Daily Routine
9   2023-06-16      18:00        45           2             0          Sport
10  2023-06-16      19:00        60           1             1  Hobby Passive
11  2023-06-16      20:15        30           0             1  Hobby Passive
12  2023-06-16      21:00        60           0             3  Daily Routine

In [5]:
from sklearn.preprocessing import OneHotEncoder

def encode_features(df, features_name, encoder):
    new_features = encoder.transform(df[features_name])
    # create dataframe from encoded features with named columns
    new_columns = pd.DataFrame(new_features, columns=encoder.get_feature_names_out())
    new_df = pd.concat([df, new_columns], axis=1)
    # new_df.drop(features_name, axis=1, inplace=True)
    return new_df

encoder = OneHotEncoder(sparse=False, drop='first')
enc_column = ['Label Number']
encoder.fit(df[enc_column])
df = encode_features(df, enc_column, encoder)

df

Date Start Time  Duration  Importance  Label Number     Label Name  \
0    2023-06-16      07:00        60           1             3  Daily Routine   
1    2023-06-16      08:15        45           2             0          Sport   
2    2023-06-16      09:15        60           0             1  Hobby Passive   
3    2023-06-16      10:30        45           3             2     Work&Study   
4    2023-06-16      11:30        60           1             3  Daily Routine   
..          ...        ...       ...         ...           ...            ...   
249  2023-07-07      15:45        90           2             2     Work&Study   
250  2023-07-07      17:30        45           1             3  Daily Routine   
251  2023-07-07      18:30        90           1             0          Sport   
252  2023-07-07      20:15        90           2             3  Daily Routine   
253  2023-07-07      22:00        60           0             3  Daily Routine   

     Label Number_1  Label Number_2  Label Number_3  
0               0.0             0.0             1.0  
1               0.0             0.0             0.0  
2               1.0             0.0             0.0  
3               0.0             1.0             0.0  
4               0.0             0.0             1.0  
..              ...             ...             ...  
249             0.0             1.0             0.0  
250             0.0             0.0             1.0  
251             0.0             0.0             0.0  
252             0.0             0.0             1.0  
253             0.0             0.0             1.0  

[254 rows x 9 columns]

In [7]:
def make_true_duration(x):
    true_noise = [20, -15, 20, -10]
    result= x['Duration'] + true_noise[x['Label Number']] + int(np.random.uniform(low=-5, high=5))

    if result < 10:
        return 10

    return result

df['True Duration'] = df.apply(lambda x: make_true_duration(x), axis=1)
df

Date Start Time  Duration  Importance  Label Number     Label Name  \
0    2023-06-16      07:00        60           1             3  Daily Routine   
1    2023-06-16      08:15        45           2             0          Sport   
2    2023-06-16      09:15        60           0             1  Hobby Passive   
3    2023-06-16      10:30        45           3             2     Work&Study   
4    2023-06-16      11:30        60           1             3  Daily Routine   
..          ...        ...       ...         ...           ...            ...   
249  2023-07-07      15:45        90           2             2     Work&Study   
250  2023-07-07      17:30        45           1             3  Daily Routine   
251  2023-07-07      18:30        90           1             0          Sport   
252  2023-07-07      20:15        90           2             3  Daily Routine   
253  2023-07-07      22:00        60           0             3  Daily Routine   

     Label Number_1  Label Number_2  Label Number_3  True Duration  
0               0.0             0.0             1.0             50  
1               0.0             0.0             0.0             67  
2               1.0             0.0             0.0             41  
3               0.0             1.0             0.0             63  
4               0.0             0.0             1.0             50  
..              ...             ...             ...            ...  
249             0.0             1.0             0.0            107  
250             0.0             0.0             1.0             32  
251             0.0             0.0             0.0            113  
252             0.0             0.0             1.0             82  
253             0.0             0.0             1.0             48  

[254 rows x 10 columns]

In [9]:
# def make_true_duration(x, prob=1.3):
#     true_noise = [[-5,20], [-15,0], [-20,5], [-10,30]]
#     addi = np.random.uniform(low=prob*true_noise[x['Label Number']][0], high=prob * true_noise[x['Label Number']][1])
#     result= x['Duration'] + int(addi)
#     if addi > true_noise[x['Label Number']][1]:
#         result= x['Duration'] + true_noise[x['Label Number']][1]
#     elif addi < true_noise[x['Label Number']][0]:
#         result= x['Duration'] + true_noise[x['Label Number']][0]
#     if result < 10:
#         return 10
#     return result

# df['True Duration'] = df.apply(lambda x: make_true_duration(x), axis=1)
# df

In [10]:
min_time = datetime.datetime.strptime("00:00", '%H:%M')
max_time = ((datetime.datetime.strptime("23:59", '%H:%M')-min_time).total_seconds()+1)//60
# df['Start Time'] = df['Start Time'].apply(lambda x: ((datetime.datetime.strptime(x, '%H:%M')-min_time).total_seconds()+1)/max_time)
df['Start Time'] = df['Start Time'].apply(lambda x: (datetime.datetime.strptime(x, '%H:%M')-min_time).total_seconds()//60)

# move start time
cur_day = '1/1/2020'
delta = 0

for index, row in df.iterrows():
    if row['Date'] != cur_day:
        delta = row['Start Time']
        cur_day = row['Date']
    df.at[index, 'Start Time'] -= delta

df['True Start Time'] = df['Start Time']

df_out['True Duration'] = df['True Duration']
df_out['True Hours'] = df['True Start Time']//24
df_out['True Minutes'] = df['True Start Time']%24

df.describe()

Start Time    Duration  Importance  Label Number  Label Number_1  \
count  254.000000  254.000000  254.000000    254.000000      254.000000   
mean   426.496063   66.259843    1.251969      1.779528        0.110236   
std    278.493487   19.999689    0.897678      1.231429        0.313802   
min      0.000000   30.000000    0.000000      0.000000        0.000000   
25%    180.000000   45.000000    1.000000      0.000000        0.000000   
50%    420.000000   60.000000    1.000000      2.000000        0.000000   
75%    660.000000   90.000000    2.000000      3.000000        0.000000   
max    900.000000   90.000000    3.000000      3.000000        1.000000   

       Label Number_2  Label Number_3  True Duration  True Start Time  
count      254.000000      254.000000     254.000000       254.000000  
mean         0.220472        0.409449      70.070866       426.496063  
std          0.415384        0.492703      30.327248       278.493487  
min          0.000000        0.000000      11.000000         0.000000  
25%          0.000000        0.000000      47.000000       180.000000  
50%          0.000000        0.000000      63.000000       420.000000  
75%          0.000000        1.000000     107.750000       660.000000  
max          1.000000        1.000000     114.000000       900.000000

In [11]:
TS_DUR =10
LENGTH = 1200

def parse_date(d):
    res = [int(i) for i in d.split('/')[::-1]]
    return datetime.date(*res)

cur_day = '1/1/2020'
# basic_slots = [0]*(2*60//10)+[1]*(3*60//10)+[0]*(2*60//10)
basic_slots = [0]*(LENGTH//TS_DUR)

available_time_slots = [0]*(LENGTH//TS_DUR)
names = ['TS'+str(i) for i in range(len(available_time_slots))]
df[names] = available_time_slots

for index, row in df.iterrows():
    if row['Date'] == cur_day:
        df.loc[index, names] = available_time_slots.copy()
    else:
        cur_day = row['Date']
        available_time_slots = basic_slots.copy()
        df.loc[index, names] = available_time_slots.copy()
    start = int(row['True Start Time'] / TS_DUR)
    end = int((row['True Start Time'] + row['True Duration']) // TS_DUR) + [1 if (row['True Start Time'] + row['True Duration']) % TS_DUR > 0 else 0][0]
    # print(start, end, row['True Duration'] )
    df.loc[index, 'Summ'] = sum(available_time_slots)

    available_time_slots[start:end+1] = [1]*(end-start+1)
    # print(index, available_time_slots)

df

Date  Start Time  Duration  Importance  Label Number  \
0    2023-06-16         0.0        60           1             3   
1    2023-06-16        75.0        45           2             0   
2    2023-06-16       135.0        60           0             1   
3    2023-06-16       210.0        45           3             2   
4    2023-06-16       270.0        60           1             3   
..          ...         ...       ...         ...           ...   
249  2023-07-07       525.0        90           2             2   
250  2023-07-07       630.0        45           1             3   
251  2023-07-07       690.0        90           1             0   
252  2023-07-07       795.0        90           2             3   
253  2023-07-07       900.0        60           0             3   

        Label Name  Label Number_1  Label Number_2  Label Number_3  \
0    Daily Routine             0.0             0.0             1.0   
1            Sport             0.0             0.0             0.0   
2    Hobby Passive             1.0             0.0             0.0   
3       Work&Study             0.0             1.0             0.0   
4    Daily Routine             0.0             0.0             1.0   
..             ...             ...             ...             ...   
249     Work&Study             0.0             1.0             0.0   
250  Daily Routine             0.0             0.0             1.0   
251          Sport             0.0             0.0             0.0   
252  Daily Routine             0.0             0.0             1.0   
253  Daily Routine             0.0             0.0             1.0   

     True Duration  ...  TS111  TS112  TS113  TS114  TS115  TS116  TS117  \
0               50  ...      0      0      0      0      0      0      0   
1               67  ...      0      0      0      0      0      0      0   
2               41  ...      0      0      0      0      0      0      0   
3               63  ...      0      0      0      0      0      0      0   
4               50  ...      0      0      0      0      0      0      0   
..             ...  ...    ...    ...    ...    ...    ...    ...    ...   
249            107  ...      0      0      0      0      0      0      0   
250             32  ...      0      0      0      0      0      0      0   
251            113  ...      0      0      0      0      0      0      0   
252             82  ...      0      0      0      0      0      0      0   
253             48  ...      0      0      0      0      0      0      0   

     TS118  TS119  Summ  
0        0      0   0.0  
1        0      0   6.0  
2        0      0  15.0  
3        0      0  18.0  
4        0      0  26.0  
..     ...    ...   ...  
249      0      0  52.0  
250      0      0  62.0  
251      0      0  65.0  
252      0      0  78.0  
253      0      0  85.0  

[254 rows x 132 columns]

In [12]:
# scaling
DUR = 6*60
df['Importance'] = df['Importance'] / 3

df.drop(columns=['Label Name'], inplace=True)

df['Duration'] = df['Duration'] / DUR
df['True Duration'] = df['True Duration'] / DUR

df

Date  Start Time  Duration  Importance  Label Number  \
0    2023-06-16         0.0  0.166667    0.333333             3   
1    2023-06-16        75.0  0.125000    0.666667             0   
2    2023-06-16       135.0  0.166667    0.000000             1   
3    2023-06-16       210.0  0.125000    1.000000             2   
4    2023-06-16       270.0  0.166667    0.333333             3   
..          ...         ...       ...         ...           ...   
249  2023-07-07       525.0  0.250000    0.666667             2   
250  2023-07-07       630.0  0.125000    0.333333             3   
251  2023-07-07       690.0  0.250000    0.333333             0   
252  2023-07-07       795.0  0.250000    0.666667             3   
253  2023-07-07       900.0  0.166667    0.000000             3   

     Label Number_1  Label Number_2  Label Number_3  True Duration  \
0               0.0             0.0             1.0       0.138889   
1               0.0             0.0             0.0       0.186111   
2               1.0             0.0             0.0       0.113889   
3               0.0             1.0             0.0       0.175000   
4               0.0             0.0             1.0       0.138889   
..              ...             ...             ...            ...   
249             0.0             1.0             0.0       0.297222   
250             0.0             0.0             1.0       0.088889   
251             0.0             0.0             0.0       0.313889   
252             0.0             0.0             1.0       0.227778   
253             0.0             0.0             1.0       0.133333   

     True Start Time  ...  TS111  TS112  TS113  TS114  TS115  TS116  TS117  \
0                0.0  ...      0      0      0      0      0      0      0   
1               75.0  ...      0      0      0      0      0      0      0   
2              135.0  ...      0      0      0      0      0      0      0   
3              210.0  ...      0      0      0      0      0      0      0   
4              270.0  ...      0      0      0      0      0      0      0   
..               ...  ...    ...    ...    ...    ...    ...    ...    ...   
249            525.0  ...      0      0      0      0      0      0      0   
250            630.0  ...      0      0      0      0      0      0      0   
251            690.0  ...      0      0      0      0      0      0      0   
252            795.0  ...      0      0      0      0      0      0      0   
253            900.0  ...      0      0      0      0      0      0      0   

     TS118  TS119  Summ  
0        0      0   0.0  
1        0      0   6.0  
2        0      0  15.0  
3        0      0  18.0  
4        0      0  26.0  
..     ...    ...   ...  
249      0      0  52.0  
250      0      0  62.0  
251      0      0  65.0  
252      0      0  78.0  
253      0      0  85.0  

[254 rows x 131 columns]

In [13]:
def drop_some_values(x, prob=0.95 ):
    if np.random.uniform() > prob:
        return 0
    return x

df['Duration'] = df['Duration'].apply(lambda x: drop_some_values(x))

df['Start Time'] = df['Start Time'] / max_time
df['True Start Time'] = df['Start Time']
df['Start Time'] = df['Start Time'].apply(lambda x: drop_some_values(x))
df.describe()

Start Time    Duration  Importance  Label Number  Label Number_1  \
count  254.000000  254.000000  254.000000    254.000000      254.000000   
mean     0.277218    0.176345    0.417323      1.779528        0.110236   
std      0.200578    0.065922    0.299226      1.231429        0.313802   
min      0.000000    0.000000    0.000000      0.000000        0.000000   
25%      0.093815    0.125000    0.333333      0.000000        0.000000   
50%      0.260598    0.166667    0.333333      2.000000        0.000000   
75%      0.458652    0.250000    0.666667      3.000000        0.000000   
max      0.625434    0.250000    1.000000      3.000000        1.000000   

       Label Number_2  Label Number_3  True Duration  True Start Time  \
count      254.000000      254.000000     254.000000       254.000000   
mean         0.220472        0.409449       0.194641         0.296384   
std          0.415384        0.492703       0.084242         0.193533   
min          0.000000        0.000000       0.030556         0.000000   
25%          0.000000        0.000000       0.130556         0.125087   
50%          0.000000        0.000000       0.175000         0.291869   
75%          0.000000        1.000000       0.299306         0.458652   
max          1.000000        1.000000       0.316667         0.625434   

              TS0  ...  TS111  TS112  TS113  TS114  TS115  TS116  TS117  \
count  254.000000  ...  254.0  254.0  254.0  254.0  254.0  254.0  254.0   
mean     0.913386  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
std      0.281824  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
min      0.000000  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
25%      1.000000  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
50%      1.000000  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
75%      1.000000  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
max      1.000000  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

       TS118  TS119        Summ  
count  254.0  254.0  254.000000  
mean     0.0    0.0   40.767717  
std      0.0    0.0   26.490903  
min      0.0    0.0    0.000000  
25%      0.0    0.0   19.000000  
50%      0.0    0.0   41.000000  
75%      0.0    0.0   63.000000  
max      0.0    0.0   86.000000  

[8 rows x 130 columns]

In [14]:
df

Date  Start Time  Duration  Importance  Label Number  \
0    2023-06-16    0.000000  0.166667    0.333333             3   
1    2023-06-16    0.052120  0.125000    0.666667             0   
2    2023-06-16    0.093815  0.166667    0.000000             1   
3    2023-06-16    0.145935  0.125000    1.000000             2   
4    2023-06-16    0.000000  0.166667    0.333333             3   
..          ...         ...       ...         ...           ...   
249  2023-07-07    0.364837  0.250000    0.666667             2   
250  2023-07-07    0.437804  0.125000    0.333333             3   
251  2023-07-07    0.479500  0.250000    0.333333             0   
252  2023-07-07    0.552467  0.250000    0.666667             3   
253  2023-07-07    0.625434  0.166667    0.000000             3   

     Label Number_1  Label Number_2  Label Number_3  True Duration  \
0               0.0             0.0             1.0       0.138889   
1               0.0             0.0             0.0       0.186111   
2               1.0             0.0             0.0       0.113889   
3               0.0             1.0             0.0       0.175000   
4               0.0             0.0             1.0       0.138889   
..              ...             ...             ...            ...   
249             0.0             1.0             0.0       0.297222   
250             0.0             0.0             1.0       0.088889   
251             0.0             0.0             0.0       0.313889   
252             0.0             0.0             1.0       0.227778   
253             0.0             0.0             1.0       0.133333   

     True Start Time  ...  TS111  TS112  TS113  TS114  TS115  TS116  TS117  \
0           0.000000  ...      0      0      0      0      0      0      0   
1           0.052120  ...      0      0      0      0      0      0      0   
2           0.093815  ...      0      0      0      0      0      0      0   
3           0.145935  ...      0      0      0      0      0      0      0   
4           0.187630  ...      0      0      0      0      0      0      0   
..               ...  ...    ...    ...    ...    ...    ...    ...    ...   
249         0.364837  ...      0      0      0      0      0      0      0   
250         0.437804  ...      0      0      0      0      0      0      0   
251         0.479500  ...      0      0      0      0      0      0      0   
252         0.552467  ...      0      0      0      0      0      0      0   
253         0.625434  ...      0      0      0      0      0      0      0   

     TS118  TS119  Summ  
0        0      0   0.0  
1        0      0   6.0  
2        0      0  15.0  
3        0      0  18.0  
4        0      0  26.0  
..     ...    ...   ...  
249      0      0  52.0  
250      0      0  62.0  
251      0      0  65.0  
252      0      0  78.0  
253      0      0  85.0  

[254 rows x 131 columns]

### Test train dataset

In [15]:
X = df.drop(columns=['Date', 'True Duration', 'True Start Time', 'Label Number', 'Summ'])
y = df[['True Start Time', 'True Duration']]

In [16]:
len(X.columns)

126

In [17]:
y.describe()

True Start Time  True Duration
count       254.000000     254.000000
mean          0.296384       0.194641
std           0.193533       0.084242
min           0.000000       0.030556
25%           0.125087       0.130556
50%           0.291869       0.175000
75%           0.458652       0.299306
max           0.625434       0.316667

In [18]:
X = X.to_numpy()
y = y.to_numpy()


In [19]:
y

array([[0.        , 0.13888889],
       [0.05211953, 0.18611111],
       [0.09381515, 0.11388889],
       [0.14593468, 0.175     ],
       [0.1876303 , 0.13888889],
       [0.25017373, 0.21388889],
       [0.30229326, 0.13055556],
       [0.33356498, 0.30555556],
       [0.41695622, 0.1       ],
       [0.45865184, 0.19166667],
       [0.50034746, 0.13055556],
       [0.55246699, 0.04166667],
       [0.58373871, 0.12777778],
       [0.        , 0.13888889],
       [0.05211953, 0.16944444],
       [0.09381515, 0.30277778],
       [0.16678249, 0.10833333],
       [0.20847811, 0.22222222],
       [0.26059764, 0.29722222],
       [0.33356498, 0.30555556],
       [0.41695622, 0.10833333],
       [0.45865184, 0.30555556],
       [0.53161918, 0.225     ],
       [0.60458652, 0.15      ],
       [0.        , 0.14166667],
       [0.05211953, 0.31388889],
       [0.12508687, 0.13055556],
       [0.17720639, 0.09722222],
       [0.21890202, 0.30555556],
       [0.29186935, 0.30833333],
       [0.

In [20]:
len(torch.tensor(y,dtype=torch.float32))

254

In [21]:
df[208:]

Date  Start Time  Duration  Importance  Label Number  \
208  2023-07-04    0.000000  0.166667    0.333333             3   
209  2023-07-04    0.052120  0.125000    0.666667             0   
210  2023-07-04    0.093815  0.166667    0.000000             1   
211  2023-07-04    0.145935  0.125000    1.000000             2   
212  2023-07-04    0.187630  0.166667    0.333333             3   
213  2023-07-04    0.250174  0.166667    0.666667             2   
214  2023-07-04    0.302293  0.083333    0.000000             0   
215  2023-07-04    0.333565  0.250000    0.333333             2   
216  2023-07-04    0.416956  0.125000    0.333333             3   
217  2023-07-04    0.458652  0.125000    0.666667             0   
218  2023-07-04    0.500347  0.166667    0.333333             1   
219  2023-07-04    0.552467  0.083333    0.000000             1   
220  2023-07-04    0.000000  0.166667    0.000000             3   
221  2023-07-05    0.000000  0.166667    0.333333             3   
222  2023-07-05    0.000000  0.250000    0.666667             0   
223  2023-07-05    0.125087  0.166667    0.666667             1   
224  2023-07-05    0.177206  0.125000    0.000000             3   
225  2023-07-05    0.218902  0.250000    1.000000             2   
226  2023-07-05    0.291869  0.250000    0.333333             0   
227  2023-07-05    0.364837  0.250000    0.666667             2   
228  2023-07-05    0.437804  0.125000    0.333333             3   
229  2023-07-05    0.479500  0.250000    0.333333             0   
230  2023-07-05    0.552467  0.250000    0.666667             3   
231  2023-07-05    0.625434  0.166667    0.000000             3   
232  2023-07-06    0.000000  0.166667    0.333333             3   
233  2023-07-06    0.052120  0.125000    0.666667             0   
234  2023-07-06    0.093815  0.250000    1.000000             2   
235  2023-07-06    0.166782  0.125000    0.000000             3   
236  2023-07-06    0.208478  0.166667    0.666667             2   
237  2023-07-06    0.260598  0.250000    0.333333             0   
238  2023-07-06    0.333565  0.250000    0.333333             2   
239  2023-07-06    0.416956  0.125000    0.333333             3   
240  2023-07-06    0.458652  0.250000    0.333333             0   
241  2023-07-06    0.531619  0.250000    0.666667             3   
242  2023-07-06    0.604587  0.166667    0.000000             3   
243  2023-07-07    0.000000  0.166667    0.333333             3   
244  2023-07-07    0.052120  0.250000    0.666667             0   
245  2023-07-07    0.125087  0.166667    0.666667             1   
246  2023-07-07    0.177206  0.125000    0.000000             3   
247  2023-07-07    0.218902  0.250000    1.000000             2   
248  2023-07-07    0.291869  0.250000    0.333333             0   
249  2023-07-07    0.364837  0.250000    0.666667             2   
250  2023-07-07    0.437804  0.125000    0.333333             3   
251  2023-07-07    0.479500  0.250000    0.333333             0   
252  2023-07-07    0.552467  0.250000    0.666667             3   
253  2023-07-07    0.625434  0.166667    0.000000             3   

     Label Number_1  Label Number_2  Label Number_3  True Duration  \
208             0.0             0.0             1.0       0.127778   
209             0.0             0.0             0.0       0.172222   
210             1.0             0.0             0.0       0.116667   
211             0.0             1.0             0.0       0.177778   
212             0.0             0.0             1.0       0.138889   
213             0.0             1.0             0.0       0.225000   
214             0.0             0.0             0.0       0.136111   
215             0.0             1.0             0.0       0.302778   
216             0.0             0.0             1.0       0.097222   
217             0.0             0.0             0.0       0.175000   
218             1.0             0.0             0.0       0.136111   
219             1.0  

In [22]:
from sklearn.model_selection import train_test_split

class TaskDataset(Dataset):
  def __init__(self,X, y):
    self.x_train=torch.tensor(X,dtype=torch.float32)
    self.y_train=torch.tensor(y,dtype=torch.float32)

  def __len__(self):
    return len(self.y_train)

  def __getitem__(self,idx):
    return self.x_train[idx], self.y_train[idx]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.18, random_state=42, shuffle=False)
datasets = {
    'train': TaskDataset(X_train, y_train),
    'test': TaskDataset(X_test, y_test)
}

batch_size = 1
dataloaders = {
    'train': DataLoader(datasets['train'], batch_size=batch_size, shuffle=False),
    # 'val': DataLoader(valData, batch_size=batch_size, shuffle=False),
    'test': DataLoader(datasets['test'], batch_size=batch_size, shuffle=False)
}

### Model designing

In [23]:
# Device configuration
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

device(type='cpu')

In [24]:
# Definition of the very simple network with 1 hidden layer
class SimpleScheduler(nn.Module):
    def __init__(self, input_n=126):
        # Invoke the parent's constructor
        super(SimpleScheduler, self).__init__()
        # nn implements feedworward layer as nn.Linear(a, b),
        # where a, b - input and output dims of weight matrix.
        # Bias is included by default.
        self.hidden = nn.Linear(input_n, 50)
        self.output = nn.Linear(50, 2)


    def forward(self, x):
        # You can write the result of sigmoid to a local variable,
        # but the common style in torch is to re-write x after computation of each layer
        x = F.relu(self.hidden(x))
        x = self.output(x)
        return x


model1 = SimpleScheduler().to(device)

print(f"SimpleScheduler model architecture:\n {model1}")
print("\n")

SimpleScheduler model architecture:
 SimpleScheduler(
  (hidden): Linear(in_features=126, out_features=50, bias=True)
  (output): Linear(in_features=50, out_features=2, bias=True)
)




In [25]:
# Set hyperparameters
# Number of iterations over the whole data set
epochs = 50
# Learning rate for Stochastic Gradient Descent
lr = 0.005
# SGD parameter to accelerate the optimization, check https://paperswithcode.com/method/sgd-with-momentum
momentum = 0.5
# Loss function - cross entropy, the multiclass variant of that you used in Lab 3
criterion = nn.HuberLoss()

In [26]:
from tqdm import tqdm

def train( model, device, train_loader, optimizer, epoch):
    # Do not forget to set train() to update weights of model
    model.train()
    # A wrapper over data loader to show progress bar
    bar = tqdm(train_loader)
    iteration = 0
    overall_loss = 0
    for data, target in bar:
        # Device of data and model must be the same
        data, target = data.to(device), target.to(device)
        # To avoid an accumulation of gradients
        optimizer.zero_grad()
        # Prediction
        output = model(data)
        # Error between prediction and ground truth
        loss = criterion(output, target)
        # Compute gradient
        loss.backward()
        # Update params of model
        optimizer.step()

        iteration += 1
        overall_loss += loss.item()
        bar.set_postfix({"Loss": format(overall_loss/iteration, '.6f')})

def test( model, device, test_loader):
    # Do not forget to set eval() to keep model's params the same
    model.eval()
    test_loss = 0
    correct = 0
    mse_loss = nn.MSELoss()
    mse_loss_val = 0
    ind = 0
    with torch.no_grad():
        for data, target in test_loader:
            # print(f"target shape is {target.shape}")
            data, target = data.to(device), target.to(device)
            output = model(data)
            # print(f"output shape is {output.shape}")
            # Sum up batch loss
            test_loss += F.cross_entropy(output, target, reduction='sum').item()
            mse_loss_val += mse_loss(output, target).item()
            # mse_loss += sum()
            # pred = output.argmax(dim=1, keepdim=True)  # get the index of the max log-probability
            # print(output.shape)
            # targ = target.argmax(dim=1, keepdim=True)  # get the index of the max log-probability
            # print(target, "\n", output)

            # correct += pred.eq(targ.view_as(pred)).sum().item()

    # test_loss /= len(test_loader.dataset)
    print(f"Test set: Average loss: {test_loss} mse loss: {mse_loss_val}")

In [27]:
# Train the model
optimizer = optim.Adam(model1.parameters(), lr=lr)

for epoch in range(1, epochs + 1):
    train(model1, device, dataloaders['train'], optimizer, epoch)
    test(model1, device, dataloaders['test'])

# Optionally, you can save the params of model to file
#torch.save(model.state_dict(), "mnist_model.pt")


100%|██████████| 208/208 [00:01<00:00, 192.84it/s, Loss=0.009354]


tensor([[0.0000, 0.1278]]) 
 tensor([[0.0044, 0.1361]])
tensor([[0.0521, 0.1722]]) 
 tensor([[0.0355, 0.2439]])
tensor([[0.0938, 0.1167]]) 
 tensor([[0.0959, 0.1439]])
tensor([[0.1459, 0.1778]]) 
 tensor([[0.1141, 0.2170]])
tensor([[0.1876, 0.1389]]) 
 tensor([[0.1825, 0.1625]])
tensor([[0.2502, 0.2250]]) 
 tensor([[0.1890, 0.2394]])
tensor([[0.3023, 0.1361]]) 
 tensor([[0.3086, 0.2075]])
tensor([[0.3336, 0.3028]]) 
 tensor([[0.3159, 0.2611]])
tensor([[0.4170, 0.0972]]) 
 tensor([[0.4099, 0.1824]])
tensor([[0.4587, 0.1750]]) 
 tensor([[0.4437, 0.1820]])
tensor([[0.5003, 0.1361]]) 
 tensor([[0.5286, 0.1494]])
tensor([[0.5525, 0.0500]]) 
 tensor([[0.5612, 0.1267]])
tensor([[0.5837, 0.1444]]) 
 tensor([[0.5535, 0.1064]])
tensor([[0.0000, 0.1306]]) 
 tensor([[0.0044, 0.1361]])
tensor([[0.0521, 0.3028]]) 
 tensor([[0.0343, 0.2479]])
tensor([[0.1251, 0.1250]]) 
 tensor([[0.1162, 0.1443]])
tensor([[0.1772, 0.1083]]) 
 tensor([[0.1499, 0.1301]])
tensor([[0.2189, 0.3000]]) 
 tensor([[0.1939, 0.

100%|██████████| 208/208 [00:00<00:00, 220.08it/s, Loss=0.001496]


tensor([[0.0000, 0.1278]]) 
 tensor([[0.0027, 0.1361]])
tensor([[0.0521, 0.1722]]) 
 tensor([[0.0311, 0.2388]])
tensor([[0.0938, 0.1167]]) 
 tensor([[0.0772, 0.1296]])
tensor([[0.1459, 0.1778]]) 
 tensor([[0.0924, 0.1999]])
tensor([[0.1876, 0.1389]]) 
 tensor([[0.1210, 0.1317]])
tensor([[0.2502, 0.2250]]) 
 tensor([[0.1448, 0.2178]])
tensor([[0.3023, 0.1361]]) 
 tensor([[0.2342, 0.2048]])
tensor([[0.3336, 0.3028]]) 
 tensor([[0.2453, 0.2720]])
tensor([[0.4170, 0.0972]]) 
 tensor([[0.3108, 0.1297]])
tensor([[0.4587, 0.1750]]) 
 tensor([[0.3499, 0.1623]])
tensor([[0.5003, 0.1361]]) 
 tensor([[0.4029, 0.1376]])
tensor([[0.5525, 0.0500]]) 
 tensor([[0.4322, 0.1144]])
tensor([[0.5837, 0.1444]]) 
 tensor([[0.4513, 0.1048]])
tensor([[0.0000, 0.1306]]) 
 tensor([[0.0027, 0.1361]])
tensor([[0.0521, 0.3028]]) 
 tensor([[0.0299, 0.2465]])
tensor([[0.1251, 0.1250]]) 
 tensor([[0.0895, 0.1270]])
tensor([[0.1772, 0.1083]]) 
 tensor([[0.1146, 0.1023]])
tensor([[0.2189, 0.3000]]) 
 tensor([[0.1729, 0.

100%|██████████| 208/208 [00:00<00:00, 229.82it/s, Loss=0.002345]


tensor([[0.0000, 0.1278]]) 
 tensor([[0.0059, 0.1307]])
tensor([[0.0521, 0.1722]]) 
 tensor([[0.0506, 0.2465]])
tensor([[0.0938, 0.1167]]) 
 tensor([[0.1303, 0.1406]])
tensor([[0.1459, 0.1778]]) 
 tensor([[0.1362, 0.2111]])
tensor([[0.1876, 0.1389]]) 
 tensor([[0.1987, 0.1620]])
tensor([[0.2502, 0.2250]]) 
 tensor([[0.2493, 0.2853]])
tensor([[0.3023, 0.1361]]) 
 tensor([[0.3310, 0.2644]])
tensor([[0.3336, 0.3028]]) 
 tensor([[0.3440, 0.3320]])
tensor([[0.4170, 0.0972]]) 
 tensor([[0.4215, 0.1908]])
tensor([[0.4587, 0.1750]]) 
 tensor([[0.4520, 0.2176]])
tensor([[0.5003, 0.1361]]) 
 tensor([[0.5337, 0.2270]])
tensor([[0.5525, 0.0500]]) 
 tensor([[0.5688, 0.2050]])
tensor([[0.5837, 0.1444]]) 
 tensor([[0.5786, 0.1860]])
tensor([[0.0000, 0.1306]]) 
 tensor([[0.0059, 0.1307]])
tensor([[0.0521, 0.3028]]) 
 tensor([[0.0467, 0.2560]])
tensor([[0.1251, 0.1250]]) 
 tensor([[0.1338, 0.1367]])
tensor([[0.1772, 0.1083]]) 
 tensor([[0.1577, 0.1267]])
tensor([[0.2189, 0.3000]]) 
 tensor([[0.1951, 0.

100%|██████████| 208/208 [00:00<00:00, 217.61it/s, Loss=0.002159]


tensor([[0.0000, 0.1278]]) 
 tensor([[-0.0100,  0.1330]])
tensor([[0.0521, 0.1722]]) 
 tensor([[0.0309, 0.2375]])
tensor([[0.0938, 0.1167]]) 
 tensor([[0.1170, 0.1506]])
tensor([[0.1459, 0.1778]]) 
 tensor([[0.0999, 0.1940]])
tensor([[0.1876, 0.1389]]) 
 tensor([[0.1483, 0.1396]])
tensor([[0.2502, 0.2250]]) 
 tensor([[0.1649, 0.2260]])
tensor([[0.3023, 0.1361]]) 
 tensor([[0.2409, 0.1937]])
tensor([[0.3336, 0.3028]]) 
 tensor([[0.2502, 0.2623]])
tensor([[0.4170, 0.0972]]) 
 tensor([[0.3451, 0.1321]])
tensor([[0.4587, 0.1750]]) 
 tensor([[0.3771, 0.1591]])
tensor([[0.5003, 0.1361]]) 
 tensor([[0.4213, 0.1694]])
tensor([[0.5525, 0.0500]]) 
 tensor([[0.4631, 0.1558]])
tensor([[0.5837, 0.1444]]) 
 tensor([[0.5004, 0.1486]])
tensor([[0.0000, 0.1306]]) 
 tensor([[-0.0100,  0.1330]])
tensor([[0.0521, 0.3028]]) 
 tensor([[0.0279, 0.2464]])
tensor([[0.1251, 0.1250]]) 
 tensor([[0.1233, 0.1481]])
tensor([[0.1772, 0.1083]]) 
 tensor([[0.1663, 0.1335]])
tensor([[0.2189, 0.3000]]) 
 tensor([[0.1597

100%|██████████| 208/208 [00:00<00:00, 227.43it/s, Loss=0.002019]


tensor([[0.0000, 0.1278]]) 
 tensor([[-0.0069,  0.1375]])
tensor([[0.0521, 0.1722]]) 
 tensor([[0.0514, 0.2272]])
tensor([[0.0938, 0.1167]]) 
 tensor([[0.1285, 0.1448]])
tensor([[0.1459, 0.1778]]) 
 tensor([[0.1388, 0.1695]])
tensor([[0.1876, 0.1389]]) 
 tensor([[0.1712, 0.1169]])
tensor([[0.2502, 0.2250]]) 
 tensor([[0.1914, 0.1943]])
tensor([[0.3023, 0.1361]]) 
 tensor([[0.2686, 0.1467]])
tensor([[0.3336, 0.3028]]) 
 tensor([[0.2824, 0.2201]])
tensor([[0.4170, 0.0972]]) 
 tensor([[0.3663, 0.0626]])
tensor([[0.4587, 0.1750]]) 
 tensor([[0.4050, 0.1082]])
tensor([[0.5003, 0.1361]]) 
 tensor([[0.4509, 0.0807]])
tensor([[0.5525, 0.0500]]) 
 tensor([[0.4905, 0.0615]])
tensor([[0.5837, 0.1444]]) 
 tensor([[0.5241, 0.0525]])
tensor([[0.0000, 0.1306]]) 
 tensor([[-0.0069,  0.1375]])
tensor([[0.0521, 0.3028]]) 
 tensor([[0.0460, 0.2383]])
tensor([[0.1251, 0.1250]]) 
 tensor([[0.1399, 0.1298]])
tensor([[0.1772, 0.1083]]) 
 tensor([[0.1674, 0.1184]])
tensor([[0.2189, 0.3000]]) 
 tensor([[0.1637

100%|██████████| 208/208 [00:00<00:00, 236.90it/s, Loss=0.002347]


tensor([[0.0000, 0.1278]]) 
 tensor([[-0.0350,  0.1288]])
tensor([[0.0521, 0.1722]]) 
 tensor([[0.0249, 0.2431]])
tensor([[0.0938, 0.1167]]) 
 tensor([[0.1384, 0.1980]])
tensor([[0.1459, 0.1778]]) 
 tensor([[0.1439, 0.2170]])
tensor([[0.1876, 0.1389]]) 
 tensor([[0.1863, 0.1682]])
tensor([[0.2502, 0.2250]]) 
 tensor([[0.2189, 0.2382]])
tensor([[0.3023, 0.1361]]) 
 tensor([[0.2940, 0.2291]])
tensor([[0.3336, 0.3028]]) 
 tensor([[0.2998, 0.2694]])
tensor([[0.4170, 0.0972]]) 
 tensor([[0.4020, 0.1384]])
tensor([[0.4587, 0.1750]]) 
 tensor([[0.4339, 0.1770]])
tensor([[0.5003, 0.1361]]) 
 tensor([[0.4841, 0.1660]])
tensor([[0.5525, 0.0500]]) 
 tensor([[0.5240, 0.1407]])
tensor([[0.5837, 0.1444]]) 
 tensor([[0.5574, 0.1336]])
tensor([[0.0000, 0.1306]]) 
 tensor([[-0.0350,  0.1288]])
tensor([[0.0521, 0.3028]]) 
 tensor([[0.0159, 0.2520]])
tensor([[0.1251, 0.1250]]) 
 tensor([[0.1836, 0.1624]])
tensor([[0.1772, 0.1083]]) 
 tensor([[0.1836, 0.1624]])
tensor([[0.2189, 0.3000]]) 
 tensor([[0.1816

100%|██████████| 208/208 [00:00<00:00, 237.46it/s, Loss=0.001919]


tensor([[0.0000, 0.1278]]) 
 tensor([[-0.0341,  0.1338]])
tensor([[0.0521, 0.1722]]) 
 tensor([[0.0202, 0.2451]])
tensor([[0.0938, 0.1167]]) 
 tensor([[0.1160, 0.2115]])
tensor([[0.1459, 0.1778]]) 
 tensor([[0.1289, 0.2201]])
tensor([[0.1876, 0.1389]]) 
 tensor([[0.1944, 0.1525]])
tensor([[0.2502, 0.2250]]) 
 tensor([[0.2112, 0.2501]])
tensor([[0.3023, 0.1361]]) 
 tensor([[0.3100, 0.2331]])
tensor([[0.3336, 0.3028]]) 
 tensor([[0.3227, 0.2803]])
tensor([[0.4170, 0.0972]]) 
 tensor([[0.4179, 0.1246]])
tensor([[0.4587, 0.1750]]) 
 tensor([[0.4522, 0.1747]])
tensor([[0.5003, 0.1361]]) 
 tensor([[0.5153, 0.1622]])
tensor([[0.5525, 0.0500]]) 
 tensor([[0.5557, 0.1359]])
tensor([[0.5837, 0.1444]]) 
 tensor([[0.5803, 0.1307]])
tensor([[0.0000, 0.1306]]) 
 tensor([[-0.0341,  0.1338]])
tensor([[0.0521, 0.3028]]) 
 tensor([[0.0107, 0.2558]])
tensor([[0.1251, 0.1250]]) 
 tensor([[0.1874, 0.1577]])
tensor([[0.1772, 0.1083]]) 
 tensor([[0.1944, 0.1525]])
tensor([[0.2189, 0.3000]]) 
 tensor([[0.1689

100%|██████████| 208/208 [00:00<00:00, 213.06it/s, Loss=0.002136]


tensor([[0.0000, 0.1278]]) 
 tensor([[-0.0349,  0.1307]])
tensor([[0.0521, 0.1722]]) 
 tensor([[0.0173, 0.2528]])
tensor([[0.0938, 0.1167]]) 
 tensor([[0.1051, 0.2245]])
tensor([[0.1459, 0.1778]]) 
 tensor([[0.1267, 0.2376]])
tensor([[0.1876, 0.1389]]) 
 tensor([[0.2005, 0.1544]])
tensor([[0.2502, 0.2250]]) 
 tensor([[0.2301, 0.2533]])
tensor([[0.3023, 0.1361]]) 
 tensor([[0.3552, 0.2461]])
tensor([[0.3336, 0.3028]]) 
 tensor([[0.3723, 0.2987]])
tensor([[0.4170, 0.0972]]) 
 tensor([[0.4798, 0.1409]])
tensor([[0.4587, 0.1750]]) 
 tensor([[0.5108, 0.1967]])
tensor([[0.5003, 0.1361]]) 
 tensor([[0.5915, 0.1860]])
tensor([[0.5525, 0.0500]]) 
 tensor([[0.6335, 0.1613]])
tensor([[0.5837, 0.1444]]) 
 tensor([[0.6422, 0.1562]])
tensor([[0.0000, 0.1306]]) 
 tensor([[-0.0349,  0.1307]])
tensor([[0.0521, 0.3028]]) 
 tensor([[0.0063, 0.2650]])
tensor([[0.1251, 0.1250]]) 
 tensor([[0.1729, 0.1746]])
tensor([[0.1772, 0.1083]]) 
 tensor([[0.2005, 0.1544]])
tensor([[0.2189, 0.3000]]) 
 tensor([[0.1705

100%|██████████| 208/208 [00:00<00:00, 225.54it/s, Loss=0.002060]


tensor([[0.0000, 0.1278]]) 
 tensor([[-0.0345,  0.1368]])
tensor([[0.0521, 0.1722]]) 
 tensor([[0.0299, 0.2437]])
tensor([[0.0938, 0.1167]]) 
 tensor([[0.0794, 0.2105]])
tensor([[0.1459, 0.1778]]) 
 tensor([[0.1082, 0.2232]])
tensor([[0.1876, 0.1389]]) 
 tensor([[0.2202, 0.1334]])
tensor([[0.2502, 0.2250]]) 
 tensor([[0.2443, 0.2441]])
tensor([[0.3023, 0.1361]]) 
 tensor([[0.3558, 0.2283]])
tensor([[0.3336, 0.3028]]) 
 tensor([[0.3773, 0.2991]])
tensor([[0.4170, 0.0972]]) 
 tensor([[0.4781, 0.1264]])
tensor([[0.4587, 0.1750]]) 
 tensor([[0.5103, 0.1801]])
tensor([[0.5003, 0.1361]]) 
 tensor([[0.5971, 0.1702]])
tensor([[0.5525, 0.0500]]) 
 tensor([[0.6388, 0.1404]])
tensor([[0.5837, 0.1444]]) 
 tensor([[0.6519, 0.1321]])
tensor([[0.0000, 0.1306]]) 
 tensor([[-0.0345,  0.1368]])
tensor([[0.0521, 0.3028]]) 
 tensor([[0.0169, 0.2596]])
tensor([[0.1251, 0.1250]]) 
 tensor([[0.1279, 0.1839]])
tensor([[0.1772, 0.1083]]) 
 tensor([[0.2045, 0.1420]])
tensor([[0.2189, 0.3000]]) 
 tensor([[0.1707

100%|██████████| 208/208 [00:00<00:00, 226.48it/s, Loss=0.001615]


tensor([[0.0000, 0.1278]]) 
 tensor([[-0.0188,  0.1347]])
tensor([[0.0521, 0.1722]]) 
 tensor([[0.0319, 0.2407]])
tensor([[0.0938, 0.1167]]) 
 tensor([[0.0997, 0.1642]])
tensor([[0.1459, 0.1778]]) 
 tensor([[0.1402, 0.1890]])
tensor([[0.1876, 0.1389]]) 
 tensor([[0.2311, 0.1232]])
tensor([[0.2502, 0.2250]]) 
 tensor([[0.2517, 0.2273]])
tensor([[0.3023, 0.1361]]) 
 tensor([[0.3374, 0.1992]])
tensor([[0.3336, 0.3028]]) 
 tensor([[0.3617, 0.2734]])
tensor([[0.4170, 0.0972]]) 
 tensor([[0.4671, 0.1186]])
tensor([[0.4587, 0.1750]]) 
 tensor([[0.4952, 0.1586]])
tensor([[0.5003, 0.1361]]) 
 tensor([[0.5736, 0.1411]])
tensor([[0.5525, 0.0500]]) 
 tensor([[0.6174, 0.1157]])
tensor([[0.5837, 0.1444]]) 
 tensor([[0.6394, 0.1153]])
tensor([[0.0000, 0.1306]]) 
 tensor([[-0.0188,  0.1347]])
tensor([[0.0521, 0.3028]]) 
 tensor([[0.0166, 0.2586]])
tensor([[0.1251, 0.1250]]) 
 tensor([[0.1254, 0.1561]])
tensor([[0.1772, 0.1083]]) 
 tensor([[0.1966, 0.1339]])
tensor([[0.2189, 0.3000]]) 
 tensor([[0.2016

100%|██████████| 208/208 [00:00<00:00, 237.96it/s, Loss=0.001632]


tensor([[0.0000, 0.1278]]) 
 tensor([[0.0107, 0.1293]])
tensor([[0.0521, 0.1722]]) 
 tensor([[0.0611, 0.2369]])
tensor([[0.0938, 0.1167]]) 
 tensor([[0.1529, 0.1376]])
tensor([[0.1459, 0.1778]]) 
 tensor([[0.1919, 0.1796]])
tensor([[0.1876, 0.1389]]) 
 tensor([[0.2273, 0.1287]])
tensor([[0.2502, 0.2250]]) 
 tensor([[0.2849, 0.2343]])
tensor([[0.3023, 0.1361]]) 
 tensor([[0.3522, 0.2024]])
tensor([[0.3336, 0.3028]]) 
 tensor([[0.3716, 0.2801]])
tensor([[0.4170, 0.0972]]) 
 tensor([[0.4876, 0.1149]])
tensor([[0.4587, 0.1750]]) 
 tensor([[0.5185, 0.1703]])
tensor([[0.5003, 0.1361]]) 
 tensor([[0.6019, 0.1568]])
tensor([[0.5525, 0.0500]]) 
 tensor([[0.6489, 0.1231]])
tensor([[0.5837, 0.1444]]) 
 tensor([[0.6727, 0.1075]])
tensor([[0.0000, 0.1306]]) 
 tensor([[0.0107, 0.1293]])
tensor([[0.0521, 0.3028]]) 
 tensor([[0.0468, 0.2517]])
tensor([[0.1251, 0.1250]]) 
 tensor([[0.1699, 0.1355]])
tensor([[0.1772, 0.1083]]) 
 tensor([[0.2016, 0.1318]])
tensor([[0.2189, 0.3000]]) 
 tensor([[0.2269, 0.

100%|██████████| 208/208 [00:00<00:00, 214.10it/s, Loss=0.001476]


tensor([[0.0000, 0.1278]]) 
 tensor([[0.0284, 0.1256]])
tensor([[0.0521, 0.1722]]) 
 tensor([[0.0725, 0.2301]])
tensor([[0.0938, 0.1167]]) 
 tensor([[0.1573, 0.1138]])
tensor([[0.1459, 0.1778]]) 
 tensor([[0.1976, 0.1844]])
tensor([[0.1876, 0.1389]]) 
 tensor([[0.2361, 0.1239]])
tensor([[0.2502, 0.2250]]) 
 tensor([[0.3054, 0.2502]])
tensor([[0.3023, 0.1361]]) 
 tensor([[0.3753, 0.2185]])
tensor([[0.3336, 0.3028]]) 
 tensor([[0.3865, 0.2978]])
tensor([[0.4170, 0.0972]]) 
 tensor([[0.5051, 0.1241]])
tensor([[0.4587, 0.1750]]) 
 tensor([[0.5324, 0.1955]])
tensor([[0.5003, 0.1361]]) 
 tensor([[0.6113, 0.1811]])
tensor([[0.5525, 0.0500]]) 
 tensor([[0.6626, 0.1504]])
tensor([[0.5837, 0.1444]]) 
 tensor([[0.6930, 0.1360]])
tensor([[0.0000, 0.1306]]) 
 tensor([[0.0284, 0.1256]])
tensor([[0.0521, 0.3028]]) 
 tensor([[0.0530, 0.2443]])
tensor([[0.1251, 0.1250]]) 
 tensor([[0.1579, 0.1138]])
tensor([[0.1772, 0.1083]]) 
 tensor([[0.1909, 0.1181]])
tensor([[0.2189, 0.3000]]) 
 tensor([[0.2320, 0.

100%|██████████| 208/208 [00:00<00:00, 212.97it/s, Loss=0.001884]


tensor([[0.0000, 0.1278]]) 
 tensor([[0.0016, 0.1305]])
tensor([[0.0521, 0.1722]]) 
 tensor([[0.0692, 0.2255]])
tensor([[0.0938, 0.1167]]) 
 tensor([[0.1058, 0.1385]])
tensor([[0.1459, 0.1778]]) 
 tensor([[0.1337, 0.1791]])
tensor([[0.1876, 0.1389]]) 
 tensor([[0.2187, 0.1228]])
tensor([[0.2502, 0.2250]]) 
 tensor([[0.2703, 0.2226]])
tensor([[0.3023, 0.1361]]) 
 tensor([[0.3026, 0.1822]])
tensor([[0.3336, 0.3028]]) 
 tensor([[0.3353, 0.2590]])
tensor([[0.4170, 0.0972]]) 
 tensor([[0.4446, 0.1154]])
tensor([[0.4587, 0.1750]]) 
 tensor([[0.4782, 0.1615]])
tensor([[0.5003, 0.1361]]) 
 tensor([[0.5329, 0.1290]])
tensor([[0.5525, 0.0500]]) 
 tensor([[0.5830, 0.1112]])
tensor([[0.5837, 0.1444]]) 
 tensor([[0.6228, 0.1100]])
tensor([[0.0000, 0.1306]]) 
 tensor([[0.0016, 0.1305]])
tensor([[0.0521, 0.3028]]) 
 tensor([[0.0536, 0.2442]])
tensor([[0.1251, 0.1250]]) 
 tensor([[0.1545, 0.1261]])
tensor([[0.1772, 0.1083]]) 
 tensor([[0.1897, 0.1243]])
tensor([[0.2189, 0.3000]]) 
 tensor([[0.2337, 0.

100%|██████████| 208/208 [00:00<00:00, 232.56it/s, Loss=0.001263]


tensor([[0.0000, 0.1278]]) 
 tensor([[-0.0261,  0.1296]])
tensor([[0.0521, 0.1722]]) 
 tensor([[-0.0061,  0.2386]])
tensor([[0.0938, 0.1167]]) 
 tensor([[-0.0057,  0.1212]])
tensor([[0.1459, 0.1778]]) 
 tensor([[0.0437, 0.1700]])
tensor([[0.1876, 0.1389]]) 
 tensor([[0.0967, 0.1091]])
tensor([[0.2502, 0.2250]]) 
 tensor([[0.1843, 0.2348]])
tensor([[0.3023, 0.1361]]) 
 tensor([[0.2982, 0.1925]])
tensor([[0.3336, 0.3028]]) 
 tensor([[0.2888, 0.2742]])
tensor([[0.4170, 0.0972]]) 
 tensor([[0.4636, 0.1193]])
tensor([[0.4587, 0.1750]]) 
 tensor([[0.4913, 0.1829]])
tensor([[0.5003, 0.1361]]) 
 tensor([[0.5502, 0.1533]])
tensor([[0.5525, 0.0500]]) 
 tensor([[0.5964, 0.1199]])
tensor([[0.5837, 0.1444]]) 
 tensor([[0.6265, 0.1124]])
tensor([[0.0000, 0.1306]]) 
 tensor([[-0.0261,  0.1296]])
tensor([[0.0521, 0.3028]]) 
 tensor([[-0.0277,  0.2577]])
tensor([[0.1251, 0.1250]]) 
 tensor([[0.0515, 0.1060]])
tensor([[0.1772, 0.1083]]) 
 tensor([[0.0931, 0.1087]])
tensor([[0.2189, 0.3000]]) 
 tensor([[

100%|██████████| 208/208 [00:00<00:00, 235.53it/s, Loss=0.001539]


tensor([[0.0000, 0.1278]]) 
 tensor([[-0.0001,  0.1268]])
tensor([[0.0521, 0.1722]]) 
 tensor([[0.0326, 0.2364]])
tensor([[0.0938, 0.1167]]) 
 tensor([[0.0572, 0.1121]])
tensor([[0.1459, 0.1778]]) 
 tensor([[0.1108, 0.1681]])
tensor([[0.1876, 0.1389]]) 
 tensor([[0.1731, 0.1045]])
tensor([[0.2502, 0.2250]]) 
 tensor([[0.2577, 0.2558]])
tensor([[0.3023, 0.1361]]) 
 tensor([[0.3288, 0.2110]])
tensor([[0.3336, 0.3028]]) 
 tensor([[0.3303, 0.2958]])
tensor([[0.4170, 0.0972]]) 
 tensor([[0.4738, 0.1316]])
tensor([[0.4587, 0.1750]]) 
 tensor([[0.4943, 0.2020]])
tensor([[0.5003, 0.1361]]) 
 tensor([[0.5605, 0.1705]])
tensor([[0.5525, 0.0500]]) 
 tensor([[0.6142, 0.1390]])
tensor([[0.5837, 0.1444]]) 
 tensor([[0.6448, 0.1209]])
tensor([[0.0000, 0.1306]]) 
 tensor([[-0.0001,  0.1268]])
tensor([[0.0521, 0.3028]]) 
 tensor([[0.0072, 0.2548]])
tensor([[0.1251, 0.1250]]) 
 tensor([[0.0887, 0.1036]])
tensor([[0.1772, 0.1083]]) 
 tensor([[0.1306, 0.0907]])
tensor([[0.2189, 0.3000]]) 
 tensor([[0.2056

100%|██████████| 208/208 [00:00<00:00, 227.77it/s, Loss=0.001229]


tensor([[0.0000, 0.1278]]) 
 tensor([[-0.0251,  0.1302]])
tensor([[0.0521, 0.1722]]) 
 tensor([[-0.0122,  0.2440]])
tensor([[0.0938, 0.1167]]) 
 tensor([[0.0060, 0.1277]])
tensor([[0.1459, 0.1778]]) 
 tensor([[0.0674, 0.1793]])
tensor([[0.1876, 0.1389]]) 
 tensor([[0.1401, 0.1027]])
tensor([[0.2502, 0.2250]]) 
 tensor([[0.2022, 0.2276]])
tensor([[0.3023, 0.1361]]) 
 tensor([[0.2822, 0.1822]])
tensor([[0.3336, 0.3028]]) 
 tensor([[0.2847, 0.2671]])
tensor([[0.4170, 0.0972]]) 
 tensor([[0.4522, 0.1239]])
tensor([[0.4587, 0.1750]]) 
 tensor([[0.4717, 0.1936]])
tensor([[0.5003, 0.1361]]) 
 tensor([[0.5334, 0.1570]])
tensor([[0.5525, 0.0500]]) 
 tensor([[0.5905, 0.1247]])
tensor([[0.5837, 0.1444]]) 
 tensor([[0.6248, 0.1217]])
tensor([[0.0000, 0.1306]]) 
 tensor([[-0.0251,  0.1302]])
tensor([[0.0521, 0.3028]]) 
 tensor([[-0.0411,  0.2639]])
tensor([[0.1251, 0.1250]]) 
 tensor([[0.0268, 0.1196]])
tensor([[0.1772, 0.1083]]) 
 tensor([[0.1041, 0.0936]])
tensor([[0.2189, 0.3000]]) 
 tensor([[0.

100%|██████████| 208/208 [00:00<00:00, 240.73it/s, Loss=0.001292]


tensor([[0.0000, 0.1278]]) 
 tensor([[-0.0169,  0.1294]])
tensor([[0.0521, 0.1722]]) 
 tensor([[0.0133, 0.2438]])
tensor([[0.0938, 0.1167]]) 
 tensor([[0.0403, 0.1171]])
tensor([[0.1459, 0.1778]]) 
 tensor([[0.0998, 0.1773]])
tensor([[0.1876, 0.1389]]) 
 tensor([[0.1715, 0.0992]])
tensor([[0.2502, 0.2250]]) 
 tensor([[0.2452, 0.2451]])
tensor([[0.3023, 0.1361]]) 
 tensor([[0.3240, 0.1931]])
tensor([[0.3336, 0.3028]]) 
 tensor([[0.3368, 0.2885]])
tensor([[0.4170, 0.0972]]) 
 tensor([[0.4583, 0.1315]])
tensor([[0.4587, 0.1750]]) 
 tensor([[0.4761, 0.2072]])
tensor([[0.5003, 0.1361]]) 
 tensor([[0.5379, 0.1681]])
tensor([[0.5525, 0.0500]]) 
 tensor([[0.5941, 0.1349]])
tensor([[0.5837, 0.1444]]) 
 tensor([[0.6234, 0.1291]])
tensor([[0.0000, 0.1306]]) 
 tensor([[-0.0169,  0.1294]])
tensor([[0.0521, 0.3028]]) 
 tensor([[-0.0162,  0.2649]])
tensor([[0.1251, 0.1250]]) 
 tensor([[0.0525, 0.1073]])
tensor([[0.1772, 0.1083]]) 
 tensor([[0.1246, 0.0811]])
tensor([[0.2189, 0.3000]]) 
 tensor([[0.20

100%|██████████| 208/208 [00:00<00:00, 229.97it/s, Loss=0.001470]


tensor([[0.0000, 0.1278]]) 
 tensor([[-0.0101,  0.1286]])
tensor([[0.0521, 0.1722]]) 
 tensor([[0.0152, 0.2474]])
tensor([[0.0938, 0.1167]]) 
 tensor([[0.0359, 0.1249]])
tensor([[0.1459, 0.1778]]) 
 tensor([[0.1027, 0.1817]])
tensor([[0.1876, 0.1389]]) 
 tensor([[0.1765, 0.1059]])
tensor([[0.2502, 0.2250]]) 
 tensor([[0.2605, 0.2418]])
tensor([[0.3023, 0.1361]]) 
 tensor([[0.3337, 0.1876]])
tensor([[0.3336, 0.3028]]) 
 tensor([[0.3467, 0.2785]])
tensor([[0.4170, 0.0972]]) 
 tensor([[0.4724, 0.1448]])
tensor([[0.4587, 0.1750]]) 
 tensor([[0.4928, 0.2011]])
tensor([[0.5003, 0.1361]]) 
 tensor([[0.5680, 0.1552]])
tensor([[0.5525, 0.0500]]) 
 tensor([[0.6283, 0.1364]])
tensor([[0.5837, 0.1444]]) 
 tensor([[0.6528, 0.1350]])
tensor([[0.0000, 0.1306]]) 
 tensor([[-0.0101,  0.1286]])
tensor([[0.0521, 0.3028]]) 
 tensor([[-0.0156,  0.2689]])
tensor([[0.1251, 0.1250]]) 
 tensor([[0.0452, 0.1121]])
tensor([[0.1772, 0.1083]]) 
 tensor([[0.1224, 0.0858]])
tensor([[0.2189, 0.3000]]) 
 tensor([[0.20

100%|██████████| 208/208 [00:00<00:00, 229.13it/s, Loss=0.001260]


tensor([[0.0000, 0.1278]]) 
 tensor([[-0.0190,  0.1336]])
tensor([[0.0521, 0.1722]]) 
 tensor([[0.0019, 0.2481]])
tensor([[0.0938, 0.1167]]) 
 tensor([[0.0381, 0.1323]])
tensor([[0.1459, 0.1778]]) 
 tensor([[0.0980, 0.1903]])
tensor([[0.1876, 0.1389]]) 
 tensor([[0.1764, 0.1101]])
tensor([[0.2502, 0.2250]]) 
 tensor([[0.2326, 0.2399]])
tensor([[0.3023, 0.1361]]) 
 tensor([[0.3091, 0.1862]])
tensor([[0.3336, 0.3028]]) 
 tensor([[0.3186, 0.2793]])
tensor([[0.4170, 0.0972]]) 
 tensor([[0.4613, 0.1404]])
tensor([[0.4587, 0.1750]]) 
 tensor([[0.4767, 0.2087]])
tensor([[0.5003, 0.1361]]) 
 tensor([[0.5455, 0.1544]])
tensor([[0.5525, 0.0500]]) 
 tensor([[0.6079, 0.1297]])
tensor([[0.5837, 0.1444]]) 
 tensor([[0.6370, 0.1276]])
tensor([[0.0000, 0.1306]]) 
 tensor([[-0.0190,  0.1336]])
tensor([[0.0521, 0.3028]]) 
 tensor([[-0.0307,  0.2705]])
tensor([[0.1251, 0.1250]]) 
 tensor([[0.0485, 0.1207]])
tensor([[0.1772, 0.1083]]) 
 tensor([[0.1310, 0.0946]])
tensor([[0.2189, 0.3000]]) 
 tensor([[0.19

100%|██████████| 208/208 [00:01<00:00, 127.51it/s, Loss=0.001147]


tensor([[0.0000, 0.1278]]) 
 tensor([[-0.0171,  0.1322]])
tensor([[0.0521, 0.1722]]) 
 tensor([[2.2313e-04, 2.4953e-01]])
tensor([[0.0938, 0.1167]]) 
 tensor([[0.0322, 0.1190]])
tensor([[0.1459, 0.1778]]) 
 tensor([[0.0957, 0.1732]])
tensor([[0.1876, 0.1389]]) 
 tensor([[0.1651, 0.0940]])
tensor([[0.2502, 0.2250]]) 
 tensor([[0.2200, 0.2119]])
tensor([[0.3023, 0.1361]]) 
 tensor([[0.2888, 0.1597]])
tensor([[0.3336, 0.3028]]) 
 tensor([[0.3254, 0.2624]])
tensor([[0.4170, 0.0972]]) 
 tensor([[0.4525, 0.1470]])
tensor([[0.4587, 0.1750]]) 
 tensor([[0.4743, 0.2061]])
tensor([[0.5003, 0.1361]]) 
 tensor([[0.5381, 0.1447]])
tensor([[0.5525, 0.0500]]) 
 tensor([[0.5982, 0.1431]])
tensor([[0.5837, 0.1444]]) 
 tensor([[0.6273, 0.1423]])
tensor([[0.0000, 0.1306]]) 
 tensor([[-0.0171,  0.1322]])
tensor([[0.0521, 0.3028]]) 
 tensor([[-0.0331,  0.2731]])
tensor([[0.1251, 0.1250]]) 
 tensor([[0.0350, 0.1076]])
tensor([[0.1772, 0.1083]]) 
 tensor([[0.1241, 0.0783]])
tensor([[0.2189, 0.3000]]) 
 tenso

100%|██████████| 208/208 [00:02<00:00, 99.44it/s, Loss=0.001409] 


tensor([[0.0000, 0.1278]]) 
 tensor([[-0.0155,  0.1324]])
tensor([[0.0521, 0.1722]]) 
 tensor([[0.0010, 0.2523]])
tensor([[0.0938, 0.1167]]) 
 tensor([[0.0451, 0.1169]])
tensor([[0.1459, 0.1778]]) 
 tensor([[0.1094, 0.1751]])
tensor([[0.1876, 0.1389]]) 
 tensor([[0.1806, 0.0945]])
tensor([[0.2502, 0.2250]]) 
 tensor([[0.2515, 0.2156]])
tensor([[0.3023, 0.1361]]) 
 tensor([[0.3296, 0.1582]])
tensor([[0.3336, 0.3028]]) 
 tensor([[0.3398, 0.2596]])
tensor([[0.4170, 0.0972]]) 
 tensor([[0.4621, 0.1475]])
tensor([[0.4587, 0.1750]]) 
 tensor([[0.4890, 0.1879]])
tensor([[0.5003, 0.1361]]) 
 tensor([[0.5545, 0.1440]])
tensor([[0.5525, 0.0500]]) 
 tensor([[0.6156, 0.1418]])
tensor([[0.5837, 0.1444]]) 
 tensor([[0.6426, 0.1407]])
tensor([[0.0000, 0.1306]]) 
 tensor([[-0.0155,  0.1324]])
tensor([[0.0521, 0.3028]]) 
 tensor([[-0.0334,  0.2777]])
tensor([[0.1251, 0.1250]]) 
 tensor([[0.0401, 0.1056]])
tensor([[0.1772, 0.1083]]) 
 tensor([[0.1350, 0.0768]])
tensor([[0.2189, 0.3000]]) 
 tensor([[0.21

100%|██████████| 208/208 [00:01<00:00, 175.18it/s, Loss=0.001253]


tensor([[0.0000, 0.1278]]) 
 tensor([[-0.0086,  0.1330]])
tensor([[0.0521, 0.1722]]) 
 tensor([[0.0180, 0.2485]])
tensor([[0.0938, 0.1167]]) 
 tensor([[0.0700, 0.1162]])
tensor([[0.1459, 0.1778]]) 
 tensor([[0.1378, 0.1726]])
tensor([[0.1876, 0.1389]]) 
 tensor([[0.1980, 0.0964]])
tensor([[0.2502, 0.2250]]) 
 tensor([[0.2707, 0.2158]])
tensor([[0.3023, 0.1361]]) 
 tensor([[0.3258, 0.1467]])
tensor([[0.3336, 0.3028]]) 
 tensor([[0.3382, 0.2537]])
tensor([[0.4170, 0.0972]]) 
 tensor([[0.4554, 0.1438]])
tensor([[0.4587, 0.1750]]) 
 tensor([[0.4840, 0.1941]])
tensor([[0.5003, 0.1361]]) 
 tensor([[0.5413, 0.1436]])
tensor([[0.5525, 0.0500]]) 
 tensor([[0.6029, 0.1434]])
tensor([[0.5837, 0.1444]]) 
 tensor([[0.6337, 0.1434]])
tensor([[0.0000, 0.1306]]) 
 tensor([[-0.0086,  0.1330]])
tensor([[0.0521, 0.3028]]) 
 tensor([[-0.0146,  0.2758]])
tensor([[0.1251, 0.1250]]) 
 tensor([[0.0689, 0.1069]])
tensor([[0.1772, 0.1083]]) 
 tensor([[0.1550, 0.0804]])
tensor([[0.2189, 0.3000]]) 
 tensor([[0.23

100%|██████████| 208/208 [00:00<00:00, 236.35it/s, Loss=0.001197]


tensor([[0.0000, 0.1278]]) 
 tensor([[-0.0234,  0.1374]])
tensor([[0.0521, 0.1722]]) 
 tensor([[0.0104, 0.2591]])
tensor([[0.0938, 0.1167]]) 
 tensor([[0.0767, 0.1209]])
tensor([[0.1459, 0.1778]]) 
 tensor([[0.1381, 0.2037]])
tensor([[0.1876, 0.1389]]) 
 tensor([[0.2020, 0.1067]])
tensor([[0.2502, 0.2250]]) 
 tensor([[0.2649, 0.2774]])
tensor([[0.3023, 0.1361]]) 
 tensor([[0.3127, 0.2141]])
tensor([[0.3336, 0.3028]]) 
 tensor([[0.3092, 0.3262]])
tensor([[0.4170, 0.0972]]) 
 tensor([[0.4151, 0.1308]])
tensor([[0.4587, 0.1750]]) 
 tensor([[0.4384, 0.2444]])
tensor([[0.5003, 0.1361]]) 
 tensor([[0.4815, 0.1664]])
tensor([[0.5525, 0.0500]]) 
 tensor([[0.5428, 0.1366]])
tensor([[0.5837, 0.1444]]) 
 tensor([[0.5778, 0.1843]])
tensor([[0.0000, 0.1306]]) 
 tensor([[-0.0234,  0.1374]])
tensor([[0.0521, 0.3028]]) 
 tensor([[-0.0230,  0.2863]])
tensor([[0.1251, 0.1250]]) 
 tensor([[0.0818, 0.1123]])
tensor([[0.1772, 0.1083]]) 
 tensor([[0.1644, 0.0901]])
tensor([[0.2189, 0.3000]]) 
 tensor([[0.22

100%|██████████| 208/208 [00:00<00:00, 243.71it/s, Loss=0.001672]


tensor([[0.0000, 0.1278]]) 
 tensor([[-0.0044,  0.1319]])
tensor([[0.0521, 0.1722]]) 
 tensor([[0.0451, 0.2365]])
tensor([[0.0938, 0.1167]]) 
 tensor([[0.1138, 0.1132]])
tensor([[0.1459, 0.1778]]) 
 tensor([[0.1846, 0.1608]])
tensor([[0.1876, 0.1389]]) 
 tensor([[0.2353, 0.1011]])
tensor([[0.2502, 0.2250]]) 
 tensor([[0.2970, 0.1963]])
tensor([[0.3023, 0.1361]]) 
 tensor([[0.3640, 0.1434]])
tensor([[0.3336, 0.3028]]) 
 tensor([[0.3584, 0.2273]])
tensor([[0.4170, 0.0972]]) 
 tensor([[0.4391, 0.1465]])
tensor([[0.4587, 0.1750]]) 
 tensor([[0.4585, 0.1701]])
tensor([[0.5003, 0.1361]]) 
 tensor([[0.5058, 0.1492]])
tensor([[0.5525, 0.0500]]) 
 tensor([[0.5522, 0.1511]])
tensor([[0.5837, 0.1444]]) 
 tensor([[0.5715, 0.1519]])
tensor([[0.0000, 0.1306]]) 
 tensor([[-0.0044,  0.1319]])
tensor([[0.0521, 0.3028]]) 
 tensor([[0.0100, 0.2616]])
tensor([[0.1251, 0.1250]]) 
 tensor([[0.1259, 0.1028]])
tensor([[0.1772, 0.1083]]) 
 tensor([[0.1900, 0.0862]])
tensor([[0.2189, 0.3000]]) 
 tensor([[0.2470

100%|██████████| 208/208 [00:00<00:00, 218.88it/s, Loss=0.002150]


tensor([[0.0000, 0.1278]]) 
 tensor([[-0.0076,  0.1340]])
tensor([[0.0521, 0.1722]]) 
 tensor([[0.0220, 0.2508]])
tensor([[0.0938, 0.1167]]) 
 tensor([[0.0933, 0.1271]])
tensor([[0.1459, 0.1778]]) 
 tensor([[0.1312, 0.1707]])
tensor([[0.1876, 0.1389]]) 
 tensor([[0.1498, 0.1030]])
tensor([[0.2502, 0.2250]]) 
 tensor([[0.1699, 0.1878]])
tensor([[0.3023, 0.1361]]) 
 tensor([[0.2802, 0.1475]])
tensor([[0.3336, 0.3028]]) 
 tensor([[0.2942, 0.2606]])
tensor([[0.4170, 0.0972]]) 
 tensor([[0.4506, 0.1335]])
tensor([[0.4587, 0.1750]]) 
 tensor([[0.4707, 0.1900]])
tensor([[0.5003, 0.1361]]) 
 tensor([[0.5337, 0.1076]])
tensor([[0.5525, 0.0500]]) 
 tensor([[0.6021, 0.0862]])
tensor([[0.5837, 0.1444]]) 
 tensor([[0.6429, 0.1028]])
tensor([[0.0000, 0.1306]]) 
 tensor([[-0.0076,  0.1340]])
tensor([[0.0521, 0.3028]]) 
 tensor([[-0.0126,  0.2764]])
tensor([[0.1251, 0.1250]]) 
 tensor([[0.1064, 0.1144]])
tensor([[0.1772, 0.1083]]) 
 tensor([[0.1408, 0.1000]])
tensor([[0.2189, 0.3000]]) 
 tensor([[0.13

100%|██████████| 208/208 [00:00<00:00, 208.25it/s, Loss=0.001923]


tensor([[0.0000, 0.1278]]) 
 tensor([[-0.0042,  0.1357]])
tensor([[0.0521, 0.1722]]) 
 tensor([[0.0314, 0.2433]])
tensor([[0.0938, 0.1167]]) 
 tensor([[0.0724, 0.1210]])
tensor([[0.1459, 0.1778]]) 
 tensor([[0.1175, 0.1932]])
tensor([[0.1876, 0.1389]]) 
 tensor([[0.1780, 0.1015]])
tensor([[0.2502, 0.2250]]) 
 tensor([[0.2441, 0.2300]])
tensor([[0.3023, 0.1361]]) 
 tensor([[0.3695, 0.1804]])
tensor([[0.3336, 0.3028]]) 
 tensor([[0.3495, 0.2763]])
tensor([[0.4170, 0.0972]]) 
 tensor([[0.4256, 0.1586]])
tensor([[0.4587, 0.1750]]) 
 tensor([[0.4438, 0.1996]])
tensor([[0.5003, 0.1361]]) 
 tensor([[0.4996, 0.1507]])
tensor([[0.5525, 0.0500]]) 
 tensor([[0.5624, 0.1440]])
tensor([[0.5837, 0.1444]]) 
 tensor([[0.6077, 0.1452]])
tensor([[0.0000, 0.1306]]) 
 tensor([[-0.0042,  0.1357]])
tensor([[0.0521, 0.3028]]) 
 tensor([[-0.0055,  0.2676]])
tensor([[0.1251, 0.1250]]) 
 tensor([[0.0646, 0.1103]])
tensor([[0.1772, 0.1083]]) 
 tensor([[0.1287, 0.0857]])
tensor([[0.2189, 0.3000]]) 
 tensor([[0.16

100%|██████████| 208/208 [00:00<00:00, 241.40it/s, Loss=0.001583]


tensor([[0.0000, 0.1278]]) 
 tensor([[-0.0096,  0.1338]])
tensor([[0.0521, 0.1722]]) 
 tensor([[0.0176, 0.2441]])
tensor([[0.0938, 0.1167]]) 
 tensor([[0.0801, 0.1222]])
tensor([[0.1459, 0.1778]]) 
 tensor([[0.1331, 0.1847]])
tensor([[0.1876, 0.1389]]) 
 tensor([[0.1869, 0.1084]])
tensor([[0.2502, 0.2250]]) 
 tensor([[0.2412, 0.2211]])
tensor([[0.3023, 0.1361]]) 
 tensor([[0.3379, 0.1708]])
tensor([[0.3336, 0.3028]]) 
 tensor([[0.3346, 0.2716]])
tensor([[0.4170, 0.0972]]) 
 tensor([[0.4346, 0.1219]])
tensor([[0.4587, 0.1750]]) 
 tensor([[0.4645, 0.1890]])
tensor([[0.5003, 0.1361]]) 
 tensor([[0.5099, 0.1232]])
tensor([[0.5525, 0.0500]]) 
 tensor([[0.5713, 0.0999]])
tensor([[0.5837, 0.1444]]) 
 tensor([[0.6099, 0.1261]])
tensor([[0.0000, 0.1306]]) 
 tensor([[-0.0096,  0.1338]])
tensor([[0.0521, 0.3028]]) 
 tensor([[-0.0147,  0.2700]])
tensor([[0.1251, 0.1250]]) 
 tensor([[0.0856, 0.1141]])
tensor([[0.1772, 0.1083]]) 
 tensor([[0.1505, 0.0984]])
tensor([[0.2189, 0.3000]]) 
 tensor([[0.18

100%|██████████| 208/208 [00:00<00:00, 223.93it/s, Loss=0.001676]


tensor([[0.0000, 0.1278]]) 
 tensor([[-0.0140,  0.1408]])
tensor([[0.0521, 0.1722]]) 
 tensor([[0.0393, 0.2402]])
tensor([[0.0938, 0.1167]]) 
 tensor([[0.0502, 0.1233]])
tensor([[0.1459, 0.1778]]) 
 tensor([[0.0920, 0.1718]])
tensor([[0.1876, 0.1389]]) 
 tensor([[0.1327, 0.0964]])
tensor([[0.2502, 0.2250]]) 
 tensor([[0.1579, 0.1905]])
tensor([[0.3023, 0.1361]]) 
 tensor([[0.2856, 0.1348]])
tensor([[0.3336, 0.3028]]) 
 tensor([[0.3566, 0.2626]])
tensor([[0.4170, 0.0972]]) 
 tensor([[0.4123, 0.1442]])
tensor([[0.4587, 0.1750]]) 
 tensor([[0.4405, 0.2024]])
tensor([[0.5003, 0.1361]]) 
 tensor([[0.4797, 0.1401]])
tensor([[0.5525, 0.0500]]) 
 tensor([[0.5465, 0.1238]])
tensor([[0.5837, 0.1444]]) 
 tensor([[0.5966, 0.1320]])
tensor([[0.0000, 0.1306]]) 
 tensor([[-0.0140,  0.1408]])
tensor([[0.0521, 0.3028]]) 
 tensor([[0.0091, 0.2694]])
tensor([[0.1251, 0.1250]]) 
 tensor([[0.0638, 0.1110]])
tensor([[0.1772, 0.1083]]) 
 tensor([[0.1236, 0.0941]])
tensor([[0.2189, 0.3000]]) 
 tensor([[0.1215

100%|██████████| 208/208 [00:00<00:00, 245.36it/s, Loss=0.002039]


tensor([[0.0000, 0.1278]]) 
 tensor([[-0.0132,  0.1382]])
tensor([[0.0521, 0.1722]]) 
 tensor([[0.0252, 0.2580]])
tensor([[0.0938, 0.1167]]) 
 tensor([[0.0604, 0.1317]])
tensor([[0.1459, 0.1778]]) 
 tensor([[0.1115, 0.1663]])
tensor([[0.1876, 0.1389]]) 
 tensor([[0.1622, 0.1074]])
tensor([[0.2502, 0.2250]]) 
 tensor([[0.2075, 0.2119]])
tensor([[0.3023, 0.1361]]) 
 tensor([[0.2659, 0.1184]])
tensor([[0.3336, 0.3028]]) 
 tensor([[0.3073, 0.2536]])
tensor([[0.4170, 0.0972]]) 
 tensor([[0.3766, 0.1298]])
tensor([[0.4587, 0.1750]]) 
 tensor([[0.4040, 0.1911]])
tensor([[0.5003, 0.1361]]) 
 tensor([[0.4374, 0.1350]])
tensor([[0.5525, 0.0500]]) 
 tensor([[0.4916, 0.1396]])
tensor([[0.5837, 0.1444]]) 
 tensor([[0.5330, 0.1432]])
tensor([[0.0000, 0.1306]]) 
 tensor([[-0.0132,  0.1382]])
tensor([[0.0521, 0.3028]]) 
 tensor([[-0.0056,  0.2940]])
tensor([[0.1251, 0.1250]]) 
 tensor([[0.0714, 0.1241]])
tensor([[0.1772, 0.1083]]) 
 tensor([[0.1409, 0.1051]])
tensor([[0.2189, 0.3000]]) 
 tensor([[0.15

100%|██████████| 208/208 [00:00<00:00, 233.36it/s, Loss=0.001511]


tensor([[0.0000, 0.1278]]) 
 tensor([[0.0110, 0.1435]])
tensor([[0.0521, 0.1722]]) 
 tensor([[0.0537, 0.2493]])
tensor([[0.0938, 0.1167]]) 
 tensor([[0.0808, 0.1532]])
tensor([[0.1459, 0.1778]]) 
 tensor([[0.1244, 0.1987]])
tensor([[0.1876, 0.1389]]) 
 tensor([[0.2047, 0.1175]])
tensor([[0.2502, 0.2250]]) 
 tensor([[0.2345, 0.2343]])
tensor([[0.3023, 0.1361]]) 
 tensor([[0.2942, 0.1422]])
tensor([[0.3336, 0.3028]]) 
 tensor([[0.3234, 0.2789]])
tensor([[0.4170, 0.0972]]) 
 tensor([[0.4092, 0.1174]])
tensor([[0.4587, 0.1750]]) 
 tensor([[0.4314, 0.2100]])
tensor([[0.5003, 0.1361]]) 
 tensor([[0.4990, 0.1241]])
tensor([[0.5525, 0.0500]]) 
 tensor([[0.5582, 0.1285]])
tensor([[0.5837, 0.1444]]) 
 tensor([[0.5994, 0.1317]])
tensor([[0.0000, 0.1306]]) 
 tensor([[0.0110, 0.1435]])
tensor([[0.0521, 0.3028]]) 
 tensor([[0.0164, 0.2852]])
tensor([[0.1251, 0.1250]]) 
 tensor([[0.1084, 0.1423]])
tensor([[0.1772, 0.1083]]) 
 tensor([[0.1816, 0.1176]])
tensor([[0.2189, 0.3000]]) 
 tensor([[0.1696, 0.

100%|██████████| 208/208 [00:00<00:00, 225.23it/s, Loss=0.000925]


tensor([[0.0000, 0.1278]]) 
 tensor([[0.0119, 0.1369]])
tensor([[0.0521, 0.1722]]) 
 tensor([[0.0634, 0.2301]])
tensor([[0.0938, 0.1167]]) 
 tensor([[0.1060, 0.1363]])
tensor([[0.1459, 0.1778]]) 
 tensor([[0.1492, 0.1777]])
tensor([[0.1876, 0.1389]]) 
 tensor([[0.2272, 0.1029]])
tensor([[0.2502, 0.2250]]) 
 tensor([[0.2692, 0.2085]])
tensor([[0.3023, 0.1361]]) 
 tensor([[0.3144, 0.1137]])
tensor([[0.3336, 0.3028]]) 
 tensor([[0.3376, 0.2551]])
tensor([[0.4170, 0.0972]]) 
 tensor([[0.4242, 0.1149]])
tensor([[0.4587, 0.1750]]) 
 tensor([[0.4573, 0.1899]])
tensor([[0.5003, 0.1361]]) 
 tensor([[0.5251, 0.1203]])
tensor([[0.5525, 0.0500]]) 
 tensor([[0.5843, 0.1234]])
tensor([[0.5837, 0.1444]]) 
 tensor([[0.6203, 0.1253]])
tensor([[0.0000, 0.1306]]) 
 tensor([[0.0119, 0.1369]])
tensor([[0.0521, 0.3028]]) 
 tensor([[0.0273, 0.2665]])
tensor([[0.1251, 0.1250]]) 
 tensor([[0.1217, 0.1291]])
tensor([[0.1772, 0.1083]]) 
 tensor([[0.1949, 0.1009]])
tensor([[0.2189, 0.3000]]) 
 tensor([[0.2022, 0.

100%|██████████| 208/208 [00:00<00:00, 237.19it/s, Loss=0.000865]


tensor([[0.0000, 0.1278]]) 
 tensor([[0.0109, 0.1366]])
tensor([[0.0521, 0.1722]]) 
 tensor([[0.0825, 0.2226]])
tensor([[0.0938, 0.1167]]) 
 tensor([[0.1426, 0.1159]])
tensor([[0.1459, 0.1778]]) 
 tensor([[0.2018, 0.1603]])
tensor([[0.1876, 0.1389]]) 
 tensor([[0.2423, 0.0925]])
tensor([[0.2502, 0.2250]]) 
 tensor([[0.2992, 0.1969]])
tensor([[0.3023, 0.1361]]) 
 tensor([[0.3313, 0.1195]])
tensor([[0.3336, 0.3028]]) 
 tensor([[0.3722, 0.2454]])
tensor([[0.4170, 0.0972]]) 
 tensor([[0.4055, 0.1113]])
tensor([[0.4587, 0.1750]]) 
 tensor([[0.4496, 0.1896]])
tensor([[0.5003, 0.1361]]) 
 tensor([[0.4928, 0.1182]])
tensor([[0.5525, 0.0500]]) 
 tensor([[0.5493, 0.1227]])
tensor([[0.5837, 0.1444]]) 
 tensor([[0.5875, 0.1257]])
tensor([[0.0000, 0.1306]]) 
 tensor([[0.0109, 0.1366]])
tensor([[0.0521, 0.3028]]) 
 tensor([[0.0507, 0.2562]])
tensor([[0.1251, 0.1250]]) 
 tensor([[0.1712, 0.1062]])
tensor([[0.1772, 0.1083]]) 
 tensor([[0.2156, 0.0894]])
tensor([[0.2189, 0.3000]]) 
 tensor([[0.2457, 0.

100%|██████████| 208/208 [00:00<00:00, 219.78it/s, Loss=0.001382]


tensor([[0.0000, 0.1278]]) 
 tensor([[0.0069, 0.1290]])
tensor([[0.0521, 0.1722]]) 
 tensor([[0.0866, 0.2161]])
tensor([[0.0938, 0.1167]]) 
 tensor([[0.0942, 0.1183]])
tensor([[0.1459, 0.1778]]) 
 tensor([[0.1403, 0.1464]])
tensor([[0.1876, 0.1389]]) 
 tensor([[0.2135, 0.1013]])
tensor([[0.2502, 0.2250]]) 
 tensor([[0.2495, 0.1761]])
tensor([[0.3023, 0.1361]]) 
 tensor([[0.2971, 0.1083]])
tensor([[0.3336, 0.3028]]) 
 tensor([[0.3091, 0.2239]])
tensor([[0.4170, 0.0972]]) 
 tensor([[0.4111, 0.1163]])
tensor([[0.4587, 0.1750]]) 
 tensor([[0.4488, 0.1783]])
tensor([[0.5003, 0.1361]]) 
 tensor([[0.5048, 0.1176]])
tensor([[0.5525, 0.0500]]) 
 tensor([[0.5685, 0.1185]])
tensor([[0.5837, 0.1444]]) 
 tensor([[0.6177, 0.1191]])
tensor([[0.0000, 0.1306]]) 
 tensor([[0.0069, 0.1290]])
tensor([[0.0521, 0.3028]]) 
 tensor([[0.0501, 0.2471]])
tensor([[0.1251, 0.1250]]) 
 tensor([[0.1236, 0.1140]])
tensor([[0.1772, 0.1083]]) 
 tensor([[0.2001, 0.1002]])
tensor([[0.2189, 0.3000]]) 
 tensor([[0.2024, 0.

100%|██████████| 208/208 [00:01<00:00, 207.40it/s, Loss=0.001455]


tensor([[0.0000, 0.1278]]) 
 tensor([[0.0010, 0.1343]])
tensor([[0.0521, 0.1722]]) 
 tensor([[0.0793, 0.2195]])
tensor([[0.0938, 0.1167]]) 
 tensor([[0.1418, 0.1136]])
tensor([[0.1459, 0.1778]]) 
 tensor([[0.1927, 0.1448]])
tensor([[0.1876, 0.1389]]) 
 tensor([[0.2263, 0.0944]])
tensor([[0.2502, 0.2250]]) 
 tensor([[0.2718, 0.1818]])
tensor([[0.3023, 0.1361]]) 
 tensor([[0.3347, 0.1043]])
tensor([[0.3336, 0.3028]]) 
 tensor([[0.3707, 0.2314]])
tensor([[0.4170, 0.0972]]) 
 tensor([[0.3810, 0.1087]])
tensor([[0.4587, 0.1750]]) 
 tensor([[0.4251, 0.1715]])
tensor([[0.5003, 0.1361]]) 
 tensor([[0.4654, 0.1172]])
tensor([[0.5525, 0.0500]]) 
 tensor([[0.5183, 0.1225]])
tensor([[0.5837, 0.1444]]) 
 tensor([[0.5607, 0.1268]])
tensor([[0.0000, 0.1306]]) 
 tensor([[0.0010, 0.1343]])
tensor([[0.0521, 0.3028]]) 
 tensor([[0.0497, 0.2570]])
tensor([[0.1251, 0.1250]]) 
 tensor([[0.1678, 0.1067]])
tensor([[0.1772, 0.1083]]) 
 tensor([[0.2123, 0.0931]])
tensor([[0.2189, 0.3000]]) 
 tensor([[0.2349, 0.

100%|██████████| 208/208 [00:00<00:00, 223.94it/s, Loss=0.001423]


tensor([[0.0000, 0.1278]]) 
 tensor([[0.0153, 0.1311]])
tensor([[0.0521, 0.1722]]) 
 tensor([[0.1441, 0.2051]])
tensor([[0.0938, 0.1167]]) 
 tensor([[0.1823, 0.1124]])
tensor([[0.1459, 0.1778]]) 
 tensor([[0.2345, 0.1419]])
tensor([[0.1876, 0.1389]]) 
 tensor([[0.2652, 0.0950]])
tensor([[0.2502, 0.2250]]) 
 tensor([[0.2988, 0.1881]])
tensor([[0.3023, 0.1361]]) 
 tensor([[0.3453, 0.1001]])
tensor([[0.3336, 0.3028]]) 
 tensor([[0.3724, 0.2386]])
tensor([[0.4170, 0.0972]]) 
 tensor([[0.4194, 0.1047]])
tensor([[0.4587, 0.1750]]) 
 tensor([[0.4538, 0.1768]])
tensor([[0.5003, 0.1361]]) 
 tensor([[0.5107, 0.1122]])
tensor([[0.5525, 0.0500]]) 
 tensor([[0.5632, 0.1166]])
tensor([[0.5837, 0.1444]]) 
 tensor([[0.6026, 0.1198]])
tensor([[0.0000, 0.1306]]) 
 tensor([[0.0153, 0.1311]])
tensor([[0.0521, 0.3028]]) 
 tensor([[0.1131, 0.2448]])
tensor([[0.1251, 0.1250]]) 
 tensor([[0.2196, 0.1054]])
tensor([[0.1772, 0.1083]]) 
 tensor([[0.2607, 0.0947]])
tensor([[0.2189, 0.3000]]) 
 tensor([[0.2727, 0.

100%|██████████| 208/208 [00:00<00:00, 216.35it/s, Loss=0.000900]


tensor([[0.0000, 0.1278]]) 
 tensor([[0.0071, 0.1327]])
tensor([[0.0521, 0.1722]]) 
 tensor([[0.1276, 0.2071]])
tensor([[0.0938, 0.1167]]) 
 tensor([[0.1861, 0.1114]])
tensor([[0.1459, 0.1778]]) 
 tensor([[0.2552, 0.1638]])
tensor([[0.1876, 0.1389]]) 
 tensor([[0.2744, 0.0936]])
tensor([[0.2502, 0.2250]]) 
 tensor([[0.3271, 0.2045]])
tensor([[0.3023, 0.1361]]) 
 tensor([[0.3685, 0.1177]])
tensor([[0.3336, 0.3028]]) 
 tensor([[0.4032, 0.2531]])
tensor([[0.4170, 0.0972]]) 
 tensor([[0.4262, 0.1093]])
tensor([[0.4587, 0.1750]]) 
 tensor([[0.4747, 0.1963]])
tensor([[0.5003, 0.1361]]) 
 tensor([[0.5381, 0.1222]])
tensor([[0.5525, 0.0500]]) 
 tensor([[0.5879, 0.1279]])
tensor([[0.5837, 0.1444]]) 
 tensor([[0.6122, 0.1307]])
tensor([[0.0000, 0.1306]]) 
 tensor([[0.0071, 0.1327]])
tensor([[0.0521, 0.3028]]) 
 tensor([[0.0988, 0.2425]])
tensor([[0.1251, 0.1250]]) 
 tensor([[0.2273, 0.1040]])
tensor([[0.1772, 0.1083]]) 
 tensor([[0.2612, 0.0923]])
tensor([[0.2189, 0.3000]]) 
 tensor([[0.3024, 0.

100%|██████████| 208/208 [00:00<00:00, 230.58it/s, Loss=0.001028]


tensor([[0.0000, 0.1278]]) 
 tensor([[0.0011, 0.1337]])
tensor([[0.0521, 0.1722]]) 
 tensor([[0.0981, 0.2141]])
tensor([[0.0938, 0.1167]]) 
 tensor([[0.1524, 0.1093]])
tensor([[0.1459, 0.1778]]) 
 tensor([[0.2097, 0.1677]])
tensor([[0.1876, 0.1389]]) 
 tensor([[0.2218, 0.0937]])
tensor([[0.2502, 0.2250]]) 
 tensor([[0.2747, 0.2178]])
tensor([[0.3023, 0.1361]]) 
 tensor([[0.3107, 0.1299]])
tensor([[0.3336, 0.3028]]) 
 tensor([[0.3619, 0.2761]])
tensor([[0.4170, 0.0972]]) 
 tensor([[0.3838, 0.1163]])
tensor([[0.4587, 0.1750]]) 
 tensor([[0.4405, 0.2160]])
tensor([[0.5003, 0.1361]]) 
 tensor([[0.4739, 0.1208]])
tensor([[0.5525, 0.0500]]) 
 tensor([[0.5230, 0.1232]])
tensor([[0.5837, 0.1444]]) 
 tensor([[0.5587, 0.1261]])
tensor([[0.0000, 0.1306]]) 
 tensor([[0.0011, 0.1337]])
tensor([[0.0521, 0.3028]]) 
 tensor([[0.0720, 0.2504]])
tensor([[0.1251, 0.1250]]) 
 tensor([[0.1881, 0.1041]])
tensor([[0.1772, 0.1083]]) 
 tensor([[0.2226, 0.0938]])
tensor([[0.2189, 0.3000]]) 
 tensor([[0.2706, 0.

100%|██████████| 208/208 [00:02<00:00, 99.38it/s, Loss=0.001399]


tensor([[0.0000, 0.1278]]) 
 tensor([[-0.0027,  0.1363]])
tensor([[0.0521, 0.1722]]) 
 tensor([[0.0900, 0.2143]])
tensor([[0.0938, 0.1167]]) 
 tensor([[0.1497, 0.0833]])
tensor([[0.1459, 0.1778]]) 
 tensor([[0.2030, 0.1340]])
tensor([[0.1876, 0.1389]]) 
 tensor([[0.2157, 0.0913]])
tensor([[0.2502, 0.2250]]) 
 tensor([[0.2753, 0.2000]])
tensor([[0.3023, 0.1361]]) 
 tensor([[0.3247, 0.1177]])
tensor([[0.3336, 0.3028]]) 
 tensor([[0.3631, 0.2582]])
tensor([[0.4170, 0.0972]]) 
 tensor([[0.3985, 0.1135]])
tensor([[0.4587, 0.1750]]) 
 tensor([[0.4322, 0.2059]])
tensor([[0.5003, 0.1361]]) 
 tensor([[0.4607, 0.1169]])
tensor([[0.5525, 0.0500]]) 
 tensor([[0.5190, 0.1201]])
tensor([[0.5837, 0.1444]]) 
 tensor([[0.5686, 0.1228]])
tensor([[0.0000, 0.1306]]) 
 tensor([[-0.0027,  0.1363]])
tensor([[0.0521, 0.3028]]) 
 tensor([[0.0724, 0.2466]])
tensor([[0.1251, 0.1250]]) 
 tensor([[0.1650, 0.0851]])
tensor([[0.1772, 0.1083]]) 
 tensor([[0.2044, 0.0899]])
tensor([[0.2189, 0.3000]]) 
 tensor([[0.2594

100%|██████████| 208/208 [00:02<00:00, 89.08it/s, Loss=0.001239] 


tensor([[0.0000, 0.1278]]) 
 tensor([[-0.0061,  0.1312]])
tensor([[0.0521, 0.1722]]) 
 tensor([[0.1002, 0.2087]])
tensor([[0.0938, 0.1167]]) 
 tensor([[0.1439, 0.1001]])
tensor([[0.1459, 0.1778]]) 
 tensor([[0.1740, 0.1451]])
tensor([[0.1876, 0.1389]]) 
 tensor([[0.2504, 0.0985]])
tensor([[0.2502, 0.2250]]) 
 tensor([[0.3066, 0.2059]])
tensor([[0.3023, 0.1361]]) 
 tensor([[0.4129, 0.1146]])
tensor([[0.3336, 0.3028]]) 
 tensor([[0.3891, 0.2626]])
tensor([[0.4170, 0.0972]]) 
 tensor([[0.4416, 0.1074]])
tensor([[0.4587, 0.1750]]) 
 tensor([[0.4764, 0.2052]])
tensor([[0.5003, 0.1361]]) 
 tensor([[0.5509, 0.1178]])
tensor([[0.5525, 0.0500]]) 
 tensor([[0.6072, 0.1231]])
tensor([[0.5837, 0.1444]]) 
 tensor([[0.6341, 0.1257]])
tensor([[0.0000, 0.1306]]) 
 tensor([[-0.0061,  0.1312]])
tensor([[0.0521, 0.3028]]) 
 tensor([[0.0773, 0.2428]])
tensor([[0.1251, 0.1250]]) 
 tensor([[0.1812, 0.0958]])
tensor([[0.1772, 0.1083]]) 
 tensor([[0.2259, 0.0975]])
tensor([[0.2189, 0.3000]]) 
 tensor([[0.2731

100%|██████████| 208/208 [00:02<00:00, 100.47it/s, Loss=0.001226]


tensor([[0.0000, 0.1278]]) 
 tensor([[-0.0103,  0.1369]])
tensor([[0.0521, 0.1722]]) 
 tensor([[0.0659, 0.2300]])
tensor([[0.0938, 0.1167]]) 
 tensor([[0.0926, 0.0818]])
tensor([[0.1459, 0.1778]]) 
 tensor([[0.1478, 0.1200]])
tensor([[0.1876, 0.1389]]) 
 tensor([[0.1401, 0.0872]])
tensor([[0.2502, 0.2250]]) 
 tensor([[0.1974, 0.2053]])
tensor([[0.3023, 0.1361]]) 
 tensor([[0.2447, 0.1190]])
tensor([[0.3336, 0.3028]]) 
 tensor([[0.2915, 0.2792]])
tensor([[0.4170, 0.0972]]) 
 tensor([[0.4072, 0.1176]])
tensor([[0.4587, 0.1750]]) 
 tensor([[0.4148, 0.2326]])
tensor([[0.5003, 0.1361]]) 
 tensor([[0.4509, 0.1164]])
tensor([[0.5525, 0.0500]]) 
 tensor([[0.5153, 0.1147]])
tensor([[0.5837, 0.1444]]) 
 tensor([[0.5713, 0.1196]])
tensor([[0.0000, 0.1306]]) 
 tensor([[-0.0103,  0.1369]])
tensor([[0.0521, 0.3028]]) 
 tensor([[0.0478, 0.2640]])
tensor([[0.1251, 0.1250]]) 
 tensor([[0.1091, 0.0836]])
tensor([[0.1772, 0.1083]]) 
 tensor([[0.1479, 0.0881]])
tensor([[0.2189, 0.3000]]) 
 tensor([[0.1926

100%|██████████| 208/208 [00:02<00:00, 102.52it/s, Loss=0.001230]


tensor([[0.0000, 0.1278]]) 
 tensor([[-0.0019,  0.1318]])
tensor([[0.0521, 0.1722]]) 
 tensor([[0.0984, 0.2051]])
tensor([[0.0938, 0.1167]]) 
 tensor([[0.1179, 0.0841]])
tensor([[0.1459, 0.1778]]) 
 tensor([[0.1567, 0.1256]])
tensor([[0.1876, 0.1389]]) 
 tensor([[0.2100, 0.0862]])
tensor([[0.2502, 0.2250]]) 
 tensor([[0.2717, 0.1879]])
tensor([[0.3023, 0.1361]]) 
 tensor([[0.3198, 0.0977]])
tensor([[0.3336, 0.3028]]) 
 tensor([[0.3625, 0.2504]])
tensor([[0.4170, 0.0972]]) 
 tensor([[0.4306, 0.1000]])
tensor([[0.4587, 0.1750]]) 
 tensor([[0.4396, 0.2028]])
tensor([[0.5003, 0.1361]]) 
 tensor([[0.4846, 0.1064]])
tensor([[0.5525, 0.0500]]) 
 tensor([[0.5452, 0.1137]])
tensor([[0.5837, 0.1444]]) 
 tensor([[0.5899, 0.1190]])
tensor([[0.0000, 0.1306]]) 
 tensor([[-0.0019,  0.1318]])
tensor([[0.0521, 0.3028]]) 
 tensor([[0.0815, 0.2408]])
tensor([[0.1251, 0.1250]]) 
 tensor([[0.1597, 0.0831]])
tensor([[0.1772, 0.1083]]) 
 tensor([[0.2059, 0.0860]])
tensor([[0.2189, 0.3000]]) 
 tensor([[0.2568

100%|██████████| 208/208 [00:01<00:00, 109.76it/s, Loss=0.001234]


tensor([[0.0000, 0.1278]]) 
 tensor([[0.0129, 0.1285]])
tensor([[0.0521, 0.1722]]) 
 tensor([[0.1104, 0.2029]])
tensor([[0.0938, 0.1167]]) 
 tensor([[0.1420, 0.0932]])
tensor([[0.1459, 0.1778]]) 
 tensor([[0.2035, 0.1290]])
tensor([[0.1876, 0.1389]]) 
 tensor([[0.2288, 0.0956]])
tensor([[0.2502, 0.2250]]) 
 tensor([[0.3009, 0.1847]])
tensor([[0.3023, 0.1361]]) 
 tensor([[0.3634, 0.0994]])
tensor([[0.3336, 0.3028]]) 
 tensor([[0.4107, 0.2382]])
tensor([[0.4170, 0.0972]]) 
 tensor([[0.4141, 0.1008]])
tensor([[0.4587, 0.1750]]) 
 tensor([[0.4461, 0.1856]])
tensor([[0.5003, 0.1361]]) 
 tensor([[0.4897, 0.1276]])
tensor([[0.5525, 0.0500]]) 
 tensor([[0.5335, 0.1431]])
tensor([[0.5837, 0.1444]]) 
 tensor([[0.5568, 0.1513]])
tensor([[0.0000, 0.1306]]) 
 tensor([[0.0129, 0.1285]])
tensor([[0.0521, 0.3028]]) 
 tensor([[0.0936, 0.2405]])
tensor([[0.1251, 0.1250]]) 
 tensor([[0.1611, 0.0937]])
tensor([[0.1772, 0.1083]]) 
 tensor([[0.2068, 0.0950]])
tensor([[0.2189, 0.3000]]) 
 tensor([[0.2692, 0.

100%|██████████| 208/208 [00:02<00:00, 90.56it/s, Loss=0.001474]


tensor([[0.0000, 0.1278]]) 
 tensor([[-0.0273,  0.1381]])
tensor([[0.0521, 0.1722]]) 
 tensor([[0.0615, 0.2185]])
tensor([[0.0938, 0.1167]]) 
 tensor([[0.1236, 0.0843]])
tensor([[0.1459, 0.1778]]) 
 tensor([[0.1861, 0.1404]])
tensor([[0.1876, 0.1389]]) 
 tensor([[0.2097, 0.0909]])
tensor([[0.2502, 0.2250]]) 
 tensor([[0.2581, 0.2074]])
tensor([[0.3023, 0.1361]]) 
 tensor([[0.3021, 0.1033]])
tensor([[0.3336, 0.3028]]) 
 tensor([[0.3421, 0.2719]])
tensor([[0.4170, 0.0972]]) 
 tensor([[0.4161, 0.1066]])
tensor([[0.4587, 0.1750]]) 
 tensor([[0.4158, 0.2198]])
tensor([[0.5003, 0.1361]]) 
 tensor([[0.4581, 0.1129]])
tensor([[0.5525, 0.0500]]) 
 tensor([[0.5126, 0.1210]])
tensor([[0.5837, 0.1444]]) 
 tensor([[0.5527, 0.1271]])
tensor([[0.0000, 0.1306]]) 
 tensor([[-0.0273,  0.1381]])
tensor([[0.0521, 0.3028]]) 
 tensor([[0.0445, 0.2566]])
tensor([[0.1251, 0.1250]]) 
 tensor([[0.1597, 0.0871]])
tensor([[0.1772, 0.1083]]) 
 tensor([[0.2192, 0.0916]])
tensor([[0.2189, 0.3000]]) 
 tensor([[0.2550

100%|██████████| 208/208 [00:02<00:00, 94.63it/s, Loss=0.001156]


tensor([[0.0000, 0.1278]]) 
 tensor([[0.0194, 0.1260]])
tensor([[0.0521, 0.1722]]) 
 tensor([[0.1585, 0.1907]])
tensor([[0.0938, 0.1167]]) 
 tensor([[0.2059, 0.1053]])
tensor([[0.1459, 0.1778]]) 
 tensor([[0.2513, 0.1491]])
tensor([[0.1876, 0.1389]]) 
 tensor([[0.2833, 0.1040]])
tensor([[0.2502, 0.2250]]) 
 tensor([[0.3251, 0.1990]])
tensor([[0.3023, 0.1361]]) 
 tensor([[0.3715, 0.1025]])
tensor([[0.3336, 0.3028]]) 
 tensor([[0.4044, 0.2507]])
tensor([[0.4170, 0.0972]]) 
 tensor([[0.4320, 0.1014]])
tensor([[0.4587, 0.1750]]) 
 tensor([[0.4794, 0.2054]])
tensor([[0.5003, 0.1361]]) 
 tensor([[0.5538, 0.1185]])
tensor([[0.5525, 0.0500]]) 
 tensor([[0.6109, 0.1265]])
tensor([[0.5837, 0.1444]]) 
 tensor([[0.6382, 0.1303]])
tensor([[0.0000, 0.1306]]) 
 tensor([[0.0194, 0.1260]])
tensor([[0.0521, 0.3028]]) 
 tensor([[0.1443, 0.2266]])
tensor([[0.1251, 0.1250]]) 
 tensor([[0.2471, 0.1046]])
tensor([[0.1772, 0.1083]]) 
 tensor([[0.2949, 0.1038]])
tensor([[0.2189, 0.3000]]) 
 tensor([[0.3282, 0.

100%|██████████| 208/208 [00:02<00:00, 93.78it/s, Loss=0.001299]


tensor([[0.0000, 0.1278]]) 
 tensor([[0.0110, 0.1302]])
tensor([[0.0521, 0.1722]]) 
 tensor([[0.1023, 0.2068]])
tensor([[0.0938, 0.1167]]) 
 tensor([[0.1480, 0.0928]])
tensor([[0.1459, 0.1778]]) 
 tensor([[0.2000, 0.1528]])
tensor([[0.1876, 0.1389]]) 
 tensor([[0.2341, 0.0997]])
tensor([[0.2502, 0.2250]]) 
 tensor([[0.2935, 0.2175]])
tensor([[0.3023, 0.1361]]) 
 tensor([[0.3511, 0.1090]])
tensor([[0.3336, 0.3028]]) 
 tensor([[0.3905, 0.2727]])
tensor([[0.4170, 0.0972]]) 
 tensor([[0.4042, 0.1133]])
tensor([[0.4587, 0.1750]]) 
 tensor([[0.4565, 0.2161]])
tensor([[0.5003, 0.1361]]) 
 tensor([[0.5118, 0.1219]])
tensor([[0.5525, 0.0500]]) 
 tensor([[0.5627, 0.1259]])
tensor([[0.5837, 0.1444]]) 
 tensor([[0.5921, 0.1282]])
tensor([[0.0000, 0.1306]]) 
 tensor([[0.0110, 0.1302]])
tensor([[0.0521, 0.3028]]) 
 tensor([[0.0872, 0.2445]])
tensor([[0.1251, 0.1250]]) 
 tensor([[0.1834, 0.0957]])
tensor([[0.1772, 0.1083]]) 
 tensor([[0.2303, 0.0994]])
tensor([[0.2189, 0.3000]]) 
 tensor([[0.2840, 0.

100%|██████████| 208/208 [00:02<00:00, 89.92it/s, Loss=0.001388]


tensor([[0.0000, 0.1278]]) 
 tensor([[0.0346, 0.1319]])
tensor([[0.0521, 0.1722]]) 
 tensor([[0.1261, 0.2027]])
tensor([[0.0938, 0.1167]]) 
 tensor([[0.1725, 0.1023]])
tensor([[0.1459, 0.1778]]) 
 tensor([[0.2037, 0.1629]])
tensor([[0.1876, 0.1389]]) 
 tensor([[0.2533, 0.1056]])
tensor([[0.2502, 0.2250]]) 
 tensor([[0.3156, 0.2188]])
tensor([[0.3023, 0.1361]]) 
 tensor([[0.3781, 0.1108]])
tensor([[0.3336, 0.3028]]) 
 tensor([[0.4085, 0.2702]])
tensor([[0.4170, 0.0972]]) 
 tensor([[0.4116, 0.1122]])
tensor([[0.4587, 0.1750]]) 
 tensor([[0.4479, 0.2034]])
tensor([[0.5003, 0.1361]]) 
 tensor([[0.5031, 0.1183]])
tensor([[0.5525, 0.0500]]) 
 tensor([[0.5584, 0.1220]])
tensor([[0.5837, 0.1444]]) 
 tensor([[0.5984, 0.1247]])
tensor([[0.0000, 0.1306]]) 
 tensor([[0.0346, 0.1319]])
tensor([[0.0521, 0.3028]]) 
 tensor([[0.1117, 0.2445]])
tensor([[0.1251, 0.1250]]) 
 tensor([[0.2043, 0.1036]])
tensor([[0.1772, 0.1083]]) 
 tensor([[0.2449, 0.1053]])
tensor([[0.2189, 0.3000]]) 
 tensor([[0.3029, 0.

100%|██████████| 208/208 [00:01<00:00, 104.86it/s, Loss=0.000853]


tensor([[0.0000, 0.1278]]) 
 tensor([[0.0035, 0.1335]])
tensor([[0.0521, 0.1722]]) 
 tensor([[0.0992, 0.2148]])
tensor([[0.0938, 0.1167]]) 
 tensor([[0.1347, 0.0994]])
tensor([[0.1459, 0.1778]]) 
 tensor([[0.1888, 0.1646]])
tensor([[0.1876, 0.1389]]) 
 tensor([[0.2250, 0.1009]])
tensor([[0.2502, 0.2250]]) 
 tensor([[0.2892, 0.2225]])
tensor([[0.3023, 0.1361]]) 
 tensor([[0.3460, 0.1107]])
tensor([[0.3336, 0.3028]]) 
 tensor([[0.3835, 0.2702]])
tensor([[0.4170, 0.0972]]) 
 tensor([[0.4310, 0.1041]])
tensor([[0.4587, 0.1750]]) 
 tensor([[0.4432, 0.2157]])
tensor([[0.5003, 0.1361]]) 
 tensor([[0.4897, 0.1135]])
tensor([[0.5525, 0.0500]]) 
 tensor([[0.5383, 0.1213]])
tensor([[0.5837, 0.1444]]) 
 tensor([[0.5733, 0.1460]])
tensor([[0.0000, 0.1306]]) 
 tensor([[0.0035, 0.1335]])
tensor([[0.0521, 0.3028]]) 
 tensor([[0.0838, 0.2521]])
tensor([[0.1251, 0.1250]]) 
 tensor([[0.1681, 0.1000]])
tensor([[0.1772, 0.1083]]) 
 tensor([[0.2152, 0.1007]])
tensor([[0.2189, 0.3000]]) 
 tensor([[0.2735, 0.

In [28]:
def float_to_schedule(input):
    start, duration = input[0], input[1]
    start *= max_time
    hours = start // 24
    minutes = start % 24
    duration *= DUR
    return hours, minutes, duration


In [29]:
df_out = df_out.reset_index(drop=True)
df_out

Date Start Time  Duration  Importance  Label Number     Label Name  \
0   2023-07-04      07:00        60           1             3  Daily Routine   
1   2023-07-04      08:15        45           2             0          Sport   
2   2023-07-04      09:15        60           0             1  Hobby Passive   
3   2023-07-04      10:30        45           3             2     Work&Study   
4   2023-07-04      11:30        60           1             3  Daily Routine   
5   2023-07-04      13:00        60           2             2     Work&Study   
6   2023-07-04      14:15        30           0             0          Sport   
7   2023-07-04      15:00        90           1             2     Work&Study   
8   2023-07-04      17:00        45           1             3  Daily Routine   
9   2023-07-04      18:00        45           2             0          Sport   
10  2023-07-04      19:00        60           1             1  Hobby Passive   
11  2023-07-04      20:15        30           0             1  Hobby Passive   
12  2023-07-04      21:00        60           0             3  Daily Routine   
13  2023-07-05      07:00        60           1             3  Daily Routine   
14  2023-07-05      08:15        90           2             0          Sport   
15  2023-07-05      10:00        60           2             1  Hobby Passive   
16  2023-07-05      11:15        45           0             3  Daily Routine   
17  2023-07-05      12:15        90           3             2     Work&Study   
18  2023-07-05      14:00        90           1             0          Sport   
19  2023-07-05      15:45        90           2             2     Work&Study   
20  2023-07-05      17:30        45           1             3  Daily Routine   
21  2023-07-05      18:30        90           1             0          Sport   
22  2023-07-05      20:15        90           2             3  Daily Routine   
23  2023-07-05      22:00        60           0             3  Daily Routine   
24  2023-07-06      07:00        60           1             3  Daily Routine   
25  2023-07-06      08:15        45           2             0          Sport   
26  2023-07-06      09:15        90           3             2     Work&Study   
27  2023-07-06      11:00        45           0             3  Daily Routine   
28  2023-07-06      12:00        60           2             2     Work&Study   
29  2023-07-06      13:15        90           1             0          Sport   
30  2023-07-06      15:00        90           1             2     Work&Study   
31  2023-07-06      17:00        45           1             3  Daily Routine   
32  2023-07-06      18:00        90           1             0          Sport   
33  2023-07-06      19:45        90           2             3  Daily Routine   
34  2023-07-06      21:30        60           0             3  Daily Routine   
35  2023-07-07      07:00        60           1             3  Daily Routine   
36  2023-07-07      08:15        90           2             0          Sport   
37  2023-07-07      10:00        60           2             1  Hobby Passive   
38  2023-07-07      11:15        45           0             3  Daily Routine   
39  2023-07-07      12:15        90           3             2     Work&Study   
40  2023-07-07      14:00        90           1             0          Sport   
41  2023-07-07      15:45        90           2             2     Work&Study   
42  2023-07-07      17:30        45           1             3  Daily Routine   
43  2023-07-07      18:30        90           1             0          Sport   
44  2023-07-07      20:15        90           2             3  Daily Routine   
45  2023-07-07      22:00        60           0             3  Daily Routine   

    True Duration  True Hours  True Minutes  
0              46         0.0           0.0  
1              62         3.0           3.0  
2              42         5.0          15.0  
3              64         8.0          18.0  
4              50  

In [30]:
# out_df = df[-1*y_test.shape[0]:]
with torch.no_grad():
    ind = 0
    for data, target in dataloaders['test']:
        # print(f"target shape is {target.shape}")
        data, target = data.to(device), target.to(device)
        output = model1(data).cpu().numpy()
        for i in output:
            df_out.loc[ind, ['Pred Hours', 'Pred Min', 'Pred Dur']] = float_to_schedule(i)
            ind+=1
df_out

Date Start Time  Duration  Importance  Label Number     Label Name  \
0   2023-07-04      07:00        60           1             3  Daily Routine   
1   2023-07-04      08:15        45           2             0          Sport   
2   2023-07-04      09:15        60           0             1  Hobby Passive   
3   2023-07-04      10:30        45           3             2     Work&Study   
4   2023-07-04      11:30        60           1             3  Daily Routine   
5   2023-07-04      13:00        60           2             2     Work&Study   
6   2023-07-04      14:15        30           0             0          Sport   
7   2023-07-04      15:00        90           1             2     Work&Study   
8   2023-07-04      17:00        45           1             3  Daily Routine   
9   2023-07-04      18:00        45           2             0          Sport   
10  2023-07-04      19:00        60           1             1  Hobby Passive   
11  2023-07-04      20:15        30           0             1  Hobby Passive   
12  2023-07-04      21:00        60           0             3  Daily Routine   
13  2023-07-05      07:00        60           1             3  Daily Routine   
14  2023-07-05      08:15        90           2             0          Sport   
15  2023-07-05      10:00        60           2             1  Hobby Passive   
16  2023-07-05      11:15        45           0             3  Daily Routine   
17  2023-07-05      12:15        90           3             2     Work&Study   
18  2023-07-05      14:00        90           1             0          Sport   
19  2023-07-05      15:45        90           2             2     Work&Study   
20  2023-07-05      17:30        45           1             3  Daily Routine   
21  2023-07-05      18:30        90           1             0          Sport   
22  2023-07-05      20:15        90           2             3  Daily Routine   
23  2023-07-05      22:00        60           0             3  Daily Routine   
24  2023-07-06      07:00        60           1             3  Daily Routine   
25  2023-07-06      08:15        45           2             0          Sport   
26  2023-07-06      09:15        90           3             2     Work&Study   
27  2023-07-06      11:00        45           0             3  Daily Routine   
28  2023-07-06      12:00        60           2             2     Work&Study   
29  2023-07-06      13:15        90           1             0          Sport   
30  2023-07-06      15:00        90           1             2     Work&Study   
31  2023-07-06      17:00        45           1             3  Daily Routine   
32  2023-07-06      18:00        90           1             0          Sport   
33  2023-07-06      19:45        90           2             3  Daily Routine   
34  2023-07-06      21:30        60           0             3  Daily Routine   
35  2023-07-07      07:00        60           1             3  Daily Routine   
36  2023-07-07      08:15        90           2             0          Sport   
37  2023-07-07      10:00        60           2             1  Hobby Passive   
38  2023-07-07      11:15        45           0             3  Daily Routine   
39  2023-07-07      12:15        90           3             2     Work&Study   
40  2023-07-07      14:00        90           1             0          Sport   
41  2023-07-07      15:45        90           2             2     Work&Study   
42  2023-07-07      17:30        45           1             3  Daily Routine   
43  2023-07-07      18:30        90           1             0          Sport   
44  2023-07-07      20:15        90           2             3  Daily Routine   
45  2023-07-07      22:00        60           0             3  Daily Routine   

    True Duration  True Hours  True Minutes  Pred Hours   Pred Min    Pred Dur  
0              46         0.0           0.0         0.0   5.024813   48.068474  
1              62         3.0           3.0         5.0  22.780893   77.327356  
2     